### ISSUE TITLE
"afr-pending-xattr" option is not created in client volfile for thin-arbiter

### ISSUE THREAD

**Issue by itisravi** [gluster/glusterd2#1006]
When you create  thin-arbiter volumes, the  `afr-pending-xattr` xlator option (which in turn is based on the client xlator names) is populated with only the 1st two (i.e. data bricks). The comma separated value needs to include thin-arbiter brick as well.

**Comment by itisravi** [comment]
@karthik-us @aspandey @aravindavk

**Comment by aspandey** [comment]
we need this issue to be fixed asap as it is blocking our testing for demo.

**Comment by aspandey** [comment]
@amarts

**Comment by aravindavk** [comment]
RCA: Since the thin-arbiter brick is not stored as brick internally, it is not added to the list of xattrs.
