### ISSUE TITLE
add github templates

### ISSUE THREAD

**Issue by Madhu-1** [gluster/glusterd2#1011]
- [x] Template to create  issue
- [ ] Template to create pull request

**Comment by prashanthpai** [comment]
We'll be moving to Gerrit soon, don't bother do it for PRs ;)

**Comment by atinmu** [comment]
@Madhu-1 Is the template to create pull request still pending? Might be worth to have it sooner as it helps in following a commit format discipline.

**Comment by Madhu-1** [comment]
Closing this one as we have issue template
