### ISSUE TITLE
Volume creation is failing after 59 volumes  with 30 node cluster

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1026]
-> Created 30 node cluster 
-> Tried to create 200 volumes through script 
-> It's distributed-replica volume 10x3 (means each volume will be having  30 bricks )
-> One brick from each node that means 30 bricks form 30 nodes
-> Volume creation failing with below error

Volume creation failed

Error: Request failed with HTTP Status code 500
Transaction step vol-create.StoreVolume failed on peer 5a011251-efb4-4efe-b9dc-b25b345c6634 with error: etcdserver: request is too large

i didn't find any logs for volume creation failed

After that I have tried to create single brick volume manually without script on 30 node cluster setup.
actually volume creation is successful,  but got error message like below 

./glustercli volume create vol1 10.70.42.199:/bricks/brick0/vol1
error message:

Volume creation failed

Error: Post http://127.0.0.1:24007/v1/volumes: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Then tried to start the volume, failed with below error

/glustercli volume start vol1
volume start failed

Error: Post http://127.0.0.1:24007/v1/volumes/vol1/start: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Again tried to start the volume, this time volume started successfully
./glustercli volume start vol1

Volume vol1 started successfully

**Comment by prashanthpai** [comment]
> -> Created 30 node cluster

How ? External etcd ? Elastic etcd ? Is it 30 VMs ? Is it 30 containers ?

> -> Tried to create 200 volumes through script

How ? Normal volume ? Smart dynamic volume ?

> -> Volume creation failing with below error

Which among the 30 volumes ? first one ? 10th one ?

> Transaction step vol-create.StoreVolume failed on peer 5a011251-efb4-4efe-b9dc-b25b345c6634 with error: etcdserver: request is too large

Please attach etcd logs and glusterd2 logs. Also share disk usage on these nodes (including the nodes that has etcd).

**Comment by rmadaka** [comment]
@prashanthpai : Volume creation is failing with 3(clustered) node external etcd server also  after 99 volume with below error.

Volume creation failed

Error: Request failed with HTTP Status code 500
etcdserver: mvcc: database space exceeded

**Comment by rmadaka** [comment]
@prashanthpai : Not able to start volumes also with below error.

volume start failed

Error: Request failed with HTTP Status code 500
etcdserver: mvcc: database space exceeded

**Comment by rmadaka** [comment]
Not able to perform any commands

[root@dhcp42-199 gd2_new]# glustercli volume status
Volume : drep1
Error getting Volume status

Error: Request failed with HTTP Status code 500
etcdserver: mvcc: database space exceeded

**Comment by prashanthpai** [comment]
@rmadaka Please report the size of etcd data directories using the `du` command.

**Comment by prashanthpai** [comment]
Also run `etcdctl defrag --cluster --endpoints=<etcd-endpoint-here>` and check if space usage of etcd datadir goes down. Please post the output of `du -h` before and after running the command.

**Comment by prashanthpai** [comment]
On my local single node system, I created 100 volumes, I don't see as much usage as your reproducer:

```sh
$ glustercli volume list | wc -l
104

$ du -h /tmp/default.etcd/
245M	/tmp/default.etcd/member/wal
159M	/tmp/default.etcd/member/snap
404M	/tmp/default.etcd/member
404M	/tmp/default.etcd/
```

**Comment by rmadaka** [comment]
@prashanthpai  i think , my setup is having 30 node cluster and trying to create 10x3 volumes that means  each volume contain 30 bricks.  might be because of large no.of nodes and more no.of bricks for each volume.

**Comment by rmadaka** [comment]
@prashanthpai 

Before running command:

node1:

8.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/rfc
4.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/platforms
8.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/dev
40K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/benchmarks
360K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2
68K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/upgrades
8.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/rfc
24K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/platforms
332K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/op-guide
68K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/learning
20K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-internal
92K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-guide/apispec/swagger
92K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-guide/apispec
180K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-guide
40K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/benchmarks
1.2M	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation
876K	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd/member/snap
123M	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd/member/wal
123M	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd/member
123M	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd
2.1G	./gd2_new/etcd-v3.3.8-linux-amd64/infra0.etcd/member/snap
1.1G	./gd2_new/etcd-v3.3.8-linux-amd64/infra0.etcd/member/wal
3.1G	./gd2_new/etcd-v3.3.8-linux-amd64/infra0.etcd/member
3.1G	./gd2_new/etcd-v3.3.8-linux-amd64/infra0.etcd
3.3G	./gd2_new/etcd-v3.3.8-linux-amd64

node2:

./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/rfc
4.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/platforms
8.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/dev
40K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/benchmarks
360K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2
68K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/upgrades
8.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/rfc
24K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/platforms
332K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/op-guide
68K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/learning
20K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-internal
92K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-guide/apispec/swagger
92K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-guide/apispec
180K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-guide
40K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/benchmarks
1.2M	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation
876K	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd/member/snap
123M	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd/member/wal
123M	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd/member
123M	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd
2.0G	./gd2_new/etcd-v3.3.8-linux-amd64/infra1.etcd/member/snap
856M	./gd2_new/etcd-v3.3.8-linux-amd64/infra1.etcd/member/wal
2.9G	./gd2_new/etcd-v3.3.8-linux-amd64/infra1.etcd/member
2.9G	./gd2_new/etcd-v3.3.8-linux-amd64/infra1.etcd
3.0G	./gd2_new/etcd-v3.3.8-linux-amd64

node3:

8.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/rfc
4.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/platforms
8.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/dev
40K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2/benchmarks
360K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/v2
68K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/upgrades
8.0K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/rfc
24K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/platforms
332K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/op-guide
68K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/learning
20K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-internal
92K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-guide/apispec/swagger
92K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-guide/apispec
180K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/dev-guide
40K	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation/benchmarks
1.2M	./gd2_new/etcd-v3.3.8-linux-amd64/Documentation
876K	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd/member/snap
123M	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd/member/wal
123M	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd/member
123M	./gd2_new/etcd-v3.3.8-linux-amd64/default.etcd
2.0G	./gd2_new/etcd-v3.3.8-linux-amd64/infra2.etcd/member/snap
920M	./gd2_new/etcd-v3.3.8-linux-amd64/infra2.etcd/member/wal
2.9G	./gd2_new/etcd-v3.3.8-linux-amd64/infra2.etcd/member
2.9G	./gd2_new/etcd-v3.3.8-linux-amd64/infra2.etcd
3.1G	./gd2_new/etcd-v3.3.8-linux-amd64

defrag failed with below error:

ETCDCTL_API=3 etcdctl defrag --endpoints=10.70.42.195:2379,10.70.41.171:2379,10.70.41.173:2379
Failed to defragment etcd member[10.70.42.195:2379] (context deadline exceeded)
Failed to defragment etcd member[10.70.41.171:2379] (context deadline exceeded)
Failed to defragment etcd member[10.70.41.173:2379] (context deadline exceeded)

**Comment by Madhu-1** [comment]
@rmadaka can you test these scenarios again with the configuration suggested by @prashanthpai

**Comment by rmadaka** [comment]
@Madhu-1, currently paused gd2 scalability testing as we are currently concentrating on GCS.

**Comment by atinmu** [comment]
This is now fixed in GCS with the etcd tunings.
