### ISSUE TITLE
After system reboot glusterd2 services are not coming up automatically

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1043]
-> Installed glusterd2 with rpm
-> Then started glusterd2 services using "systemctl start glusterd2"
-> Now glusterd2 is running
-> Then reboot the node
-> Glusterd2 status will be in inactive state.
-> We need to start glusterd2 services manually, then glusterd2 services will be active state

**Comment by kshlm** [comment]
Did you `systemctl enable glusterd2.service`? Also, if you're using elasticetcd, GD2 will not come up if all nodes are rebooted together.
