### ISSUE TITLE
Peer add is failing with incorrect error message

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1045]
-> Terminate the external etcd which is in running state
-> Then try to perform the peer add
-> Peer add is failing with error  peer is part of another cluster which is not expected
# glustercli peer add 10.70.42.78
Peer add failed

Error: Request failed with HTTP Status code 500
peer is part of another cluster

**Comment by aravindavk** [comment]
Error is "peer is part of another cluster". Looks like setup and cleanup issue. Please provide more details about external etcd usage details and current configuration and node details.

**Comment by prashanthpai** [comment]
> -> Terminate the external etcd which is in running state

In that case, how is the error not expected ? Just terminating external etcd isn't equivalent to peer remove/detach.
