### ISSUE TITLE
Need consistent gluster volume status

### ISSUE THREAD

**Issue by pranithk** [gluster/glusterd2#1046]
For monitoring glusterfs volumes, we need gluster volume status output every X seconds (at the moment X is 30 seconds) Based on my discussions with @prashanthpai, at the moment volume status doesn't take any lock while getting the status of the bricks etc, so there is a possibility of getting a snapshot of status that is not consistent while say volume stop is in progress. Goal is to be able to build alerts to the admin/users based on this output and if for any reason we capture volume status while a volume stop is in progress, there is a chance of seeing some bricks that are down and that can lead to alerts to the user which are not intended. It is also important to not fail volume status command when another transaction is in progress as that will also prevent monitoring from happening. I want to understand if we can make changes in gd2 to achieve this goal of easier integration by monitoring tools for observing volume status continuously and add alerts that won't give any false +ves.

@kshlm @aravindavk @atinmu @prashanthpai Any thoughts?

**Comment by prashanthpai** [comment]
@pranithk I have filed an issue for this here: https://github.com/gluster/glusterd2/issues/1025

**Comment by pranithk** [comment]
@prashanthpai thanks, will close this.
