### ISSUE TITLE
Metrics for monitoring GD2

### ISSUE THREAD

**Issue by pranithk** [gluster/glusterd2#1047]
I am raising this issue to figure out the metrics that need to be tracked from GD2 so that it is easier to monitor that GD2 is functioning as expected.

@kshlm @prashanthpai @aravindavk let me know.

**Comment by pranithk** [comment]
pinging again to find if you guys had a chance to find the metrics that are important for gd2.

**Comment by atinmu** [comment]
I'm bit confused on the requirements here. Are you looking for the metrics which represent the overall state of the cluster (be it from management  or the I/O plane)? If yes then probably https://github.com/gluster/glusterd2/issues/483 is more detailed out than this. If that's not the intention what do you mean by "if GD2 is functioning as expected or not" ?

**Comment by prashanthpai** [comment]
@atinmu He means metrics about glusterd2 itself.

I don't think we have such a list yet. Our `/statedump` endpoint is glusterd2's node-specific metrics collection endpoint.

**Comment by vredara** [comment]
@pranithk if we get node-level, where can we aggregate the metrics to get volume-level stats?. we have to figure out the way to collect volume-level stats like free space, total space.

**Comment by pranithk** [comment]
@vredara They are different from GD2 metrics. This issue is trying to find what in GD2 need to come in metrics.

**Comment by prashanthpai** [comment]
@pranithk @vredara All volume-level data aggregation should be done by glusterd2. The consumers of metrics should only consume such metrics from ant one glusted2 instance.

The node level metrics is only for metrics about one glusterd2 instance.

**Comment by vredara** [comment]
@pranithk @prashanthpai makes sense. we can collect node-level metrics for glusterd2..for vol level we will collect only from one glusterd2 instance.

**Comment by aravindavk** [comment]
Glusterd2 process monitoring is already handled in gluster/gluster-prometheus project. Is there any other metrics required to monitor Glusterd2?

This issue description is incomplete, please update with specific metric requirement.

**Comment by pranithk** [comment]
@aravindavk This was an issue we raised very early to check what metrics are needed from GD2. If it is already handled, we can close the issue.
