### ISSUE TITLE
Need a way of knowing if gd2 on a node is leader or not

### ISSUE THREAD

**Issue by pranithk** [gluster/glusterd2#1050]
We want to avoid collecting same metrics from all the nodes in cluster as much as possible. Metrics collection process  running on a node needs to know if GD2 on that same node is leader or not so that extra information can be collected just from that node and for all the other nodes it doesn't collect this information.

@aravindavk  raising this issue as per our discussion.

**Comment by kshlm** [comment]
I'd like to know what you mean by a "leader".

With GD2 specifically, we still haven't yet decided if a specific peer is going to be a leader or not. We're working on updates to transaction framework #1003, which brings in a notion of a specialized node (currently calling it a cleanup leader) that just handles cleanup. Most of GD2 will still work without a specific leader.

The embedded elasticetcd have a notion of a leader. But that is specific to etcd management and separate from GD2s workings.

And also could you please explain upon the metrics that you'd collect, and the metrics that you'd collect just from the leader (if one were available).

**Comment by aravindavk** [comment]
For metrics/monitoring context, leader is an identifier. so that cluster/volume level metrics can be collected only from one node instead of collecting duplicate metrics from all node. For example `GET /v1/leader` (or some other url name), if this api can return a peer id, the metrics collection can proceed. if that node goes down the API can return different peer id.

**Comment by aravindavk** [comment]
I realized this requirement can be achieved by getting list of peers and filter only online peers. First one in the list can be used for metrics collection purpose. 

@pranithk let me know if this works for you.

**Comment by pranithk** [comment]
If I understand the infra correctly, prometheus endpoint exists on each of the nodes in the cluster and each of them only has context about what just that endpoint is doing. So to prevent duplicates, we need an answer from that node that is consistent across the cluster.
For example:
If we have 3 nodes: n1, n2, n3 and on each of these nodes if the endpoint asks for list and all the nodes give n1, n2, n3 in the same order then we can return the cluster metrics from the node n1 always.
Something like: if (mynode == list_of_nodes().first()) collect_cluster_metrics()

But this logic won't work if the order on each of the nodes is different. Also adding @vredara to the discussion to see if he is fine with this solution.

**Comment by aravindavk** [comment]
> If I understand the infra correctly, prometheus endpoint exists on each of the nodes in the cluster and each of them only has context about what just that endpoint is doing. So to prevent duplicates, we need an answer from that node that is consistent across the cluster.

local metrics will be exported from each node, only cluster/volume level metrics needs to be exported from only one node instead of exporting from all nodes.

>  if (mynode == list_of_nodes().first()) collect_cluster_metrics()

list_of_nodes().online().first()

> But this logic won't work if the order on each of the nodes is different.

Order will be same in all nodes because all API calls will fetch this list from same etcd store.

**Comment by pranithk** [comment]
@aravindavk cool, I think then that should be enough. Let us also wait to hear from @vredara

**Comment by vredara** [comment]
@pranithk looks cool to me . we can try this out in our test cluster.

**Comment by aravindavk** [comment]
Nice. Closing this issue. Please reopen if this feature required again
