### ISSUE TITLE
Stop and Start of External etcd causes to incorrect peer status 

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1054]
-> I have prepared 30  node glusterd2 cluster
-> Single external etcd running from different node not from any one the 30 node cluster
-> if i stop the external etcd wait for some time and start the external etcd
-> if i perform the peer status , all nodes peer status showing offline
-> But still i am able to perform glustercli commands on that node which is offline
For example out put of peer status from one node , that node peer status showing offline, but still i am able to perform peer status from that node

```[root@dhcp42-199 ~]# glustercli peer status
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-----+
|                  ID                  |               NAME                |  CLIENT ADDRESSES  |   PEER ADDRESSES   | ONLINE | PID |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-----+
| 06f72798-01a7-4327-a472-e360f52868c1 | dhcp42-199.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.42.199:24008 | no     |     |
|                                      |                                   | 10.70.42.199:24007 |                    |        |     |
| 0ce3b780-6ca4-4a0f-9194-27d96cb2b8d9 | dhcp43-189.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.43.189:24008 | no     |     |
|                                      |                                   | 10.70.43.189:24007 |                    |        |     |
| 121e2b82-6af2-40b2-9af0-6cba5a7d91dd | dhcp43-141.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.43.141:24008 | no     |     |
|                                      |                                   | 10.70.43.141:24007 |                    |        |     |
| 1ba8d6d2-526a-4444-a737-12f94e5b7e3b | dhcp41-224.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.41.224:24008 | no     |     |
|                                      |                                   | 10.70.41.224:24007 |                    |        |     |
| 22e8a829-d992-4a27-a259-cba75c013ece | dhcp42-213.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.42.213:24008 | no     |     |
```

if you observer above peer status command 
I have ran the peer status command from 10.70.42.199, in peer status output 10.70.42.199 showing as offline, 

please let me know which logs i need to provide ??

**Comment by aravindavk** [comment]
After stop and start of etcd, wait for some time(2-5 mins) and see the status. Just to confirm it is the keep alive issue after etcd restart.

**Comment by rmadaka** [comment]
@aravindavk , i have waited for around 1 hour after external etcd started, still it is in same condition.

**Comment by Madhu-1** [comment]
@rmadaka  please provide glusterd2 served logs, if get the ETCD output also it will be helpful ,

```ETCDCTL_API=3 etcdctl get --prefix=true "" --endpoints="127.0.0.1:2379"```

replace endpoints which ETCD server ip

**Comment by atinmu** [comment]
What do you mean by stopping external etcd? Do you mean stopping all the masters or some of them partially? If etcd instance is completely down and then manually bringing them up, don't we get into a similar problem like what embedded etcd has?

**Comment by rmadaka** [comment]
@atinmu  Actually i am having one node external etcd, which is not part of cluster nodes,
i am running external etcd like below 
 ./etcd  --listen-peer-urls http://10.70.42.195:2380  --listen-client-urls http://10.70.42.195:2379  --advertise-client-urls http://10.70.42.195:2379

It will not run background, if i want to stop the etcd process, by pressing ctrl-c i am terminating the etcd process.

**Comment by atinmu** [comment]
Running etcd in a single node doesn't make much sense to me. Not sure what's the motivation of running such configuration.

@prashanthpai @aravindavk @kshlm Is this something we can even support?

**Comment by rmadaka** [comment]
@atinmu i am planning to add some more external etcd server, just started with one external etcd, while doing this faced some issues,.
as i dont have much idea on external etcd, started with one and just checking that how it is working.

**Comment by aravindavk** [comment]
> Running etcd in a single node doesn't make much sense to me. Not sure what's the motivation of running such configuration.

True, but test case is valid. Even if we use external etcd cluster, behavior of glusterd2 when external cluster goes down and comes back needs to be tested.

**Comment by rmadaka** [comment]
@Madhu-1 : i have copied logs in below machine
IP: 10.70.42.195
username: root
password: redhat

/root/etcd_log1
/root/glusterd2.log

**Comment by prashanthpai** [comment]
@rmadaka Can this be reproduced with a 3 node cluster ?

**Comment by rmadaka** [comment]
@rmadaka 3 node etcd cluster you mean?

**Comment by prashanthpai** [comment]
@rmadaka 3 node glusterd2 cluster. Can you provide reproducer steps for the same ?

**Comment by rmadaka** [comment]
I am able reproduce this issue with 3 node glusterd2 cluster as well. below are the repro steps.

1) Having 3 node GD2 cluster with single node external etcd.
2) Stop external etcd services from etcd node.
3) Wait for around 10 mints. Then start external etcd services
4) Verify peer status, all peer status showing as offline but glustercli commands are working.

```glustercli peer status
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-----+
|                  ID                  |               NAME                |  CLIENT ADDRESSES  |   PEER ADDRESSES   | ONLINE | PID |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-----+
| 46b846fd-32e8-4046-9080-fb827413ccff | dhcp35-194.lab.eng.blr.redhat.com | 127.0.0.1:24007    | dhcp35-194:24008   | no     |     |
|                                      |                                   | 10.70.35.194:24007 | 10.70.35.194:24008 |        |     |
| 5d9f6dbc-3231-4e78-93ba-148ed8fd6249 | dhcp35-33.lab.eng.blr.redhat.com  | 127.0.0.1:24007    | dhcp35-33:24008    | no     |     |
|                                      |                                   | 10.70.35.33:24007  | 10.70.35.33:24008  |        |     |
| 91b6edad-6246-4b77-9a0d-6bf92a6a1514 | dhcp35-219.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.35.219:24008 | no     |     |
|                                      |                                   | 10.70.35.219:24007 |                    |        |     |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-----+
```

**Comment by atinmu** [comment]
We need to get this fixed as early as possible.

**Comment by Madhu-1** [comment]
@rmadaka glusterd2 will take nearly  `15 to 20 sec` to connect to `ETCD` and mark itself as online.
is `gluster peer list` done after some  `20 sec` time gap of restarting `ETCD`?

**Comment by rmadaka** [comment]
@prashanthpai , once etcd is up all peer should be in online state, but here peer status is showing all peers are in offline state. 

```[root@dhcp35-219 ~]# glustercli peer status
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-----+
|                  ID                  |               NAME                |  CLIENT ADDRESSES  |   PEER ADDRESSES   | ONLINE | PID |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-----+
| 46b846fd-32e8-4046-9080-fb827413ccff | dhcp35-194.lab.eng.blr.redhat.com | 127.0.0.1:24007    | dhcp35-194:24008   | no     |     |
|                                      |                                   | 10.70.35.194:24007 | 10.70.35.194:24008 |        |     |
| 5d9f6dbc-3231-4e78-93ba-148ed8fd6249 | dhcp35-33.lab.eng.blr.redhat.com  | 127.0.0.1:24007    | dhcp35-33:24008    | no     |     |
|                                      |                                   | 10.70.35.33:24007  | 10.70.35.33:24008  |        |     |
| 91b6edad-6246-4b77-9a0d-6bf92a6a1514 | dhcp35-219.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.35.219:24008 | no     |     |
|                                      |                                   | 10.70.35.219:24007 |                    |        |     |
```
Actually once etcd is up, all peers should be in online state.  but if you observe above output all peers are in offline state still i am able to run glustercli peer status command.

Here my expectation is that all peers should be in online state and glustercli commands should work. after stop and start of etcd.

**Comment by prashanthpai** [comment]
> Here my expectation is that all peers should be in online state and glustercli commands should work. after stop and start of etcd.

:+1:

**Comment by aravindavk** [comment]
Suspect: On Glusterd2 start, it starts a keep alive in etcd to update each peer's online status. Once etcd restarts, this keepalive in etcd is lost. We have to detect the etcd online and restart the Store to solve this issue.

https://github.com/gluster/glusterd2/blob/master/glusterd2/store/liveness.go#L59-L67

@prashanthpai @kshlm any thoughts?
