### ISSUE TITLE
Not able to run glusterd2 with the documentation steps (2 Node cluster)

### ISSUE THREAD

**Issue by anmolsachan** [gluster/glusterd2#1058]
Setup:
- 2 Node Vagrant Centos cluster.
- Glusterfs already installed and running.

Glusterd2 created a default config :  /etc/glusterd2/glusterd2.toml
```
localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = "machine2_ip:24008"
clientaddress = "machine2_ip:24007"
#restauth should be set to false to disable REST authentication in glusterd2
#restauth = false 
```
I inserted the ip of my machine in the config.

When I run : ` glusterd2 `  on machine 1, it gives error : Failed to write to log, write /var/log/glusterd2/store/elastic.log: file already closed.

When I created the config file manually and ran with its path, it gives the same error :Failed to write to log, write /var/log/glusterd2/store/elastic.log: file already closed.

**Comment by atinmu** [comment]
What's the latest on this @rishubhjain ? Did we try to figure out what was the gap?

@anmolsachan were you able to fix this up by following #1076 ?

**Comment by anmolsachan** [comment]
@atinmu I will try it with the https://github.com/gluster/glusterd2/pull/1076 and provide an update.

**Comment by anmolsachan** [comment]
@atinmu  The PR works for me. Sorry for the delayed response. 
Closing the issue.
