### ISSUE TITLE
When peer is removed from the cluster it said peer remove failed, But it had actually removed the peer from the cluster.

### ISSUE THREAD

**Issue by Shrivaibavi** [gluster/glusterd2#1062]
Description:
While trying to add and remove a peer from a cluster repeatedly. It said that the peer remove failed. But when checked in the peer list it actually had removed that node from the cluster. 

Steps:
[root@dhcp35-201 ~]# glustercli peer add 10.70.35.5
Peer add successful
+--------------------------------------+---------------------------------+------------------+------------------+
|                  ID                  |              NAME               | CLIENT ADDRESSES |  PEER ADDRESSES  |
+--------------------------------------+---------------------------------+------------------+------------------+
| 9a90a179-fbcb-434e-a1f0-a08b4d2a7f51 | dhcp35-5.lab.eng.blr.redhat.com | 127.0.0.1:24007  | 10.70.35.5:24008 |
|                                      |                                 | 10.70.35.5:24007 |                  |
+--------------------------------------+---------------------------------+------------------+------------------+
[root@dhcp35-201 ~]# glustercli peer remove 9a90a179-fbcb-434e-a1f0-a08b4d2a7f51
Peer remove success
[root@dhcp35-201 ~]# glustercli peer list
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+------+
|                  ID                  |               NAME                |  CLIENT ADDRESSES  |   PEER ADDRESSES   | ONLINE | PID  |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+------+
| 624c0de6-6c3d-4ef3-aef7-761ae78d57cc | dhcp35-179.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.35.179:24008 | yes    | 1624 |
|                                      |                                   | 10.70.35.179:24007 |                    |        |      |
| 657bbaf5-df53-41dd-b621-62f7dd33d1b5 | dhcp35-201.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.35.201:24008 | yes    | 3254 |
|                                      |                                   | 10.70.35.201:24007 |                    |        |      |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+------+
[root@dhcp35-201 ~]# glustercli peer add 10.70.35.5
Peer add successful
+--------------------------------------+---------------------------------+------------------+------------------+
|                  ID                  |              NAME               | CLIENT ADDRESSES |  PEER ADDRESSES  |
+--------------------------------------+---------------------------------+------------------+------------------+
| 9a90a179-fbcb-434e-a1f0-a08b4d2a7f51 | dhcp35-5.lab.eng.blr.redhat.com | 127.0.0.1:24007  | 10.70.35.5:24008 |
|                                      |                                 | 10.70.35.5:24007 |                  |
+--------------------------------------+---------------------------------+------------------+------------------+
[root@dhcp35-201 ~]# glustercli peer remove 9a90a179-fbcb-434e-a1f0-a08b4d2a7f51
Peer remove success
[root@dhcp35-201 ~]# glustercli peer add 10.70.35.5
Peer add successful
+--------------------------------------+---------------------------------+------------------+------------------+
|                  ID                  |              NAME               | CLIENT ADDRESSES |  PEER ADDRESSES  |
+--------------------------------------+---------------------------------+------------------+------------------+
| 9a90a179-fbcb-434e-a1f0-a08b4d2a7f51 | dhcp35-5.lab.eng.blr.redhat.com | 127.0.0.1:24007  | 10.70.35.5:24008 |
|                                      |                                 | 10.70.35.5:24007 |                  |
+--------------------------------------+---------------------------------+------------------+------------------+
[root@dhcp35-201 ~]# glustercli peer remove 9a90a179-fbcb-434e-a1f0-a08b4d2a7f51
Peer remove failed

Error: Request failed with HTTP Status code 500
failed to send leave cluster request

[root@dhcp35-201 ~]# glustercli peer list
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+------+
|                  ID                  |               NAME                |  CLIENT ADDRESSES  |   PEER ADDRESSES   | ONLINE | PID  |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+------+
| 624c0de6-6c3d-4ef3-aef7-761ae78d57cc | dhcp35-179.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.35.179:24008 | yes    | 1624 |
|                                      |                                   | 10.70.35.179:24007 |                    |        |      |
| 657bbaf5-df53-41dd-b621-62f7dd33d1b5 | dhcp35-201.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.35.201:24008 | yes    | 3254 |
|                                      |                                   | 10.70.35.201:24007 |                    |        |      |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+------+
log file:
 
[glusterd2.log](https://github.com/gluster/glusterd2/files/2223761/glusterd2.log)

**Comment by atinmu** [comment]
Is this test done with external or embedded etcd?

**Comment by Shrivaibavi** [comment]
@atinmu I am not using any external etcd

**Comment by prashanthpai** [comment]
@Shrivaibavi Please retry on latest nightlies as this is fixed by @oshankkumar in https://github.com/gluster/glusterd2/pull/1109
