### ISSUE TITLE
failed to start a volume if request body is not present

### ISSUE THREAD

**Issue by oshankkumar** [gluster/glusterd2#1065]
curl -X POST http://192.168.122.253:24007/v1/volumes/mydistvol/start
{"errors":[{"code":1,"message":"EOF"}]}
Please refer start volume in  [Quick Start User Guide](https://github.com/gluster/glusterd2/blob/master/doc/quick-start-user-guide.md)

**Comment by prashanthpai** [comment]
The commit 55ed87fc by @Madhu-1 made it mandatory for volume start to have a body. My personal opinion is that the force flag can be a query parameter although it may seem odd. Having to specify a body seems more odd to me for volume start operation.

@Madhu-1 @aravindavk Thoughts ?

**Comment by aravindavk** [comment]
for uniformity(except get requests) I prefer requestBody. We can skip unmarshal if `req` is `nil`

**Comment by Madhu-1** [comment]
as @aravindavk said we can skip unmarshaling if request body is ```nil``` in this scenario.

**Comment by prashanthpai** [comment]
> for uniformity(except get requests) I prefer requestBody. We can skip unmarshal if req is nil

LGTM :+1:
