### ISSUE TITLE
Make management operations involving some form of mount easier/faster

### ISSUE THREAD

**Issue by pranithk** [gluster/glusterd2#1069]
Form @raghavendrahg I heard yesterday that there is an initiative to fix graph switch issues. So based on that approach, I think it is better to upgrade shd process into a new daemon which will have graph of each volume (I think till dht excluding perf xlators should suffice). We can keep sending rpc calls from glusterd/glusterd2 to get status from bricks/statfs/heal-info-counts etc. This is not possible without fixing https://github.com/gluster/glusterfs/issues/476

On my laptop with all local bricks glfs_init() takes .3 seconds so if we have 100s of volume, cost of collecting metrics for each volume will be a lot more as we tend to get these serially. Doing this in parallel may reduce the time to collect the info/metrics but doing so many mounts/glfs_init() will increase the memory usage drastically. Since we have shd running for all volumes always, I was thinking why not just promote it to accept more responsibility.

Thoughts?

**Comment by sankarshanmukhopadhyay** [comment]
Please let's agree to stop using laptops as setting expectations or, origins of any arithmetic.

**Comment by pranithk** [comment]
@sankarshanmukhopadhyay It is easier to achieve lower bounds in some cases. So it has its +ves.

**Comment by sankarshanmukhopadhyay** [comment]
It is nicer to use https://github.com/gluster/softserve than the laptop. The hardware detail and related bits are easily understood.

**Comment by pranithk** [comment]
@sankarshanmukhopadhyay In general it is better to use bare metal for doing anything related to perf. So softserve may not be a a good setup to do that. Physical machines need to be reserved and sometimes it takes weeks to get them, so that process is followed to do something that is time consuming and larger scope. That probably is the reason why you may see developers throwing numbers from their laptops for something quick and dirty.

**Comment by aravindavk** [comment]
@pranithk please elaborate the expectations from Glusterd2. Will this involves volfile change(or new volfile required) or any new API required from glusterd2.

**Comment by pranithk** [comment]
@aravindavk Let us wait and find if larger team agrees with this change. Then I can give the exact changes we need from fs/glusterd2 etc. I am waiting for feedback at the moment.

**Comment by pranithk** [comment]
@aravindavk @kshlm @prashanthpai I am not able to edit the labels. Do you have any label that means observability? I would like to tag this issue with that and easily track the dependencies on gd2. Please let me know how to go about doing that on gd2 project.

**Comment by pranithk** [comment]
@prashanthpai On glusterfs, I am tracking all the issues required for monitoring/observability project using "FA: observability" label. If you guys don't mind could you create one and tag this one with that same label?

**Comment by itisravi** [comment]
I don't understand the problem description or the topic of the github issue. Could you please elaborate on what do you mean by "Make management operations involving some form of mount easier/faster" and " and " I think it is better to upgrade shd process into a new daemon which will have graph of each volume" mean? What is the significance of glfs_init for shd?

**Comment by pranithk** [comment]
> "Make management operations involving some form of mount easier/faster"

There are CLI commands which either use glfs_init() or mount of the volume to give output. For example:
"gluster volume heal <volname> info summary" needs to do glfs_init()(this is similar to mounting the volume) and only then it can do the necessary actions to give the heal-counts. We recently had a discussion about reducing time to get heal counts on the issue: https://github.com/gluster/glusterfs/issues/474, even after this enhancement because glfs_init() itself is taking 0.3 seconds, we can not serve heal info summary of all volumes in cluster under 5 seconds with current implementation(This time limit is brought in by operators as mentioned by John Strunk on gluster-devel[1] and the scale we need to support is 1000 volumes). So even if we do the enhancement proposed in https://github.com/gluster/glusterfs/issues/474, we can not give information for all the volumes in the time limit. I think similar kind of mounting happens for other commands too like quota usage etc. Problem that needs to be solved is eliminating time for mounting.
Hope that clarifies why we need to "Make management operations involving some form of mount easier/faster".

To prevent this kind of latency, we need a process with all volume client graphs loaded. This process should accept RPCs from other processes to give the information that only a mount would be used previously. We can then remove the bottleneck of mounting from executing these commands. But loading a new process with all volumes' client graph will consume a lot of memory. So I was thinking may be we should retire existing daemon like shd and create a new process (io-daemon) which loads graphs till dht at least for all volumes so that we can have the infra we need to serve volume specific io details. This new process will also do the job of shd. With this solution, "gluster volume heal <volname> summary" can be served by just sending an rpc from glusterd/glusterd2 or any other process to this daemon. We can also retire quotad and have that functionality in this io-daemon etc. Hope that clarifies your next question about
> I think it is better to upgrade shd process into a new daemon which will have graph of each volume

Initially I had doubts about proposing this solution as the io-daemons are always re-started to avoid graph-switch upon attach/detach of new volumes, but looks like that problem is being worked upon with priority as the same issue is a pain point even in brick-mux. So this solution should work fine for providing the infra to reduce the time for any io related commands/apis. I believe even gd2 does some form of mount to get statfs information. Those can also be converted into this.

[1] - https://lists.gluster.org/pipermail/gluster-devel/2018-July/055044.html

**Comment by xhernandez** [comment]
Pranith and I discussed a bit about this some days ago. The idea seems fine to me. My only concern is probably semantic.

For this to work, we need a process with all existing volumes in the cluster already mounted (or connected with glfs_init). Considering that we could have hundreds or thousands of volumes, creating an additional daemon to handle monitoring requests seems a waste of resources when we'll already have another daemon with access to almost all volumes (the self-heal daemon works for replicated and dispersed volumes, but not for pure distributed ones).

So it seems reasonable to use the same daemon for self-heal and monitoring, but I think it shouldn't be called the "self-heal daemon". Maybe self-heal should only be a subprocess inside this daemon.

**Comment by pranithk** [comment]
> So it seems reasonable to use the same daemon for self-heal and monitoring, but I think it shouldn't be called the "self-heal daemon". Maybe self-heal should only be a subprocess inside this daemon.

Yes, I am calling it io-daemon, but I don't like the name :-).

**Comment by xhernandez** [comment]
Ops, missed the name...

What about gateway-daemon (gw-daemon), or bridge-daemon, or link-daemon ? as it will be used as a connection between external world and existing volumes.

**Comment by itisravi** [comment]
@pranithk Thanks for the explanation. If I understand this correctly, once we have this new daemon in place, we will be retiring glfsheal, and this new daemon will be used to serve heal info and its sub commands in addition to healing files. In that sense, is it the same as how things used to work earlier in afr-v1, where shd was catering to heal-info requests before glfsheal was written?

**Comment by pranithk** [comment]
@itisravi At the moment heal info summary will be moved into this daemon, but I don't think we can do just heal info with this model because of rpc issues we faced for big outputs when this command was in glustershd.

**Comment by pranithk** [comment]
@amarts If I understand @jstrunk's mail correctly, if we can't get metrics to be collected in 5 seconds, we can't integrate with operators? So I am thinking we need to target this for gcs release?

**Comment by aravindavk** [comment]
Closing this issue since gluster-prometheus project collects subvolume/brick utilization without mounting the volume. Please re-open if anything still needs to be fixed from gd2
