### ISSUE TITLE
etcd: Start etcd server with optimal args related to size

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#1070]
Note: This issue concerns both embedded etcd and external etcd.

While debugging issue https://github.com/gluster/glusterd2/issues/1026, it was noted that etcd in its default configuration takes up a non-trivial amount of space on disk to store its data. The default storage size limit is 2GB, configurable with up to 8GB.

Here's a quick experiment (single node external etcd, single node glusterd2 cluster):

**Default space utilisation by etcd, as soon as single node glusterd2 is started:**

```sh
$ du -h /tmp/default.etcd/
123M	/tmp/default.etcd/member/wal
32K	/tmp/default.etcd/member/snap
123M	/tmp/default.etcd/member
123M	/tmp/default.etcd/
```

**Creating 100 volumes, each containing one brick:**
```sh
$ for i in {1..100}; do glustercli volume create test$i 7be40ebc-3f71-4d1b-857a-dad8f10d2793:/export/brick$i/data --force ; done
```

**Etcd space utilisation:**
```sh
$ du -h /tmp/default.etcd/
245M	/tmp/default.etcd/member/wal
161M	/tmp/default.etcd/member/snap
405M	/tmp/default.etcd/member
405M	/tmp/default.etcd/
```

**Deleting all 100 volumes:**
```sh
$ for i in {1..100}; do glustercli volume delete test$i ; done
```

**Etcd space utilisation:**
```sh
$ du -h /tmp/default.etcd/
245M	/tmp/default.etcd/member/wal
161M	/tmp/default.etcd/member/snap
405M	/tmp/default.etcd/member
405M	/tmp/default.etcd/
```

Key takeaway here is that deleting key-values does not reclaim the space on disk. The `defrag` operation releases this storage space back to the file system. One can find more information [here](https://github.com/coreos/etcd/blob/master/Documentation/op-guide/maintenance.md#defragmentation
)

**Get last etcd revision number:**
```sh
$ ETCDCTL_API=3 etcdctl endpoint status --endpoints=127.0.0.1:2379 -w json | grep revision
```
```json
[{"Endpoint":"127.0.0.1:2379","Status":{"header":{"cluster_id":14841639068965178418,"member_id":10276657743932975437,"revision":27363,"raft_term":2},"version":"3.3.9","dbSize":168402944,"leader":10276657743932975437,"raftIndex":27658,"raftTerm":2}}]
```

**Do compaction followed by etcd defrag:**
```sh
$ ETCDCTL_API=3 etcdctl compaction --physical=true --endpoints=127.0.0.1:2379 27363
compacted revision 27363

$ ETCDCTL_API=3 etcdctl defrag --endpoints=http://127.0.0.1:2379
Finished defragmenting etcd member[http://127.0.0.1:2379]
```

**Etcd space utilisation:**
```sh
$ du -h /tmp/default.etcd/
245M	/tmp/default.etcd/member/wal
148K	/tmp/default.etcd/member/snap
245M	/tmp/default.etcd/member
245M	/tmp/default.etcd/
```

```sh
$ ls -lh /tmp/default.etcd/member/wal/
total 245M
-rw-------. 1 ppai ppai 62M Jul 26 10:13 0000000000000000-0000000000000000.wal
-rw-------. 1 ppai ppai 62M Jul 26 10:13 0000000000000001-0000000000003481.wal
-rw-------. 1 ppai ppai 62M Jul 26 10:18 0000000000000002-00000000000066d1.wal
-rw-------. 1 ppai ppai 62M Jul 26 10:13 0.tmp

$ ls -lh /tmp/default.etcd/member/snap/
total 148K
-rw-------. 1 ppai ppai 148K Jul 26 10:18 db
```

The actual compacted `db` size is less. But the `*.wal` files takes up space.

Summary of etcd tunables and operations related to size:

**etcd tunables**
* `--quota-backend-bytes`
* `--max-snapshots`
* `--max-wals`
* `--auto-compaction-mode`
* `--auto-compaction-retention`
* `--snapshot-count`

**etcdctl operations**
* `etcdctl defrag`
* `etcdctl compaction`

Explanation of above tunables can be found by running `etcd --help` and `etcdctl --help` respectively.

The information posted above should eventually end up in some document. When we have some real usage data of how glusterd2 access pattern influences etcd backend size usage, we can come up with some recommendations for values to above tunables.

**Comment by atinmu** [comment]
This is already taken care of in GCS deolyment yaml for etcd.
