### ISSUE TITLE
Batch storing volume info in etcd as single etcd txn

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#1079]
A glance at the following screenshot by @sseshasa reveals that `storeVolinfo` takes a lot of time:

![screenshot_20180725_141008](https://user-images.githubusercontent.com/36185324/43245169-f7c88aa6-90ca-11e8-976a-b76c82d9cb26.png)

The originator node txn step `storeVolinfo` took **68% of time taken** to complete entire volume operation.

```go
// storeVolInfo uses to store the volinfo based on key and to generate client volfile
func storeVolInfo(c transaction.TxnCtx, key string) error {
        var volinfo volume.Volinfo
        if err := c.Get(key, &volinfo); err != nil {
                c.Logger().WithError(err).WithField(
                        "key", "volinfo").Debug("Failed to get key from store")
                return err
        }

        if err := volume.AddOrUpdateVolumeFunc(&volinfo); err != nil {
                c.Logger().WithError(err).WithField(
                        "volume", volinfo.Name).Debug("failed to store volume info")
                return err
        }

        if err := volgen.Generate(); err != nil {
                c.Logger().WithError(err).WithField(
                        "volume", volinfo.Name).Debug("failed to generate volfiles")
                return err
        }

        return nil
}
```

We can batch all PUTs (including those from volgen) originating from `storeVolinfo` to etcd as a single etcd txn. May require some code changes there but totally worth it considering the disproportionate amount of time it takes.

**Comment by aravindavk** [comment]
+1

May be Volgen is taking more time than  Volinfo, since each volfile is an entry in etcd. This time will grow when we have more volumes. We also need to enhance Volgen to generate incrementally instead of generating all volfiles.

**Comment by aravindavk** [comment]
Volfiles are not stored in etcd, only one call made to save Volinfo to store. Closing this issue. Please reopen if this can be optimized further.
