### ISSUE TITLE
Volume deleted successfully when one of node glusterd2 services are not running.

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1093]
-> Having 3 node cluster setup with external etcd running.
-> Created 1X3 replica volume
-> Don't start the volume
-> Stop the glusterd2 services on one of the node out of 3 node cluster setup
-> Then try to delete the volume 
-> Volume deleted successully

Note: 
When one of the node glusterd2 services are not running, volume deleted successfully, glusterd2 down node containing the bricks of that particular volume.
Actually  i am expecting error message like one of the peer is down.

Logs:
time="2018-07-30 16:15:17.809495" level=info msg="volume deleted" reqid=5ac9179f-fadc-4ce0-9775-42e2adc47b5f source="[volume-delete.go:95:volumes.volumeDeleteHandler]" volume-name=rep6
time="2018-07-30 16:15:17.811582" level=info msg="127.0.0.1 - - [30/Jul/2018:16:15:17 +0530] \"DELETE /v1/volumes/rep6 HTTP/1.1\" 204 0" reqid=5ac9179f-fadc-4ce0-9775-42e2adc47b5f

**Comment by prashanthpai** [comment]
> -> Stop the glusterd2 services on one of the node out of 3 node cluster setup

How did you do this ?

**Comment by rmadaka** [comment]
@prashanthpai 
How did you do this ?
systemctl stop glusterd2

**Comment by rishubhjain** [comment]
This is not reproducible, on deleting volume with a node down the volume deletion fails with error: ```
Volume deletion failed

Response headers:
X-Gluster-Cluster-Id: e56e67b7-51a3-4b22-8d5b-73679baafe91
X-Gluster-Peer-Id: 91b6edad-6246-4b77-9a0d-6bf92a6a1514
X-Request-Id: c5613588-d873-4b7d-af2e-5593b127c4b1

Response body:
node 5d9f6dbc-3231-4e78-93ba-148ed8fd6249 is probably down

```

This is tested on system with the following:
```

glusterd version: v4.1.0-159.git1a9d78c
git SHA: 1a9d78c
go version: go1.9.4
go OS/arch: linux/amd64
```

**Comment by rishubhjain** [comment]
@prashanthpai Please close this issue

**Comment by rmadaka** [comment]
glustercli volume delete rep2
Are you sure you want to delete volume rep2 [yes/no]? yes
Volume deletion failed

Response headers:X-Gluster-Cluster-Id: e56e67b7-51a3-4b22-8d5b-73679baafe91
X-Gluster-Peer-Id: 91b6edad-6246-4b77-9a0d-6bf92a6a1514
X-Request-Id: 997d7878-7a39-4ebf-b863-efb927bc6fe9

Response body:
node 5d9f6dbc-3231-4e78-93ba-148ed8fd6249 is probably down


Note: This issue is currently not reproducible, closing this issue

version: glusterd2-4.1.0-159
