### ISSUE TITLE
After removing peer and adding it again, glusterd2 goes to failed state

### ISSUE THREAD

**Issue by Akarsha-rai** [gluster/glusterd2#1101]
Steps:
-------
1) Created 3 nodes cluster, say n1, n2 and n3 and having single node external etcd.
2) From node n1, tried removing node n3 and was success.
[root@dhcp35-34 ~]# glustercli peer remove 9c375d0a-5ff2-4e0d-8f58-10c23c08d78c
Peer remove success
And checked the glusterd2 status on node n3.
[root@dhcp35-19 ~]# systemctl status glusterd2
● glusterd2.service - GlusterD2, the management service for GlusterFS (pre-release)
   Loaded: loaded (/usr/lib/systemd/system/glusterd2.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-07-30 18:08:02 IST; 3min 55s ago
 Main PID: 1629 (glusterd2)
   CGroup: /system.slice/glusterd2.service
           └─1629 /usr/sbin/glusterd2 --config=/etc/glusterd2/glusterd2.toml

Jul 30 18:08:02 dhcp35-19.lab.eng.blr.redhat.com systemd[1]: Started GlusterD2, the management serv...).
Jul 30 18:08:02 dhcp35-19.lab.eng.blr.redhat.com systemd[1]: Starting GlusterD2, the management ser.....
Jul 30 18:11:35 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: grpc: addrConn.resetTransport fail...}
Jul 30 18:11:36 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: grpc: addrConn.resetTransport fail...}
Jul 30 18:11:38 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: grpc: addrConn.resetTransport fail...}
Jul 30 18:11:40 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: Failed to dial localhost:2379: con....
Hint: Some lines were ellipsized, use -l to show in full.
3) From node n1, tried adding node n3 which failed with error.
[root@dhcp35-34 ~]# glustercli peer add 10.70.35.19
Peer add failed

Error: Request failed with HTTP Status code 500
failed to send join cluster request
4) Checked the glusterd2 status on node n3 which is in falied state.
[root@dhcp35-19 ~]# systemctl status glusterd2
● glusterd2.service - GlusterD2, the management service for GlusterFS (pre-release)
   Loaded: loaded (/usr/lib/systemd/system/glusterd2.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-07-30 18:12:11 IST; 5s ago
  Process: 1629 ExecStart=/usr/sbin/glusterd2 --config=/etc/glusterd2/glusterd2.toml (code=exited, status=2)
 Main PID: 1629 (code=exited, status=2)

Jul 30 18:12:11 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: /builddir/build/BUILD/glusterd2-v4...c
Jul 30 18:12:11 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: github.com/gluster/glusterd2/vendo...)
Jul 30 18:12:11 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: /builddir/build/BUILD/glusterd2-v4...8
Jul 30 18:12:11 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: github.com/gluster/glusterd2/vendo...)
Jul 30 18:12:11 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: /builddir/build/BUILD/glusterd2-v4...f
Jul 30 18:12:11 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: created by github.com/gluster/glus...1
Jul 30 18:12:11 dhcp35-19.lab.eng.blr.redhat.com glusterd2[1629]: /builddir/build/BUILD/glusterd2-v4...1
Jul 30 18:12:11 dhcp35-19.lab.eng.blr.redhat.com systemd[1]: glusterd2.service: main process exited...NT
Jul 30 18:12:11 dhcp35-19.lab.eng.blr.redhat.com systemd[1]: Unit glusterd2.service entered failed ...e.
Jul 30 18:12:11 dhcp35-19.lab.eng.blr.redhat.com systemd[1]: glusterd2.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

Logs:
-------
Node n1 log:
----------------
time="2018-07-30 18:10:40.261862" level=info msg="peer connected to store" id=e0bfb6ad-9104-4752-8599-5676f08619e4 source="[liveness.go:48:events.(*livenessWatcher).Watch]"
time="2018-07-30 18:10:40.264664" level=info msg="new peer joined our cluster" peer="10.70.35.163:24008" peerid=e0bfb6ad-9104-4752-8599-5676f08619e4 reqid=5d20499d-8d5c-4210-af97-dc690a7902df source="[addpeer.go:96:peers.addPeerHandler]"
time="2018-07-30 18:10:40.267005" level=info msg="127.0.0.1 - - [30/Jul/2018:18:10:40 +0530] \"POST /v1/peers HTTP/1.1\" 201 264" reqid=5d20499d-8d5c-4210-af97-dc690a7902df
time="2018-07-30 18:10:44.290479" level=info msg="peer connected to store" id=26e453dd-6368-43da-a5c8-f6a2c16b4d24 source="[liveness.go:48:events.(*livenessWatcher).Watch]"
time="2018-07-30 18:10:44.292737" level=info msg="new peer joined our cluster" peer="10.70.35.19:24008" peerid=26e453dd-6368-43da-a5c8-f6a2c16b4d24 reqid=4421cf04-3f2e-44a5-8c56-65c54ccb7e91 source="[addpeer.go:96:peers.addPeerHandler]"
time="2018-07-30 18:10:44.295724" level=info msg="127.0.0.1 - - [30/Jul/2018:18:10:44 +0530] \"POST /v1/peers HTTP/1.1\" 201 261" reqid=4421cf04-3f2e-44a5-8c56-65c54ccb7e91
time="2018-07-30 18:10:48.723104" level=info msg="127.0.0.1 - - [30/Jul/2018:18:10:48 +0530] \"GET /v1/peers HTTP/1.1\" 200 818" reqid=6f162030-4d9c-41b5-b7e7-f61c15015803
time="2018-07-30 18:11:35.533858" level=info msg="peer disconnected from store" id=26e453dd-6368-43da-a5c8-f6a2c16b4d24 source="[liveness.go:51:events.(*livenessWatcher).Watch]"
time="2018-07-30 18:11:40.542258" level=info msg="127.0.0.1 - - [30/Jul/2018:18:11:35 +0530] \"DELETE /v1/peers/26e453dd-6368-43da-a5c8-f6a2c16b4d24 HTTP/1.1\" 204 0" reqid=8a1c63f9-c602-4da4-87e8-752f065cfb38
time="2018-07-30 18:11:44.709745" level=info msg="127.0.0.1 - - [30/Jul/2018:18:11:44 +0530] \"GET /v1/peers HTTP/1.1\" 200 547" reqid=4b07c01f-8d98-416a-8407-82f917fb9709
time="2018-07-30 18:12:11.488246" level=error msg="failed RPC call" error="rpc error: code = 13 desc = transport is closing" remote="10.70.35.19:24008" rpc=PeerService.Join source="[peer-rpc-clnt.go:47:peers.(*peerSvcClnt).JoinCluster]"
time="2018-07-30 18:12:11.488379" level=error msg="sending Join request failed" error="rpc error: code = 13 desc = transport is closing" peer="10.70.35.19:24008" reqid=4ef6362a-9f5c-4cf4-bee5-d1581fa067cb source="[addpeer.go:82:peers.addPeerHandler]"
time="2018-07-30 18:12:11.488580" level=info msg="127.0.0.1 - - [30/Jul/2018:18:12:11 +0530] \"POST /v1/peers HTTP/1.1\" 500 72" reqid=4ef6362a-9f5c-4cf4-bee5-d1581fa067cb
Node n3 log:
----------------
time="2018-07-30 18:10:44.269422" level=info msg="handling new incoming join cluster request" remotecluster=5b297d65-e351-45c4-93ec-00a7b836c16f remotepeer=67f3c3d6-2a8c-4d29-b626-720069ce6363 source="[peer-rpc-svc.go:45:peers.(*PeerService).Join]"
time="2018-07-30 18:10:44.273533" level=warning msg="failed to close etcd session" error="grpc: the client connection is closing" source="[remote.go:66:store.(*GDStore).closeRemoteStore]"
time="2018-07-30 18:10:44.279750" level=info msg="joined new cluster" remotecluster=5b297d65-e351-45c4-93ec-00a7b836c16f remotepeer=67f3c3d6-2a8c-4d29-b626-720069ce6363 source="[peer-rpc-svc.go:90:peers.(*PeerService).Join]"
time="2018-07-30 18:11:01.082979" level=info msg="127.0.0.1 - - [30/Jul/2018:18:11:01 +0530] \"GET /v1/peers HTTP/1.1\" 200 818" reqid=b6756ba4-1ec2-40d4-bfa0-26649832e108
time="2018-07-30 18:11:35.518636" level=info msg="handling incoming leave cluster request" remotepeer=67f3c3d6-2a8c-4d29-b626-720069ce6363 source="[peer-rpc-svc.go:105:peers.(*PeerService).Leave]"
time="2018-07-30 18:11:35.521637" level=warning msg="failed to close etcd session" error="grpc: the client connection is closing" source="[remote.go:66:store.(*GDStore).closeRemoteStore]"
time="2018-07-30 18:11:40.522482" level=error msg="failed to create etcd client" error="dial tcp [::1]:2379: getsockopt: connection refused" source="[remote.go:49:store.newRemoteStore]"
time="2018-07-30 18:11:40.522578" level=error msg="failed to restart store with new endpoints" endpoints="[http://localhost:2379]" error="dial tcp [::1]:2379: getsockopt: connection refused" source="[peer-rpc-svc.go:183:peers.ReconfigureStore]"
time="2018-07-30 18:11:40.528332" level=warning msg="failed to reconfigure store with defaults" error="dial tcp [::1]:2379: getsockopt: connection refused" remotepeer=67f3c3d6-2a8c-4d29-b626-720069ce6363 source="[peer-rpc-svc.go:146:peers.(*PeerService).Leave]"
time="2018-07-30 18:12:11.467550" level=info msg="handling new incoming join cluster request" remotecluster=5b297d65-e351-45c4-93ec-00a7b836c16f remotepeer=67f3c3d6-2a8c-4d29-b626-720069ce6363 source="[peer-rpc-svc.go:45:peers.(*PeerService).Join]"

**Comment by prashanthpai** [comment]
Are you using external etcd ?

**Comment by Akarsha-rai** [comment]
@prashanthpai, yes I have used external etcd.

**Comment by prashanthpai** [comment]
This has been fixed. Can you retry ?

**Comment by Akarsha-rai** [comment]
Tried same scenario on glusterd version: v4.1.0-130.gitd83253f.
Peer remove and adding it again was success without any crash, glusterd2 was running on all nodes.

**Comment by prashanthpai** [comment]
Thank you @Akarsha-rai
