### ISSUE TITLE
Volume mounted successfully but mount point size is zero

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1102]
-> Created 1x3 replica volume
-> Volume started
-> Mount volume on client
mount -t glusterfs 10.70.35.219:/rep7 /mnt/fuse2/

-> If i check with df -h, size is showing 0(zero)
df -h /mnt/fuse2/
Filesystem          Size  Used Avail Use% Mounted on
10.70.35.219:/rep7     0     0     0    - /mnt/fuse2

-> But if i check with "mount"

10.70.35.219:/rep7 on /mnt/fuse2 type fuse.glusterfs (rw,relatime,user_id=0,group_id=0,default_permissions,allow_other,max_read=131072)

 logs:
time="2018-07-30 18:53:05.488764" level=info msg="client connected" address="10.70.35.33:49149" server=sunrpc source="[server.go:158:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-07-30 18:53:05.512936" level=info msg="client connected" address="10.70.35.33:1023" server=sunrpc source="[server.go:158:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-07-30 18:53:05.517772" level=info msg="client disconnected" address="10.70.35.33:1023" server=sunrpc source="[server.go:114:sunrpc.(*SunRPC).pruneConn]"

**Comment by prashanthpai** [comment]
This is a bug in glusterfs, not in glusterd2. Hence, closing this.
