### ISSUE TITLE
[RFE] Incremental Volgen

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#1111]
All volfiles are regenerated when Volume set, New Volume create/delete/start/stop. Volume creation time will take more time when we have more number of volumes(https://github.com/gluster/glusterd2/issues/1079#issuecomment-408316333)

Volfiles re-generation can be optimized by,

- Skip Volgen when Volume Create/Delete: Recently Volume Start and Stop is regenerating volfiles to avoid including Stopped volumes in generated Volfiles. Volfiles geneation is not required during Volume create/delete.
- When a Volume starts: 
    - Regenerate brick volfiles which belongs to that Volume
    - Regenerate cluster Volfiles
    - Regenerate client volfiles which belongs to that Volume
- When a Volume stops:
    - Regenerate Cluster Volfiles
- Volume Set/Reset:
    - Regenerate cluster Volfiles(Currently no easy mechanism to say cluster option is changed)
    - Regenerate client Volfiles of that Volume(Same as above, no easy mechanism to say client option changed)
    - Regenerate brick volfiles of that Volume(Same as above, no easy mechanism to say brick option changed)

**Comment by aravindavk** [comment]
@kshlm @prashanthpai please add if I missed anything.

@rafikc30 please add optimizations related to snapshot volumes/bricks and Snapshot related cluster volfiles if any.

**Comment by prashanthpai** [comment]
It's also required to allow volgen to create volfiles from temporary (from txn ctx) `Volinfo` - something that is not committed into final volfile namespace in etcd.

What are your thoughts on generating brick volfiles and cluster volfiles on every node, separately. Or at least let the daemons consumer temporary volfiles when they start. This may mean we pass volfile as a file argument when we restart daemons. I'm specifically trying to avoid the current orchestration we do today:

1. Commit new Volinfo to permanent etcd namespace.
2. Regenerate volfiles from permanent Volinfo.
3. Start daemon
3. Daemon will issue a `GETSPEC` to get volfiles over RPC.

The above steps are prone to state being inconsistent when the txn has to be undone.

**Comment by aravindavk** [comment]
> It's also required to allow volgen to create volfiles from temporary (from txn ctx) Volinfo - something that is not committed into final volfile namespace in etcd.

+1

> What are your thoughts on generating brick volfiles and cluster volfiles on every node, separately. Or at least let the daemons consumer temporary volfiles when they start. This may mean we pass volfile as a file argument when we restart daemons. I'm specifically trying to avoid the current orchestration we do today:

What advantages we can expect with this approach compared to current method? Except client process, all other process are not good at reconfigure.

**Comment by prashanthpai** [comment]
> What advantages we can expect with this approach compared to current method? Except client process, all other process are not good at reconfigure.

I'm hoping that it will simplify the orchestration that we do today (described in previous comment). I don't see why we need volfiles belonging to one brick to be accessible on other nodes. Both brick and daemons only connect to local glusterd2. What's the benefit in starting a brick/daemon and then waiting for it to fetch the volfile over RPC when we can pass a volfile directly during start itself ?

**Comment by aravindavk** [comment]
> I'm hoping that it will simplify the orchestration that we do today (described in previous comment). I don't see why we need volfiles belonging to one brick to be accessible on other nodes. Both brick and daemons only connect to local glusterd2. What's the benefit in starting a brick/daemon and then waiting for it to fetch the volfile over RPC when we can pass a volfile directly during start itself ?

Makes sense. Need to check how Volume set is handled in case of brick process.

**Comment by atinmu** [comment]
@aravindavk Are we ready with all the changes needed for this? If we can't close this issue by tomorrow morning IST, we'd need to move this to GCS/0.3 .

**Comment by aravindavk** [comment]
> @aravindavk Are we ready with all the changes needed for this? If we can't close this issue by tomorrow morning IST, we'd need to move this to GCS/0.3 .

I just refreshed the PR by addressing @kshlm's comments. If merging takes more time then I will move it to GCS/0.3

**Comment by aravindavk** [comment]
moving this to `GCS/0.3` since review is taking some more time.
