### ISSUE TITLE
Accept config options as environment variables

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#1112]
The easiest way to pass config values when running GD2 in containers is to use environment variables. It allows us to keep the container image simple, and avoid having custom entrypoint scripts.

Having config environment variables will allow us to easily set up the external etcd endpoints when starting a container.

This is an easy enough fix. `spf13/viper` the package we use for managing configuration, supports env variables. We just need to enable it.

**Comment by kshlm** [comment]
Building a usable GD2 container depends on this.

**Comment by aravindavk** [comment]
We can use env variables or config file for local resources like `localstatedir`, `logdir` etc.  Cluster-wide  configurations need to be stored in etcd itself as cluster configuration. For example log level, tls_enable, restauth etc.(Different settings in each node may lead to unexpected behavior)

**Comment by kshlm** [comment]
> We can use env variables or config file for local resources like localstatedir, logdir etc. Cluster-wide configurations need to be stored in etcd itself as cluster configuration. For example log level, tls_enable, restauth etc.(Different settings in each node may lead to unexpected behavior)

Configs like localstatedir, logdir etc. remain the same for all containers. These can be set in the config file when building the image.

Options like etcd-endpoint, tracing endpoints, tls certs etc. change with every deployment. These cannot be set in the config file when building the image. Allowing these to be set as environment variables, allows the deployment tool to set these as environment variables when starting the containers.

Some of these options are applicable cluster wide and could be stored in etcd (except the obvious one of etcd-endpoints). `spf13/viper` allows binding config options to etcd. But it is slightly more involved to setup, and even more so in our case as we'd need to update-config again after connecting to store. This is not really hard to do, but enabling environment variable support is much easier and simpler.

In any case, when the operator is deployed, it essentially would be storing these config values in etcd (the k8s instance probably), and be passing it around to the containers it launches. So we get that for free.
