### ISSUE TITLE
return HTTP status code as part of response in rest client

### ISSUE THREAD

**Issue by Madhu-1** [gluster/glusterd2#1128]
whoever is using the restclient should come to know for what reason it failed (whether its bad request, internal server error or not found)

if I want to delete a volume, (if it fails)we may get different errors, the current restclient returns only the error message based on that am not able to take any further action, if we return status code from restclient it will be useful

**Comment by prashanthpai** [comment]
This is already implemented AFAIK.

**Comment by prashanthpai** [comment]
https://github.com/gluster/glusterd2/blob/master/pkg/restclient/common.go#L33-L38

**Comment by Madhu-1** [comment]
AFAIK, we are returning the response error message to the caller, by this it will be hard to understand why it failed.

in case of volume delete
* does it failed because volume not found
* some internal server error
* txn locking failure etc

as per CSI if the volume is not found during the volume deletion driver should return back with success.

if we return HTTP status it will be easy further processing, as a caller, I don't need to decode error message and do the string comparison

**Comment by prashanthpai** [comment]
The entire 'http.Response' is available to rest client consumer which will contain status code too. Currently it's only set just for error cases. That's straight-forward to fix.

**Comment by prashanthpai** [comment]
This has been fixed already in PR #1154
