### ISSUE TITLE
Volume creation is failing with invalid error message if volume name is combination of special characters and characters or numbers

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1134]
Volume creation is failing with invalid error message, if volume name is combination of special characters and characters or numbers

-> If i provide volname as combination of special-characters and characters or special-characters and numbers, volume creation is failing with below error message which is invalid.

command:
glustercli volume create #sf 10.70.35.219:/bricks/brick0/test_brick1 --force
Bricks not specified

 glustercli volume create #89 10.70.35.219:/bricks/brick0/test_brick1 --force
Bricks not specified

-> If i provide the volname as only special characters, volume creation is failing with proper error message like below.

glustercli volume create @# 10.70.35.219:/bricks/brick0/test_brick --force
Volume creation failed

Response headers:
X-Gluster-Cluster-Id: e56e67b7-51a3-4b22-8d5b-73679baafe91
X-Gluster-Peer-Id: 91b6edad-6246-4b77-9a0d-6bf92a6a1514
X-Request-Id: 57c76eda-2f13-48a4-b7ce-5ca3865cb436

Response body:
invalid volume name

**Comment by Madhu-1** [comment]
@rmadaka  in terminal whatever you give after `#` is ignored

example:
```
[root@dhcp43-209 glusterd2]# df --ha
df: unrecognized option '--ha'
Try 'df --help' for more information.

[root@dhcp43-209 glusterd2]# df #--ha
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/vda2       25152516 3188768  21963748  13% /
devtmpfs         1931108       0   1931108   0% /dev
tmpfs            1940948       0   1940948   0% /dev/shm
tmpfs            1940948   16888   1924060   1% /run
tmpfs            1940948       0   1940948   0% /sys/fs/cgroup
/dev/vda3       15718400  711592  15006808   5% /var
/dev/vda1        1038336  161228    877108  16% /boot
tmpfs             388192       0    388192   0% /run/user/0
```

>glustercli volume create #sf 10.70.35.219:/bricks/brick0/test_brick1 --force
Bricks not specified
glustercli volume create #89 10.70.35.219:/bricks/brick0/test_brick1 --force
Bricks not specified

in this 2 cases, the same thing happened 

>glustercli volume create @# 10.70.35.219:/bricks/brick0/test_brick --force

in this case `@` is considered for the volume name and you got invalid volume name error

hope I have answered your questions, if you feel this issue need to be closed please close it

**Comment by rmadaka** [comment]
I agree with madhu comment , closing this issue
