### ISSUE TITLE
Volume create should accept Size in bytes

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#1135]
The K8S CSI specifies size in bytes. Which needs to be converted before being passed along to GD2 by the CSI driver. This conversion should not be needed IMO.

In addition to the volume create API, we should ensure that within GD2, in the device management and provisioning we only deal with bytes as well. This is the base unit used by the underlying tools we use (lvm, xfs-tools etc.) and which gives the most accurate control and representation.

When displaying the values to the user, the CLI or another UI can convert it into human friendly format.

**Comment by prashanthpai** [comment]
The sooner we get this cleaned up the better, from API stability standpoint. Bumping up the priority accordingly.

**Comment by atinmu** [comment]
@rishubhjain this is targeted for GCS/0.3 milestone. Where are we w.r.t the implementation?
