### ISSUE TITLE
Unable to see the glustercli peer list, When glusterd2 is actively running

### ISSUE THREAD

**Issue by Shrivaibavi** [gluster/glusterd2#1139]
Note: This issue is seen in single node external etcd server with 3 clients.

Description:
When i restarted the glusterd2 service and checked the status it was active and the external etcd node was actively running. I was able to see the peer list for first time and suddenly i could see an error "Error getting peer list" message. I tried for fetching volume list, again got an error " Error getting volume list". This happened on all the 3 clients.

Console output/steps:
[root@dhcp35-47 ~]# systemctl restart glusterd2

[root@dhcp35-47 ~]# systemctl status glusterd2
● glusterd2.service - GlusterD2, the management service for GlusterFS (pre-release)
   Loaded: loaded (/usr/lib/systemd/system/glusterd2.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-08-07 14:18:02 IST; 11s ago
 Main PID: 6096 (glusterd2)
   CGroup: /system.slice/glusterd2.service
           └─6096 /usr/sbin/glusterd2 --config=/etc/glusterd2/glusterd2.toml

Aug 07 14:18:02 dhcp35-47.lab.eng.blr.redhat.com systemd[1]: Started GlusterD2, the management serv...).
Aug 07 14:18:02 dhcp35-47.lab.eng.blr.redhat.com systemd[1]: Starting GlusterD2, the management ser.....
Hint: Some lines were ellipsized, use -l to show in full.

[root@dhcp35-47 ~]# glustercli peer list
+--------------------------------------+----------------------------------+-------------------+--------------------+--------+-------+
|                  ID                  |               NAME               | CLIENT ADDRESSES  |   PEER ADDRESSES   | ONLINE |  PID  |
+--------------------------------------+----------------------------------+-------------------+--------------------+--------+-------+
| 624c0de6-6c3d-4ef3-aef7-761ae78d57cc | dhcp35-47.lab.eng.blr.redhat.com | 127.0.0.1:24007   | 10.70.35.47:24008  | yes    |  6096 |
|                                      |                                  | 10.70.35.47:24007 | 10.70.35.179:24008 |        |       |
| d2dd17b9-2f8c-4b3a-be38-ad56cb0b87c5 | dhcp35-5.lab.eng.blr.redhat.com  | 127.0.0.1:24007   | 10.70.35.5:24008   | yes    | 18388 |
|                                      |                                  | 10.70.35.5:24007  |                    |        |       |
+--------------------------------------+----------------------------------+-------------------+--------------------+--------+-------+

[root@dhcp35-47 ~]# glustercli volume list
Error getting Volumes list

Response headers:
X-Gluster-Cluster-Id: 7e57dac0-3807-43d8-a4d3-6f142d8863ac
X-Gluster-Peer-Id: 624c0de6-6c3d-4ef3-aef7-761ae78d57cc
X-Request-Id: b9632ea5-6b89-4c5d-973a-3dffd8c0a67c

Response body:
context deadline exceeded

[root@dhcp35-47 ~]# glustercli peer list
Failed to get Peers list

Response headers:
X-Request-Id: fcd46d73-0554-4dd3-a109-12ca5ab7f587
X-Gluster-Cluster-Id: 7e57dac0-3807-43d8-a4d3-6f142d8863ac
X-Gluster-Peer-Id: 624c0de6-6c3d-4ef3-aef7-761ae78d57cc

Response body:
context deadline exceeded

[root@dhcp35-47 ~]# systemctl status glusterd2
● glusterd2.service - GlusterD2, the management service for GlusterFS (pre-release)
   Loaded: loaded (/usr/lib/systemd/system/glusterd2.service; disabled; vendor preset: disabled)
   Active: active (running) since Tue 2018-08-07 14:18:02 IST; 3min 59s ago
 Main PID: 6096 (glusterd2)
   CGroup: /system.slice/glusterd2.service
           └─6096 /usr/sbin/glusterd2 --config=/etc/glusterd2/glusterd2.toml

Aug 07 14:18:33 dhcp35-47.lab.eng.blr.redhat.com glusterd2[6096]: grpc: addrConn.resetTransport fail...}
Aug 07 14:18:35 dhcp35-47.lab.eng.blr.redhat.com glusterd2[6096]: grpc: addrConn.resetTransport fail...}
Aug 07 14:18:38 dhcp35-47.lab.eng.blr.redhat.com glusterd2[6096]: grpc: addrConn.resetTransport fail...}
Aug 07 14:18:41 dhcp35-47.lab.eng.blr.redhat.com glusterd2[6096]: grpc: addrConn.resetTransport fail...}
Aug 07 14:18:49 dhcp35-47.lab.eng.blr.redhat.com glusterd2[6096]: grpc: addrConn.resetTransport fail...}
Aug 07 14:18:58 dhcp35-47.lab.eng.blr.redhat.com glusterd2[6096]: grpc: addrConn.resetTransport fail...}
Aug 07 14:19:16 dhcp35-47.lab.eng.blr.redhat.com glusterd2[6096]: grpc: addrConn.resetTransport fail...}
Aug 07 14:19:47 dhcp35-47.lab.eng.blr.redhat.com glusterd2[6096]: grpc: addrConn.resetTransport fail...}
Aug 07 14:20:28 dhcp35-47.lab.eng.blr.redhat.com glusterd2[6096]: grpc: addrConn.resetTransport fail...}
Aug 07 14:21:36 dhcp35-47.lab.eng.blr.redhat.com glusterd2[6096]: grpc: addrConn.resetTransport fail...}
Hint: Some lines were ellipsized, use -l to show in full.
[root@dhcp35-47 ~]# glustercli peer list
Failed to get Peers list

Response headers:
X-Gluster-Peer-Id: 624c0de6-6c3d-4ef3-aef7-761ae78d57cc
X-Request-Id: 614e08ce-ff42-4cf3-afb7-414db476d9b5
X-Gluster-Cluster-Id: 7e57dac0-3807-43d8-a4d3-6f142d8863ac

Response body:
context deadline exceeded

Console output from etcd server:
The etcd server was running in the background.
[root@dhcp35-173 ~]# pgrep etcd
2140

Configuration on all the 3 clients are same:
localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
restauth = false
etcdendpoints = "http://10.70.35.173:2379"
noembed = true

Logs from all the 3 machines:
[glusterd2.log](https://github.com/gluster/glusterd2/files/2265756/glusterd2.log)
[glusterd2.log](https://github.com/gluster/glusterd2/files/2265757/glusterd2.log)
[glusterd2.log](https://github.com/gluster/glusterd2/files/2265758/glusterd2.log)

**Comment by Shrivaibavi** [comment]
Note : Even after a reboot on all the 3 nodes and restarting the glusterd2 services on all the nodes i am still facing this issue.

**Comment by kshlm** [comment]
From the logs, I see that the first `peer list` returns successfully, but the subsequent requests fail. 
Looks like the etcd server is becoming unresponsive after the first request. Need to figure out why.

**Comment by sankarshanmukhopadhyay** [comment]
Is there not a --debug equivalent to run on etcd to ascertain what specifically transpires when the sequence of commands are executed to arrive at output of `peer list`

**Comment by Madhu-1** [comment]
>Response body:
context deadline exceeded

gd2 is not able to connect to ETCD

@Shrivaibavi can you try to restart `ETCD`.

**Comment by Shrivaibavi** [comment]
It is an etcd configuration issue, That is solved now.
