### ISSUE TITLE
Failed to get volume status if one of the node glusterd2 is stopped

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1140]
-> Having 3 node glusterd2 cluster(n1, n2, n3) with external etcd running.
-> Create some volumes.
-> Then stop the glusterd2  on one of the node(n2) from 3 node cluster.
-> Then check for volume status, volume status is failing with below error.

glustercli volume status
Volume : Disp3
Error getting Volume status

Response headers:
X-Gluster-Cluster-Id: e56e67b7-51a3-4b22-8d5b-73679baafe91
X-Gluster-Peer-Id: 91b6edad-6246-4b77-9a0d-6bf92a6a1514
X-Request-Id: 47614cb2-5750-41d9-97c4-1b11c1a0aabe

Response body:
Transaction step bricks-status.Check failed on peer 5d9f6dbc-3231-4e78-93ba-148ed8fd6249 with error: rpc error: code = 14 desc = grpc: the connection is unavailable

Logs:

time="2018-08-07 15:36:49.271988" level=info msg="127.0.0.1 - - [07/Aug/2018:15:36:49 +0530] \"GET /v1/volumes HTTP/1.1\" 200 10699" reqid=743a5d1d-1ea5-4d24-ad4d-af7d1ca24930
time="2018-08-07 15:36:49.279308" level=error msg="failed RPC call" error="rpc error: code = 14 desc = grpc: the connection is unavailable" remotepeer="5d9f6dbc-3231-4e78-93ba-148ed8fd6249(dhcp35-33.lab.eng.blr.redhat.com)" reqid=f508d34b-5cdd-4e17-894a-8c02730c2e9a rpc=TxnSvc.RunStep source="[rpc-client.go:73:transaction.runStepOn]" txnid=d935ec41-512f-4cb2-8790-91dc84514e82
time="2018-08-07 15:36:49.279397" level=error msg="Step failed on node." error="rpc error: code = 14 desc = grpc: the connection is unavailable" node=5d9f6dbc-3231-4e78-93ba-148ed8fd6249 reqid=f508d34b-5cdd-4e17-894a-8c02730c2e9a source="[step.go:119:transaction.runStepFuncOnNodes]" step=bricks-status.Check txnid=d935ec41-512f-4cb2-8790-91dc84514e82
time="2018-08-07 15:36:49.285942" level=error msg="Failed to get volume status" error="Step bricks-status.Check failed on 1 nodes" reqid=f508d34b-5cdd-4e17-894a-8c02730c2e9a source="[bricks-status.go:76:volumes.volumeBricksStatusHandler]" volume=Disp3
time="2018-08-07 15:36:49.286895" level=info msg="127.0.0.1 - - [07/Aug/2018:15:36:49 +0530] \"GET /v1/volumes/Disp3/bricks HTTP/1.1\" 500 217" reqid=f508d34b-5cdd-4e17-894a-8c02730c2e9a

**Comment by Madhu-1** [comment]
@rmadaka volume status calls `/v1/volumes/%s/bricks` (BrickStatus) URL which is nothing but, we are getting the bricks status from the nodes where the brick belongs to
if a node is down then we are not able to fetch brick status from it. hence we are returning an error

what is your expectation for this CLI if brick hosting node is down?

**Comment by Madhu-1** [comment]
>Then stop the glusterd2 on one of the node(n2) from 3 node cluster

did you manually stopped glusterd2 on `n2`?

**Comment by aravindavk** [comment]
> what is your expectation for this CLI if brick hosting node is down?

API should return status of available nodes. rest of the status can be marked as "Unknown"

**Comment by rmadaka** [comment]
@Madhu-1: If one of the glusterd2 node is down which is hosting a brick, if we perform gluster volume status from other node, It should show the status for available node bricks.
