### ISSUE TITLE
Log file format

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#1141]
Glusterd2 log format is different from all other Gluster components(glusterfsd,glusterfs, geo-rep etc) log format.

Common format for all Gluster logs will help to write tools for analyzing Gluster logs.

    <TIMESTAMP> <LOG_LEVEL> [MSGID:<MSGID>] [<FILENAME>:<LINENO>:<FUNCNAME>] <DOMAIN> <MSG>

Example brick log:

    [2018-08-03 11:32:04.466022] W [MSGID: 113117] [posix-metadata.c:569:posix_update_utime_in_mdata] 0-gv1-posix: posix utime set mdata failed on file

**Comment by amarts** [comment]
I would recommend keeping the logs to be debug-able by machine, ie JSON etc. Goal is to have a elk stack for analysing logs in future. Let's not get new tools to older format, instead try to stick to more global standards, so we can re-use tools from different projects.

**Comment by prashanthpai** [comment]
I agree with @amarts :+1: 

We can live with glusterd2 logs being different from those from other glusterfs components.

**Comment by aravindavk** [comment]
> I would recommend keeping the logs to be debug-able by machine, ie JSON etc. Goal is to have a elk stack for analysing logs in future. Let's not get new tools to older format, instead try to stick to more global standards, so we can re-use tools from different projects.

Current log library used in glusterd2 already supports json and other formats already. But the default log format used now is different from other gluster components. 

Having common format makes it easy to parse the logs, without common format tools will have to understand every format used. Existing log parsers will not work for glusterd2 logs unless it is modified.(Ex: http://aravindavk.in/blog/gluster-log-tools-and-structured-logging/)

I will close this issue if we don't need log uniformity across gluster components.

**Comment by aravindavk** [comment]
> We can live with glusterd2 logs being different from those from other glusterfs components.

Are we loosing anything if we support same format or is there any technical limitation with logrus? 

If json is not configured with logrus, we are using text format to dump the logs. If possible we can change the format in the default text format?

**Comment by aravindavk** [comment]
Even logstash(elk stack) understands gluster's log format(https://gist.github.com/semiosis/1499710)

**Comment by prashanthpai** [comment]
> Are we loosing anything if we support same format or is there any technical limitation with logrus?

The `field=<value>` format of logrus is very useful and more expressive than glusterfs logging format which has fixed and ordered fields. I don't prefer to introduce msg ID either.

> If json is not configured with logrus, we are using text format to dump the logs. If possible we can change the format in the default text format?

+1. Yes we need that :+1:
