### ISSUE TITLE
Peer remove with force throws error but when we check peer status, peer is removed

### ISSUE THREAD

**Issue by Akarsha-rai** [gluster/glusterd2#1157]
Steps:
1) Having 3 node cluster say n1, n2 and n3 and single external etcd.
2) Tried to remove n3 from node n1 with force got the error
curl -X DELETE http://10.70.35.34:24007/v1/peers/da478ca0-2b84-4b99-a6bc-9edd3b5950ce force
curl: (6) Could not resolve host: force; Unknown error
3) Checked the peer status from node n1, node n3 was removed even though it threw an error
[root@dhcp35-229 ~]# glustercli peer status
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-------+
|                  ID                  |               NAME                |  CLIENT ADDRESSES  |   PEER ADDRESSES   | ONLINE |  PID  |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-------+
| aab46496-065c-4dc3-8010-11435a7428a4 | dhcp35-229.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.35.229:24008 | yes    | 20241 |
|                                      |                                   | 10.70.35.229:24007 |                    |        |       |
|                                      |                                   | 10.70.35.34:24007  |                    |        |       |
| b7964d08-d68d-4c35-b598-abbd6c2407d0 | dhcp35-163.lab.eng.blr.redhat.com | 127.0.0.1:24007    | 10.70.35.163:24008 | yes    | 20025 |
|                                      |                                   | 10.70.35.163:24007 |                    |        |       |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-------+
27.0.0.1:24007    | 10.70.35.163:24008 | yes    | 20025 |
|                                      |                                   | 10.70.35.163:24007 |                    |        |       |
+--------------------------------------+-----------------------------------+--------------------+--------------------+--------+-------+

If the command is wrong, peer shouldn't be removed from the cluster and should throw an appropriate error
Logs:
Node1:
time="2018-08-10 12:18:34.021810" level=info msg="peer disconnected from store" id=da478ca0-2b84-4b99-a6bc-9edd3b5950ce source="[liveness.go:51:events.(*livenessWatcher).Watch]"
time="2018-08-10 12:18:39.034589" level=info msg="10.70.35.34 - - [10/Aug/2018:12:18:34 +0530] \"DELETE /v1/peers/da478ca0-2b84-4b99-a6bc-9edd3b5950ce HTTP/1.1\" 204 0" reqid=c4b09767-a5ab-4a61-abeb-9b5e21cadee6
time="2018-08-10 12:19:20.985605" level=info msg="127.0.0.1 - - [10/Aug/2018:12:19:20 +0530] \"GET /v1/peers HTTP/1.1\" 200 572" reqid=52a22000-4933-464e-9657-f16dbea91aa0
time="2018-08-10 12:19:43.123058" level=info msg="127.0.0.1 - - [10/Aug/2018:12:19:43 +0530] \"GET /v1/peers HTTP/1.1\" 200 572" reqid=e8def88c-9063-40b6-9b75-844ad70d781d
Node3:
time="2018-08-10 12:18:34.019867" level=info msg="handling incoming leave cluster request" remotepeer=aab46496-065c-4dc3-8010-11435a7428a4 source="[peer-rpc-svc.go:105:peers.(*PeerService).Leave]"
time="2018-08-10 12:18:34.023784" level=warning msg="failed to close etcd session" error="grpc: the client connection is closing" source="[remote.go:66:store.(*GDStore).closeRemoteStore]"
time="2018-08-10 12:18:39.024653" level=error msg="failed to create etcd client" error="dial tcp [::1]:2379: getsockopt: connection refused" source="[remote.go:49:store.newRemoteStore]"
time="2018-08-10 12:18:39.024774" level=error msg="failed to restart store with new endpoints" endpoints="[http://localhost:2379]" error="dial tcp [::1]:2379: getsockopt: connection refused" source="[peer-rpc-svc.go:183:peers.ReconfigureStore]"
time="2018-08-10 12:18:39.032155" level=warning msg="failed to reconfigure store with defaults" error="dial tcp [::1]:2379: getsockopt: connection refused" remotepeer=aab46496-065c-4dc3-8010-11435a7428a4 source="[peer-rpc-svc.go:146:peers.(*PeerService).Leave]"

**Comment by Madhu-1** [comment]
>curl -X DELETE http://10.70.35.34:24007/v1/peers/da478ca0-2b84-4b99-a6bc-9edd3b5950ce force
curl: (6) Could not resolve host: force; Unknown error

we don't support force for peer remove. the error what you posted is from CURL not from glusterd2

from curl request peer remove was successful.
