### ISSUE TITLE
GD2 should provide overall cluster status (healthy/unhealthy)

### ISSUE THREAD

**Issue by shtripat** [gluster/glusterd2#1159]
Based on peers connected state in the peers list and status of the volumes whether they are partially available or degraded, the status of the cluster overall should be reported as healthy or un-healthy.
This is meaningful and required for north bound consumers like web admin to report the same to end user.

**Comment by sankarshanmukhopadhyay** [comment]
Is there a list of metrics/parameters which can be utilized to conclude if a cluster is healthy or, unhealthy?

**Comment by shtripat** [comment]
In WA earlier, the cluster status was calculated based on volume brick's status and the peers connected status.
If few volumes are partially available or degraded, the cluster used to be marked as unhealthy. Similarly if not all the peers in connected state, the cluster used to be unhealthy.

This logic actually was borrowed from old gstatus project and detailed logic could be referred from https://github.com/Tendrl/gluster-integration/blob/master/tendrl/gluster_integration/sds_sync/cluster_status.py

Hope this helps.

**Comment by sankarshanmukhopadhyay** [comment]
Borrowing heavily from gstatus's approach to cluster health may not translate fully over to the containerized model of deployment. It is in this context that I asked about a list and the likelihood of a revisit of the parameters.

We also need to be mindful that in a container using OpenShift etc, gd2 is the "layer of separation" between the orchestrator and the storage-orchestrator (gd2). So, being able to factor in quick response times for the data set that indicates health is important.

**Comment by sankarshanmukhopadhyay** [comment]
Also adding a reference to https://github.com/heketi/heketi/issues/1320

**Comment by aravindavk** [comment]
All applications will be interested in Volume level metrics that means Volume is healthy or not. Is there any usecase for combining healthy status of two or more volumes?

Issue already available for Volume health https://github.com/gluster/glusterd2/issues/1160

**Comment by aravindavk** [comment]
needinfo: @shtripat 

Can this be closed?

**Comment by aravindavk** [comment]
closing this based on the previous discussions. Please re-open if anything needs to be fixed from gd2
