### ISSUE TITLE
[RFE] Template support for Volfiles

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#1190]
Default Graphs via template file, This will be applied build
time. Alternatively we can load this when glusterd2 starts, but may
face issues if each node contains different versions of template.

Along with the list of xlators and order of xlators to load, templates
can mention default options and default state of xlator.

Example brick template(`toml` format):

```
[[xlator]]
name = "protocol/server"

[[xlator]]
name = "debug/io-stats"

[[xlator]]
name = "features/index"

[[xlator]]
name = "features/selinux"

[[xlator]]
name = "performance/io-threads"

[[xlator]]
name = "features/upcall"

[[xlator]]
name = "features/locks"

[[xlator]]
name = "features/access-control"

[[xlator]]
name = "features/changelog"
enabled = false
enable_by_option = true

[xlator.options]
capture-del-path = "on"

[[xlator]]
name = "storage/posix"
```

Example client template(`toml` format):

```
[[clustergraph.xlator]]
name = "protocol/client"

[clustergraph.xlator.options]
ping-timeout = 42

[[xlator]]
name = "debug/io-stats"

[xlator.options]
client-log-level = "INFO"

[[xlator]]
name = "distribute"
```

By default xlators included in template are enabled. Add `enabled =
false` if a xlator needs to be disabled by default. If a xlator
enabled/disabled is dicided based on option inside that xlator then
add `enabled_by_option=true` (Example above is `changelog` xlator,
disabled by default)

### New APIs

New templates can be registerd using the following APIs

```
Add new Template:    POST /volfiles-template/:template-name
Delete new Template: DEL /volfiles-template/:template-name
```

Once the templates are registerd, default template for new volumes can
be customized using,

```
POST /cluster/config -d '{"volfiles-template": "my-new-tmpl"}'
```

Note: Already created volumes will continue to use the previously
registerd template or default template.

Template of an existing volume can be changed using, (Note: This may
require Volume restart)

```
POST /volumes/:name/edit -d '{"volfiles-template": "my-new-tmpl"}'
```

### Enabled state and Options
Enabled state and options will be applied in the following order.

- Options and Enabled state from options table of xlators(default
  value)
- Options and Enabled state from volfile template
- Options and Enabled state from Volinfo(Set using Volume set)

### Effect on Volume Options Set/Get

- xlators can only be enabled/disabled only if it is listed in its
  template.Volume set will fail if that option does not belong to the
  xlators list.
- Volume options get/help will only show the options which are related
  to listed xlators.
- Xlator can be enabled or disabled using key as `xlator-name` and
  value as `on|off`.
- Xlator enable/disable volume set should not fail if xlator's option
  table does not define option with xlator name itself.

### Effect on generated Volfiles

- Volfiles will only contains the xlators which are Enabled.
- If `enable_by_option` is set then generated volfile will contain the
  xlator graph even though it is disabled. Disabled state will be
  mentioned as one of the option in xlator graph as `option
  <xlator-name> on/off`
- If `enabled_by_option` is not set then generated volfile will not
  contain xlator graph if it is disabled.

### Effect on the running Volumes

- If a xlator is enabled without setting `enabled_by_option`, then
  brick/daemon restart is required if graph changes.(Clients can
  reconfigure on new graph, but brick processes and other daemons
  can't re-configure on graph change.)
  
## Changes to option table and xlators

- If a xlator requires support for `enable_by_option`, then option
  table should contain a key with name same as xlator name and default
  value `on` or `off`. Respective code should understand this key when
  xlator is disabled/enabled.

## MVP 0

- Default template support
- Consider Enabled state and Options from template and apply during
  Volfile generation
- Consider `enabled_by_option` to include xlator in volfile

## MVP.Next

- New APIs for customizing the templates and assign template to Volume
- Volume set support to enable/disable xlators and Validation if a
  xlator does not exists in the template.
- Changes to xlators option table to accomodate enable option(If
  `enable_by_option` is required)
- Volume options GET filter - include in response only in template

**Comment by aravindavk** [comment]
@amarts @kshlm @atinmu @prashanthpai @ShyamsundarR @vbellur Please add if I missed anything here or if any changes required.

**Comment by amarts** [comment]
Looks good to me! This is a good start, and more questions, and possibilities may arise later :-)

**Comment by Madhu-1** [comment]
@aravindavk it will be helpful if we support GET and LIST api's for templates
* GET the content of template file (helps for debugging)
* Listing the template names ( if we have multiple templates, a user can get the list of templates available in glusterd2 and associate appropriate template name with volume.)

**Comment by aravindavk** [comment]
moving this to `GCS/0.3` since review is taking some more time.

**Comment by atinmu** [comment]
Closed through https://github.com/gluster/glusterd2/pull/1229
