### ISSUE TITLE
Frequent disconnects being logged on one node.

### ISSUE THREAD

**Issue by rohantmp** [gluster/glusterd2#1210]
Same log problems as seen in this [issue](https://github.com/gluster/glusterd2/issues/940)

### Observed behavior
One node is frequently logging connects and disconnects despite attempts to reset gd2 to a clean state:
```
time="2018-09-03 10:11:38.737138" level=info msg="client connected" address="10.70.42.23:49141" server=sunrpc source="[server.go:158:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-09-03 10:11:38.740325" level=info msg="client disconnected" address="10.70.42.23:49141" server=sunrpc source="[server.go:114:sunrpc.(*SunRPC).pruneConn]"
time="2018-09-03 10:11:39.237597" level=info msg="client connected" address="10.70.42.135:49133" server=sunrpc source="[server.go:158:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-09-03 10:11:39.239787" level=info msg="client disconnected" address="10.70.42.135:49133" server=sunrpc source="[server.go:114:sunrpc.(*SunRPC).pruneConn]"
time="2018-09-03 10:11:39.571069" level=info msg="client connected" address="10.70.42.23:49130" server=sunrpc source="[server.go:158:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-09-03 10:11:39.572727" level=info msg="client disconnected" address="10.70.42.23:49130" server=sunrpc source="[server.go:114:sunrpc.(*SunRPC).pruneConn]"
time="2018-09-03 10:11:40.130230" level=info msg="client connected" address="10.70.42.135:49120" server=sunrpc source="[server.go:158:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-09-03 10:11:40.131944" level=info msg="client disconnected" address="10.70.42.135:49120" server=sunrpc source="[server.go:114:sunrpc.(*SunRPC).pruneConn]"

```
I tried to cleanup glusterd2 state via the following steps:
- Stop glusterd2 on all nodes.
- Stop etcd server.
- Remove /var/lib/etcd on the etcd server (verified that it existed first)
- Remove the localstatedir (/usr/local/var/lib/glusterd2) on all glusterd2 nodes.
- Start etcd.
- Start glusterd2 on all nodes.

### Details on how to reproduce 
Unknown. I don't know what about this specific node is causing this issue.

### Information about the environment:

- Glusterd2 version used : master  from a while ago.
- Operating system used: centos
- Glusterd2 compiled from source
- Using External ETCD: yes, 3.2.22
- Direct install of etcd using yum

### Other useful information
- Problem node is node 2 of 3

- statedump of nodes:[ node 1](http://pastebin.test.redhat.com/640314), [node 2](http://pastebin.test.redhat.com/640315), [node 3](http://pastebin.test.redhat.com/640316)

- glusterd2 config files from all nodes:
```
localstatedir = "/usr/local/var/lib/glusterd2"
loglevel = "INFO"
logdir="/root/test/"
logfile = "glusterd2.log"
rundir = "/usr/local/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
#restauth should be set to false to disable REST authentication in glusterd2
restauth = false
noembed = true
etcdendpoints = "http://10.70.43.184:2379"
```
- ETCD configuration:
```
data-dir: "/var/lib/etcd"
listen-peer-urls: http://10.70.43.184:2380
listen-client-urls: http://10.70.43.184:2379
name: "glusterd2"
initial-advertise-peer-urls: http://10.70.43.184:2380
advertise-client-urls: http://10.70.43.184:2379
```
- [Glusterd2 logs](http://pastebin.test.redhat.com/640317) from node 1.

- `glusterd2 --version`
```
glusterd version: v4.1.0-134.git660b029
git SHA: 660b029
go version: go1.10.3
go OS/arch: linux/amd64

```

**Comment by rohantmp** [comment]
@prashanthpai 
>  Can you check that on all the nodes ?
Same on all nodes. Only matched process is glusterd2.

**Comment by prashanthpai** [comment]
@rohantmp sent a pcap capture (attached) and seems like stale clients (mount process) on different machines (outside the 3 node cluster) were accessing glusterd2 instance in this cluster.


[output_a2.zip](https://github.com/gluster/glusterd2/files/2344333/output_a2.zip)

**Comment by rohantmp** [comment]
@prashanthpai yes, thanks for solving the mystery!
