### ISSUE TITLE
Unable to create and list snapshot via glustercli , but able to do it with curl commands

### ISSUE THREAD

**Issue by Shrivaibavi** [gluster/glusterd2#1242]
### Observed behavior

```
[root@dhcp35-30 ~]# glustercli snapshot create snap_test300 test02
Snapshot creation failed

Response headers:
X-Gluster-Cluster-Id: 3a526594-5b01-410f-a445-0a6adc2a901e
X-Gluster-Peer-Id: 7ebfbea6-59e6-494a-b157-cdf35603e624
X-Request-Id: f13efd69-fb83-4806-830e-4f60986d22f0

Response body:
unexpected end of JSON input
```
Successful with curl comand
```
curl -X POST http://10.70.35.30:24007/v1/snapshot --data @snap.json -H 'Container-Type: application/json'
{"snapinfo":{"id":"4855302d-1574-4d8a-bd27-53f08a7b69a3","name":"snap_test02_GMT_2018_09_17_06_16_53","type":"Distribute","transport":"tcp","distribute-count":1,"replica-count":1,"options":{"bitrot-stub.bitrot":"off","feature.deem-statfs":"off","features.barrier":"disable","features.inode-quota":"off","features.quota":"off","features.quota-deem-statfs":"off","features.read-only":"on","features.uss":"off","replicate.self-heal-daemon":"off"},"state":"Created","subvols":[{"name":"snap_test02_GMT_2018_09_17_06_16_53-distribute-0","type":"Distribute","bricks":[{"id":"f66d3997-31d7-45fc-9190-9adc9e27857e","path":"/var/run/glusterd2/snaps/snap_test02_GMT_2018_09_17_06_16_53/test02/subvol1/brick1/brick","volume-id":"4855302d-1574-4d8a-bd27-53f08a7b69a3","volume-name":"snap_test02_GMT_2018_09_17_06_16_53","peer-id":"7ebfbea6-59e6-494a-b157-cdf35603e624","host":"10.70.35.30","type":"Brick"}],"replica-count":1,"arbiter-count":0,"disperse-count":0}],"metadata":{},"snap-list":[]},"parentname":"test02","description":""}
```
```
[root@dhcp35-30 ~]# glustercli snapshot list
Error getting Snapshot list
json: cannot unmarshal string into Go struct field SnapList.snaps of type api.SnapInfo
```
Successful with curl command
```
[root@dhcp35-30 ~]# curl -X GET http://10.70.35.30:24007/v1/snapshots
[{"parentname":"test01","snaps":["snap_test","snap_test_GMT_2018_09_14_10_17_13"]},{"parentname":"test02","snaps":["snap_test02_GMT_2018_09_17_06_02_04","snap_test02_GMT_2018_09_17_06_16_53"]}]
```
### Expected/desired behavior

Create and list snapshot should be successful via glustercli

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): 
[root@dhcp35-30 ~]# glusterd2 --version
glusterd version: v4.1.0-196.git305072d
git SHA: 305072d
go version: go1.9.4
go OS/arch: linux/amd64

- Operating system used: CentOS Linux release 7.5.1804 (Core)
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: 
- Using External ETCD: (yes/no, if yes ETCD version): yes
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

[glusterd2_17-9.log](https://github.com/gluster/glusterd2/files/2387566/glusterd2_17-9.log)
[var-run-glusterd2-bricks-test02-subvol1-brick1-brick.log](https://github.com/gluster/glusterd2/files/2387567/var-run-glusterd2-bricks-test02-subvol1-brick1-brick.log)

[root@dhcp35-30 glusterd2]# cat glusterd2.toml 

localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
restauth = false
etcdendpoints = "http://10.70.35.173:2379"
noembed = true

- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by Shrivaibavi** [comment]
@rafikc30 ^^

**Comment by Madhu-1** [comment]
@ShrivaibaviI have tested snapshot list with the master branch
```
./glustercli snapshot list
+-------+---------------+
| NAME  | ORIGIN VOLUME |
+-------+---------------+
| test1 | test          |
+-------+---------------+
```
please check both gluster-cli and glusterd2 binaries are updated.

**Comment by Madhu-1** [comment]
>curl -X POST http://10.70.35.30:24007/v1/snapshot --data @snap.json -H 'Container-Type: application/json'
{"snapinfo":{"id":"4855302d-1574-4d8a-bd27-53f08a7b69a3","name":"snap_test02_GMT_2018_09_17_06_16_53

even this API is not supported now, please check after upgrading glusterd2 services is reloaded

**Comment by Madhu-1** [comment]
@Shrivaibavi if this is not an issue please verify and close this one

**Comment by Shrivaibavi** [comment]
@Madhu-1 Thanks, it was an update issue. Its working now.
