### ISSUE TITLE
glusterd2.socket makes the service dead after updating rpms.

### ISSUE THREAD

**Issue by ksandha** [gluster/glusterd2#1246]
### Observed behavior
The glusterd2 service becomes dead after restarting the service of updated rpms.

### Expected/desired behavior
The service shouldn't be dead

### Details on how to reproduce (minimal and precise)
Update the glusterd2 rpms and restart the service 

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): 
[root@dhcp35-88 ~]# rpm -qa | grep gluster
glusterfs-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-cli-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-libs-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-client-xlators-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-fuse-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-server-6dev-0.3.git76cb1e7.el7.x86_64
glusterfs-api-6dev-0.3.git76cb1e7.el7.x86_64
glusterd2-4.1.0-202.gitea0c111.el7.x86_64

- Operating system used: 
[root@dhcp35-88 ~]# cat /etc/centos-release
CentOS Linux release 7.5.1804 (Core) 

- Glusterd2 compiled from sources, as a package (rpm/deb), or container: 
rpm
- Using External ETCD: (yes/no, if yes ETCD version):
[root@dhcp35-220 etcd-v3.3.8-linux-amd64]# ./etcd --version
etcd Version: 3.3.8
Git SHA: 33245c6b5
Go Version: go1.9.7
Go OS/Arch: linux/amd64

- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
direct
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
```
server1
[root@dhcp35-88 ~]# cat /etc/glusterd2/glusterd2.toml

localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
#defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
#restauth should be set to false to disable REST authentication in glusterd2
restauth = false
etcdendpoints = "http://10.70.35.220:2379"
noembed = true

server2
[root@dhcp35-181 ~]# cat /etc/glusterd2/glusterd2.toml

localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
#restauth should be set to false to disable REST authentication in glusterd2
restauth = false
etcdendpoints = "http://10.70.35.220:2379"

server3
[root@dhcp35-26 ~]# cat /etc/glusterd2/glusterd2.toml

localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
#restauth should be set to false to disable REST authentication in glusterd2
#restauth = false

```
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)

- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
```
[root@dhcp35-88 ~]# cat /var/lib/glusterd2/uuid.toml
cluster-id = "a193619e-ce9d-4c19-8e0b-5a82ab8655ff"
peer-id = "ddf8af56-04cf-4e49-a4c7-99d90904bcb7"
[root@dhcp35-88 ~]# 

[root@dhcp35-181 ~]# cat /var/lib/glusterd2/uuid.toml
cluster-id = "a193619e-ce9d-4c19-8e0b-5a82ab8655ff"
peer-id = "de9fab15-40ac-46c7-90f0-6a1659b0fb4b"


[root@dhcp35-26 ~]# cat /var/lib/glusterd2/uuid.toml
cluster-id = "a193619e-ce9d-4c19-8e0b-5a82ab8655ff"
peer-id = "bc8dcfaf-e848-427b-839b-2d4c7a0a9034"
```
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
[root@dhcp35-88 ~]# glusterd2 --version
glusterd version: v4.1.0-202.gitea0c111
git SHA: ea0c111
go version: go1.9.4
go OS/arch: linux/amd64

    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by ksandha** [comment]
[server3.log](https://github.com/gluster/glusterd2/files/2391735/server3.log)
[server2.log](https://github.com/gluster/glusterd2/files/2391741/server2.log)
[server1.log](https://github.com/gluster/glusterd2/files/2391743/server1.log)

**Comment by ksandha** [comment]
Don't  think this a race condition , as I am able to hit it 4/4 times. on my setup.

**Comment by prashanthpai** [comment]
> Don't think this a race condition , as I am able to hit it 4/4 times. on my setup.

It is clearly not. It has been a known issue.

**Comment by aravindavk** [comment]
Lock file can be used to address this issue

https://gavv.github.io/blog/unix-socket-reuse/

**Comment by atinmu** [comment]
We can not live with this bug for too long.  In GD1, I believe this is handled through https://github.com/gluster/glusterfs/blob/master/glusterfs.spec.in#L990 ?

**Comment by aravindavk** [comment]
> We can not live with this bug for too long. In GD1, I believe this is handled through https://github.com/gluster/glusterfs/blob/master/glusterfs.spec.in#L990 ?

As mentioned by @prashanthpai (https://github.com/gluster/glusterd2/issues/1246#issuecomment-422302670), removing socket file before starting glusterd2 will introduce race. We should implement Lock as mentioned in https://github.com/gluster/glusterd2/issues/1246#issuecomment-424624991

**Comment by atinmu** [comment]
> As mentioned by @prashanthpai (#1246 (comment)), removing socket file before starting glusterd2 will introduce race. We should implement Lock as mentioned in #1246 (comment)
@prashanthpai For my knowledge, could you explain why would it introduce race?
