### ISSUE TITLE
PVC status is in bound state after volume deleted from gd2 container

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1249]
After volume deleted from gd2 cotainer  LV's deleted from kube nodes which means devices(/dev/vdc) space freed up from all nodes. But PVC status still in Bound state.

### Observed behavior
root@glusterd2-cluster-2qcgw /]# glustercli volume stop pvc-3c4c3626bd9a11e8
Volume pvc-3c4c3626bd9a11e8 stopped successfully

[root@glusterd2-cluster-2qcgw /]# glustercli volume delete pvc-3c4c3626bd9a11e8
Are you sure you want to delete volume pvc-3c4c3626bd9a11e8 [yes/no]? yes
Volume pvc-3c4c3626bd9a11e8 deleted successfully

NAME                STATUS    VOLUME                 CAPACITY   ACCESS MODES   STORAGECLASS    AGE
glusterfs-csi-pv1   Bound     pvc-3c4c3626bd9a11e8   2Gi        RWX            glusterfs-csi   42m

### Expected/desired behavior

 If PVC is in BOUND state, i think LV's should be available.

### Details on how to reproduce (minimal and precise)
-> Create PVC
-> Stop and delete the volume from GD2 container
-> LV's also deleted from kube nodes.
-> But PVC is in BOUND state

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): glusterd version: v4.1.0-184.gita69e8f4

- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container:  Container
- Using External ETCD: (yes/no, if yes ETCD version): yes
- If container, which container image: quay.io/kshlm/glusterd2-nightly:envfixes
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by JohnStrunk** [comment]
I think this is a misunderstanding of proper usage.

I am a bit unclear on how the volume was created intitially and the behavior you expected, so I'll try to cover the two cases I can think of...

### If you were using the prototype CSI driver...
If you were using the CSI driver, it would have created the gluster volume as a part of the automatic provisioning. Likewise, when you delete the PVC, the underlying PV would be deleted, triggering the volume deletion through the CSI driver.

### if you manually provisioned the volume & created the PV by hand...
When doing manual provisioning, it is the responsibility to the admin to ensure the PVC/PV are deleted prior to freeing the backing storage.

When you use glustercli and tell it to delete the volume, it will oblige. Likewise, Kube has no way to know that the storage has been deleted out from under it.

Does that help?

**Comment by rmadaka** [comment]
@JohnStrunk
yes,  I am using CSI driver to create volume, as part of automatic provisioning gluster volume has created. If i delete the PVC from kubernetes  master using "kubectl delete pvc/<pvc- name>" command , underlying pv will get delete as well as gluster volume will get delete properly, this is proper positive scenario.

But here i am trying to do some kind of negative scenario. Once PVC created successfully, i have logged into GD2 container using "kubectl exec" command, then stopped the volume and deleted the volume using "glstercli volume stop/delete" command, then tried to observer the behavior. What i have observed is like, after volume deleted from GD2 container, underlying pv got deleted that i can observe using 'fdisk -l' command from each node/contianer, but if i do "kubectl get pvc" from kubernetes master still pvc status is showing bound state.

Here my doubt is that if pvs are already deleted, how pvc status is showing BOUND state

**Comment by JohnStrunk** [comment]
> Here my doubt is that if pvs are already deleted, how pvc status is showing BOUND state

"Bound" just means the PVC is paired with a PV. It doesn't provide guarantees wrt:
- Whether you can successfully use that PVC in a pod
- Whether your data still exists on the back end

Your scenario has deleted the data out from under kube. There is no mechanism in kube that can be used to asynchronously feed that info back.

Now, what may be possible (but have no idea of what would happen today) is that when you try to start a pod that uses that PVC, you may be able to surface an error that the volume no longer exists. This would come back via the CSI driver as a result of the mount call failing, so would probably be visible via `kubectl describe <pod>`

**Comment by JohnStrunk** [comment]
Yes, that is expected, and there should also be an error in one of the CSI pods that corresponds to these mount attempts. Hopefully that error would say something about the volume not existing when it tries to process the mount requests.

**Comment by atinmu** [comment]
I'm not certain if this is even a bug in GD2. If the volume is deleted through CLI instead of csi-driver, then isn't this an expected behavior?

**Comment by Madhu-1** [comment]
as this is not a bug either in gd2 or in CSI driver we can close this one.
I think PVC related should be raised in `gluster-csi-driver` repo

**Comment by rmadaka** [comment]
Closing this issue as it is expected behavior.
