### ISSUE TITLE
GCS: distribute+replicate volume type

### ISSUE THREAD

**Issue by JohnStrunk** [gluster/glusterd2#1262]
@atinmu Suggested we start a discussion about what is needed from distribute-type volumes in GCS.

The main focus is on 1x3 (no distribute) at this point, but in the future, we will need to support adding distribute to the mix for supporting "large" PVs.

I would like to be able to cap the brick size at some upper limit to enable easier brick migration within the cluster, both for failure recovery and for capacity/performance balancing. Working with smaller chunks makes these easier. Even without a cap, we would still be limited by the device size. My [current proposal](https://github.com/gluster/gluster-csi-driver/pull/30/files#diff-c6b9b1189a45890edc0dcc6ed45f0205R89) is to have the max brick size provided by the csi driver on volume create. This would allow the admin to optimize for large volumes if necessary. (A big max size would keep distribute count low for large volumes, limiting metadata performance hit.)

In addition to large PVs, we'll also need to support PV resize. Today, *I think* Heketi just adds a new distribute set to handle this. It would be good to have a hybrid approach wherein we lvextend to the max permitted size before creating a new set. Handling PV resize has implications for rebalance.

In terms of initial steps, we could:
- stick w/ 1x3
- not implement the max brick size limit
- and use lvextend for resize.

Let's discuss. :smile:

**Comment by aravindavk** [comment]
- Auto distribute count and max brick size is discussed here https://github.com/gluster/glusterd2/issues/999#issuecomment-407982234
- Volume expand by `lvresize` is discussed here https://github.com/gluster/glusterd2/issues/852#issuecomment-426632380

**Comment by aravindavk** [comment]
Closing this issue since the requirement is tracked in #999
