### ISSUE TITLE
device info and device list is displaying null value

### ISSUE THREAD

**Issue by Madhu-1** [gluster/glusterd2#1276]
### Observed behavior
get device info and device list is showing null in rest response

### Expected/desired behavior
it should not display null

### Details on how to reproduce (minimal and precise)
```
curl http://10.233.36.190:24007/v1/devices 
null
```
```
curl http://10.233.36.190:24007/v1/devices/07b4d16e-8e4f-4b4d-94b9-1d7440db59a4
null
```

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): master
- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: latest container image
- Using External ETCD: (yes/no, if yes ETCD version):
- If container, which container image: 
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: kubernetes

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by vpandey-RH** [comment]
@Madhu-1  I have tried this in my system but couldn't reproduce.

**Comment by atinmu** [comment]
@Madhu-1 If this isn't reproducible, can we please close this one? We can always reopen it if the issue is seen again.

**Comment by Madhu-1** [comment]
closing this one, as am  not having reproducible
