### ISSUE TITLE
Failed to remount bricks  after glusterd2 container restart

### ISSUE THREAD

**Issue by Madhu-1** [gluster/glusterd2#1277]
### Observed behavior
after restarting the glusterd2 container, if we don't persist bricks path in `/var/run/glusterd2`, bricks won't come up automatically

### Expected/desired behavior
glusterd2  bricks path should get created automatically even if the bricks path are not present

### Details on how to reproduce (minimal and precise)
More info [gcs issue](https://github.com/gluster/gcs/issues/24)

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): master
- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: container
- Using External ETCD: (yes/no, if yes ETCD version): yes
- If container, which container image: latest
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside kubernetes

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by Madhu-1** [comment]
@aravindavk PTAL

**Comment by aravindavk** [comment]
RCA: During Volume create, it creates the target mount directory and mounts the brick. But during glusterd start, mount is tried without creating the mount directory.

**Comment by aravindavk** [comment]
With the PR https://github.com/gluster/glusterd2/pull/1053 brick directory is created before mounting the brick. Closing this issue. Please reopen if this issue happens again.
