### ISSUE TITLE
doesn't build on debian stretch/9 w/ golang-1.8

### ISSUE THREAD

**Issue by kalebskeithley** [gluster/glusterd2#1295]
### Observed behavior

build fails with error on stretch/9.  glusterd2-4.1.0 built previously on stretch, and glusterd2-5.0 builds on debian buster/10.

### Expected/desired behavior

successful build

### Details on how to reproduce (minimal and precise)

use vendor tar.xz and debian packaging bits from glusterfs-debian github repo, stretch-glusterd2-5 branch

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): 
- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: 
- Using External ETCD: (yes/no, if yes ETCD version):
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information
[stretch.build.log](https://github.com/gluster/glusterd2/files/2507604/stretch.build.log)

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by kshlm** [comment]
etcd-3.3, which we bundle in GD2 v5, requires Go1.9 or later. The update to etcd is required to support the correct gRPC version required by the Opencensus tracing support.

Go1.10 is available via the stretch-backports repository ([golang-1.10-go][1]), can be made use of if possible. If using strech-backports isn't possible, then Debian Stretch cannot have native packages.

[1]: https://packages.debian.org/stretch-backports/golang-1.10

**Comment by aravindavk** [comment]
Closing this based on previous comments. Please re-open if this issue is not yet fixed
