### ISSUE TITLE
Daemon/Service management

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#130]
Add a package to manage GlusterFS daemons and services.

This package needs to,
- [x] Start/Stop/Monitor daemons
- [x] Enable communication with daemons

Details regarding communication still need to be worked out.

**Comment by kshlm** [comment]
For the initial implementation, just being able to start/stop the daemons should be good.

**Comment by kshlm** [comment]
I've got the following picture of the framework in my mind.

```go
package daemon

type Daemon interface {
 DaemonPath() string //path to the binary
 DaemonArgs() string //args to the process
 DaemonSocket() string //path to socket file to connect to
}

func Start(d Daemon) error {
 //run(d.DaemonPath(), d.DaemonArgs())
 //save pid etc.
 return nil
}

func Stop(d Daemon) error {
 //kill pid
 return nil
}

func Call(d Daemon, req string, args interface, resp interface) error {
 c := Dial(d.DaemonSocket())
 return c.Call(req, args, resp)
}
```

**Comment by kshlm** [comment]
@prashanthpai What do you think?

**Comment by prashanthpai** [comment]
Looks good. I had something much simpler for now.

**Comment by kshlm** [comment]
#136 begins implementing this.

**Comment by atinmu** [comment]
@prashanthpai @kshlm can this be closed now?

**Comment by kshlm** [comment]
We still have to do the communication part. So let's keep this open.

**Comment by aravindavk** [comment]
Will `glusterd2` respawn the daemons if crashed? Will it periodically monitors the process? (I am not sure how is the behavior in gd1)

**Comment by kshlm** [comment]
On 28 Dec 2016 15:24, "Aravinda VK" <notifications@github.com> wrote:

Will glusterd2 respawn the daemons if crashed? Will it periodically
monitors the process? (I am not sure how is the behavior in gd1)

GD1 doesn't do this. But we can do this for GD2.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/gluster/glusterd2/issues/130#issuecomment-269453981>,
or mute the thread

**Comment by purpleidea** [comment]
On Wed, Dec 28, 2016 at 6:30 AM, Kaushal M <notifications@github.com> wrote:
>
> GD1 doesn't do this. But we can do this for GD2.

If we used libmgmt for doing the service management, all this code
happens for free :) Furthermore, you can specify when to restart, and
perhaps to do some actions first and use the entire power of the mgmt
graph.

**Comment by prashanthpai** [comment]
Sunrpc is ready and can be used to communicate with the daemons.
