### ISSUE TITLE
glusterd2 is failing on all nodes when force start the volume.

### ISSUE THREAD

**Issue by Shrivaibavi** [gluster/glusterd2#1322]
### Description
Created a replica 3 volume and started it. Added-bricks to the volume and everything was fine. Just tried to froce start the volume, the glusterd2 went into failed state on all the 3 nodes. When i tried to reproduce i saw glusterd2 failing on 2 nodes and etcd is running fine.

### Observed behavior

```
[root@dhcp35-30 ~]# glustercli volume create volrep2 --replica 3 10.70.35.30:/bricks/brick0/volrep2 10.70.35.240:/bricks/brick0/volrep2 10.70.35.106:/bricks/brick0/volrep2 --create-brick-dir
volrep2 Volume created successfully
Volume ID:  8cd54f95-8835-421a-9607-526b919301f2
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# glustercli volume start volrep2
Volume volrep2 started successfully
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# glustercli volume info volrep2

Volume Name: volrep2
Type: Replicate
Volume ID: 8cd54f95-8835-421a-9607-526b919301f2
State: Started
Transport-type: tcp
Options:
Number of Bricks: 3
Brick1: 10.70.35.30:/bricks/brick0/volrep2
Brick2: 10.70.35.240:/bricks/brick0/volrep2
Brick3: 10.70.35.106:/bricks/brick0/volrep2
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# glustercli volume status volrep2
Volume : volrep2
+--------------------------------------+--------------+------------------------+--------+-------+-------+
|               BRICK ID               |     HOST     |          PATH          | ONLINE | PORT  |  PID  |
+--------------------------------------+--------------+------------------------+--------+-------+-------+
| 8fe6858f-ce09-4aad-b0f9-e880e7e8ab7b | 10.70.35.30  | /bricks/brick0/volrep2 | true   | 46247 |  6844 |
| 6794973c-6b74-4dc6-8cd7-4671337afc2f | 10.70.35.240 | /bricks/brick0/volrep2 | true   | 42387 |  7072 |
| 0a50ed96-4f8d-40a9-a5a1-3811192be8ab | 10.70.35.106 | /bricks/brick0/volrep2 | true   | 42392 | 11641 |
+--------------------------------------+--------------+------------------------+--------+-------+-------+
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# glustercli volume add-brick volrep2 10.70.35.106:/bricks/brick2/volrep2 10.70.35.30:/bricks/brick2/volrep2 10.70.35.240:/bricks/brick2/volrep2 --create-brick-dir
volrep2 Volume expanded successfully
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# glustercli volume status volrep2
Volume : volrep2
+--------------------------------------+--------------+------------------------+--------+-------+-------+
|               BRICK ID               |     HOST     |          PATH          | ONLINE | PORT  |  PID  |
+--------------------------------------+--------------+------------------------+--------+-------+-------+
| 8fe6858f-ce09-4aad-b0f9-e880e7e8ab7b | 10.70.35.30  | /bricks/brick0/volrep2 | true   | 46247 |  6844 |
| 6794973c-6b74-4dc6-8cd7-4671337afc2f | 10.70.35.240 | /bricks/brick0/volrep2 | true   | 42387 |  7072 |
| 0a50ed96-4f8d-40a9-a5a1-3811192be8ab | 10.70.35.106 | /bricks/brick0/volrep2 | true   | 42392 | 11641 |
| 74a655d0-c6dd-4229-98f7-b5df1f217863 | 10.70.35.106 | /bricks/brick2/volrep2 | true   | 46516 | 11730 |
| e464a94f-728e-4705-b9f4-ed164c1b6ecf | 10.70.35.30  | /bricks/brick2/volrep2 | true   | 43775 |  6954 |
| 30e25f4b-eee9-48a7-a8d6-6257c884b808 | 10.70.35.240 | /bricks/brick2/volrep2 | true   | 42114 |  7156 |
+--------------------------------------+--------------+------------------------+--------+-------+-------+
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# glustercli volume info volrep2

Volume Name: volrep2
Type: Replicate
Volume ID: 8cd54f95-8835-421a-9607-526b919301f2
State: Started
Transport-type: tcp
Options:
Number of Bricks: 2 x 3 = 6
Brick1: 10.70.35.30:/bricks/brick0/volrep2
Brick2: 10.70.35.240:/bricks/brick0/volrep2
Brick3: 10.70.35.106:/bricks/brick0/volrep2
Brick4: 10.70.35.106:/bricks/brick2/volrep2
Brick5: 10.70.35.30:/bricks/brick2/volrep2
Brick6: 10.70.35.240:/bricks/brick2/volrep2
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# glustercli volume start volrep --force
volume start failed

Failed to connect to glusterd. Please check if
- Glusterd is running(http://127.0.0.1:24007) and reachable from this node.
- Make sure Endpoints specified in the command is valid
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# glustercli volume list
Error getting volumes list

Failed to connect to glusterd. Please check if
- Glusterd is running(http://127.0.0.1:24007) and reachable from this node.
- Make sure Endpoints specified in the command is valid
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# systemctl status glusterd2
● glusterd2.service - GlusterD2, the management service for GlusterFS (pre-release)
   Loaded: loaded (/usr/lib/systemd/system/glusterd2.service; enabled; vendor preset: disabled)
   Active: failed (Result: signal) since Mon 2018-11-12 10:02:42 IST; 1min 7s ago
  Process: 6479 ExecStart=/usr/sbin/glusterd2 --config=/etc/glusterd2/glusterd2.toml (code=killed, signal=KILL)
 Main PID: 6479 (code=killed, signal=KILL)
   CGroup: /system.slice/glusterd2.service
           ├─ 2101 /usr/sbin/glusterfs -s localhost --volfile-id gluster/glustershd -p /var/run/glust...
           ├─ 6490 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6512 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6534 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6556 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6579 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6601 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6623 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6645 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6667 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6699 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6844 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 6954 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─13160 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           └─13201 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...

Nov 12 09:58:44 dhcp35-30.lab.eng.blr.redhat.com systemd[1]: Started GlusterD2, the management serv...).
Nov 12 09:58:44 dhcp35-30.lab.eng.blr.redhat.com systemd[1]: Starting GlusterD2, the management ser.....
Nov 12 10:02:42 dhcp35-30.lab.eng.blr.redhat.com systemd[1]: glusterd2.service: main process exited...LL
Nov 12 10:02:42 dhcp35-30.lab.eng.blr.redhat.com systemd[1]: Unit glusterd2.service entered failed ...e.
Nov 12 10:02:42 dhcp35-30.lab.eng.blr.redhat.com systemd[1]: glusterd2.service failed.
Hint: Some lines were ellipsized, use -l to show in full.
```
### Expected/desired behavior

Glusterd2 should not go down
### Details on how to reproduce (minimal and precise)
1. Create a replica 3 volume and start it
2. Add bricks to it
3. force start the volume.
4.Check the glusterd2 status

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master):
glusterd version: v6.0-dev.6.gitc0a3aa0
git SHA: c0a3aa0
go version: go1.9.4
go OS/arch: linux/amd64
- Operating system used: CentOS Linux release 7.5.1804 (Core)
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: 
- Using External ETCD: (yes/no, if yes ETCD version): yes
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
localstatedir = "/var/lib/glusterd2"
logdir = "/var/log/glusterd2"
logfile = "glusterd2.log"
loglevel = "INFO"
rundir = "/var/run/glusterd2"
defaultpeerport = "24008"
peeraddress = ":24008"
clientaddress = ":24007"
restauth = false
etcdendpoints = "http://10.70.35.173:2379"
noembed = true

- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
[glusterd2.log](https://github.com/gluster/glusterd2/files/2570629/glusterd2.log)
[glusterd2.log](https://github.com/gluster/glusterd2/files/2570630/glusterd2.log)
[glusterd2.log](https://github.com/gluster/glusterd2/files/2570631/glusterd2.log)

- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by Shrivaibavi** [comment]
I tried to reproduce the above issue on one more fresh setup,
* Created a volume and started it
* just force started the volume again,.
* Immediately glusterd2 went down on all the nodes with latest build, didn't find any issues with etcd.
 



### Console output:

```
[root@dhcp35-219 ~]# glustercli volume create rep2 replica 3 10.70.35.219:/bricks/brick0/rep2 10.70.35.194:/bricks/brick0/rep2 10.70.35.33:/bricks/brick0/rep2 --create-brick-dir
rep2 Volume created successfully
Volume ID:  8092c4d5-ff52-439e-aa31-f744ca3c16b1
[root@dhcp35-219 ~]# 
[root@dhcp35-219 ~]# 
[root@dhcp35-219 ~]# 
[root@dhcp35-219 ~]# glustercli volume start rep2
Volume rep2 started successfully


[root@dhcp35-219 ~]# systemctl status glusterd2
● glusterd2.service - GlusterD2, the management service for GlusterFS (pre-release)
   Loaded: loaded (/usr/lib/systemd/system/glusterd2.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2018-11-12 14:33:02 IST; 8min ago
 Main PID: 32613 (glusterd2)
   CGroup: /system.slice/glusterd2.service
           ├─ 1891 /usr/sbin/glusterfs -s localhost --volfile-id gluster/glustershd -p /var/run/glust...
           ├─ 1931 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─ 2009 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...
           ├─32613 /usr/sbin/glusterd2 --config=/etc/glusterd2/glusterd2.toml
           └─32710 /usr/sbin/glusterfsd --volfile-server 127.0.0.1 --volfile-server-port 24007 --volf...

Nov 12 14:33:02 dhcp35-219.lab.eng.blr.redhat.com systemd[1]: Started GlusterD2, the management ser...).
Nov 12 14:33:02 dhcp35-219.lab.eng.blr.redhat.com systemd[1]: Starting GlusterD2, the management se.....
Hint: Some lines were ellipsized, use -l to show in full.



[root@dhcp35-219 ~]# glustercli volume start rep2 --force
volume start failed

Failed to connect to glusterd. Please check if
- Glusterd is running(http://127.0.0.1:24007) and reachable from this node.
- Make sure Endpoints specified in the command is valid
```

Updating the logs here:
[glusterd2.log](https://github.com/gluster/glusterd2/files/2571927/glusterd2.log)
[glusterd2.log](https://github.com/gluster/glusterd2/files/2571943/glusterd2.log)
[glusterd2.log](https://github.com/gluster/glusterd2/files/2571946/glusterd2.log)

glusterd2 version

glusterd version: v6.0-dev.18.git367de6f
git SHA: 367de6f
go version: go1.9.4
go OS/arch: linux/amd64

**Comment by harigowtham** [comment]
On inspection done by Vishal and I, we came to see that there were glusterfsd process still running from the older state. The content in the glusterd2 were deleted on all the node and restart was issued for glusterd without the killing the glusterfsd processes.

Once the glusterd2 was restarted, the glusterfsd process tries to connect to the glusterd2. And in this path we have a memory leak, https://github.com/gluster/glusterd2/issues/1321 and glusterd2 keep consuming memory and then goes out of memory and kills itself.

The message for oom kill on node 10.70.35.30:
Nov 12 10:02:42 dhcp35-30 kernel: glusterd2 invoked oom-killer: gfp_mask=0x201da, order=0, oom_score_adj=0
Nov 12 10:02:42 dhcp35-30 kernel: glusterd2 cpuset=/ mems_allowed=0

So once we resolve the memory leak, this issue should be fixed.

**Comment by atinmu** [comment]
Depends on #1321

**Comment by rmadaka** [comment]
Keep on Glusterd2 services are went to failed state.

Glusterd2 services are stopped running automatically on all the nodes, what i have observed from logs is that, its trying to connect bricks which are already deleted. And It is not able to connect to brick process of added replica sets which are currently available.

source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:26.048056" level=info msg="client disconnected" address="10.70.35.194:762" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:26.786936" level=info msg="client connected" address="10.70.35.194:760" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:26.788788" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/rep6 error="SearchByBrickPath: port for brick /bricks/brick0/rep6 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:26.789335" level=info msg="client disconnected" address="10.70.35.194:760" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:26.790665" level=info msg="client connected" address="10.70.35.194:759" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:26.793652" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/rep5 error="SearchByBrickPath: port for brick /bricks/brick0/rep5 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:26.794210" level=info msg="client disconnected" address="10.70.35.194:759" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:27.567469" level=info msg="client connected" address="10.70.35.33:925" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:27.568928" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/rep20 error="SearchByBrickPath: port for brick /bricks/brick0/rep20 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:27.569503" level=info msg="client disconnected" address="10.70.35.33:925" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:27.576500" level=info msg="client connected" address="10.70.35.33:922" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:27.579185" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/test/rep20 error="SearchByBrickPath: port for brick /bricks/brick0/test/rep20 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:27.579669" level=info msg="client disconnected" address="10.70.35.33:922" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:27.586634" level=info msg="client connected" address="10.70.35.33:919" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:27.588439" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/test/rep21 error="SearchByBrickPath: port for brick /bricks/brick0/test/rep21 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:27.588884" level=info msg="client disconnected" address="10.70.35.33:919" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:27.745633" level=info msg="client connected" address="10.70.35.219:905" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:27.747692" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/test/rep21 error="SearchByBrickPath: port for brick /bricks/brick0/test/rep21 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:27.748163" level=info msg="client disconnected" address="10.70.35.219:905" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:27.748496" level=info msg="client connected" address="10.70.35.219:904" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:27.750222" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/rep20 error="SearchByBrickPath: port for brick /bricks/brick0/rep20 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:27.750505" level=info msg="client disconnected" address="10.70.35.219:904" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:28.768866" level=info msg="client connected" address="10.70.35.219:898" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:28.771188" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/test/rep20 error="SearchByBrickPath: port for brick /bricks/brick0/test/rep20 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:28.771772" level=info msg="client disconnected" address="10.70.35.219:898" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:28.909454" level=info msg="client connected" address="10.70.35.194:750" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:28.911396" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/rep3 error="SearchByBrickPath: port for brick /bricks/brick0/rep3 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:28.912455" level=info msg="client disconnected" address="10.70.35.194:750" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:28.913349" level=info msg="client connected" address="10.70.35.194:749" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:28.915104" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/rep4 error="SearchByBrickPath: port for brick /bricks/brick0/rep4 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:28.915589" level=info msg="client disconnected" address="10.70.35.194:749" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:29.068341" level=info msg="client connected" address="10.70.35.194:744" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:29.070314" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/test/rep20 error="SearchByBrickPath: port for brick /bricks/brick0/test/rep20 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:29.070828" level=info msg="client disconnected" address="10.70.35.194:744" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:29.072090" level=info msg="client connected" address="10.70.35.194:743" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:29.074191" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/rep20 error="SearchByBrickPath: port for brick /bricks/brick0/rep20 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:29.074823" level=info msg="client disconnected" address="10.70.35.194:743" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:29.079790" level=info msg="client connected" address="10.70.35.194:741" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:29.082243" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/test/rep21 error="SearchByBrickPath: port for brick /bricks/brick0/test/rep21 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:29.083487" level=info msg="client disconnected" address="10.70.35.194:741" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:29.810460" level=info msg="client connected" address="10.70.35.194:739" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:29.812472" level=info msg="client connected" address="10.70.35.194:738" server=sunrpc source="[server.go:155:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
time="2018-11-19 15:18:29.815713" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/rep6 error="SearchByBrickPath: port for brick /bricks/brick0/rep6 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:29.816295" level=info msg="client disconnected" address="10.70.35.194:739" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"
time="2018-11-19 15:18:29.816353" level=error msg="registry.SearchByBrickPath() failed for brick" brick=/bricks/brick0/rep5 error="SearchByBrickPath: port for brick /bricks/brick0/rep5 not found" source="[rpc_prog.go:104:pmap.(*GfPortmap).PortByBrick]"
time="2018-11-19 15:18:29.817007" level=info msg="client disconnected" address="10.70.35.194:738" server=sunrpc source="[server.go:109:sunrpc.(*SunRPC).pruneConn]"

**Comment by vpandey-RH** [comment]
According to what I have been able to find out - 
Yes, If PortByBrick() RPC procedure is hit,  GD2 will crash as the RPC will fail and there will be continuous RPC calls after every 3 sec I guess. PortByBrick() is causing increased memory usage because of which GD2 crashes. It could be because of the pruneConn() go routine, as stated in the Serve() method in glusterd2/servers/sunrpc/server.go. I have been looking into it but couldn't find anything solution to this issue yet. Its also mentioned about leaks in the comments in Serve() method.

Also, we might need to change MountVolumeBricks() because if there is issue with mounting any one brick directory, it returns with an error and other local bricks are not mounted.

@aravindavk @Madhu-1   Could these be the reasons for the above failures ?

**Comment by aravindavk** [comment]
> Also, we might need to change MountVolumeBricks() and MountLocalBricks() because if there is issue with mounting any one brick directory, it returns with an error and other local bricks are not mounted.

This needs to be logged and continue for other local bricks as you mentioned.
