### ISSUE TITLE
PVC's are in pending for 1000 GB volumes

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#1338]
### Observed behavior
I am trying to create 1000GB PVC, PVC's are going to pending state.

Then i have logged into gd2 pod and tried to create 1000GB volume. volume creation failing with below error.
```
[root@gluster-kube1-0 /]# glustercli volume create rep1 --replica=3 --size=1000G
Volume creation failed

Response headers:
X-Gluster-Cluster-Id: 6d4ed993-de57-4c78-bb3a-14ec24a47fda
X-Gluster-Peer-Id: d2b9dba8-147a-45ca-81b0-8fdf53b8e186
X-Request-Id: c0ff1336-31e3-414e-b909-9bb76f795beb

Response body:
no space available or all the devices are not registered
```
### Expected/desired behavior
PVC creation should be successful.

With current build only i am facing this issue, till last build i was able to create the volume.

### Details on how to reproduce (minimal and precise)
-> Create GCS setup using Vagrant
-> Tried to create 1000 GB pvc , pvc went to pending state.
      ```[vagrant@kube1 ~]$ kubectl get pvc
NAME       STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
gcs-pvc6   Pending                                                                        glusterfs-csi   161m
```
-> Then login to GD2 pod and tried to create 1000GB volume, volume creation failing with below error.
     
 ```
[root@gluster-kube1-0 /]# glustercli volume create rep1 --replica=3 --size=1000G
Volume creation failed

Response headers:
X-Gluster-Cluster-Id: 6d4ed993-de57-4c78-bb3a-14ec24a47fda
X-Gluster-Peer-Id: d2b9dba8-147a-45ca-81b0-8fdf53b8e186
X-Request-Id: c0ff1336-31e3-414e-b909-9bb76f795beb

Response body:
no space available or all the devices are not registered
```

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): v6.0-dev.33.git45f8290
- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: container
- Using External ETCD: (yes/no, if yes ETCD version): yes
- If container, which container image: 
- Using kubernetes, openshift, or direct install: kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: inside

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by aravindavk** [comment]
Please let us know the available volumes info. `glustercli volume info`

**Comment by rmadaka** [comment]
Now i am able to create 1000GB volume , closing this issue.

```[vagrant@kube1 ~]$ kubectl get pvc
NAME       STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
gcs-pvc1   Bound    pvc-1a63185e-f481-11e8-be25-52540049d944   1000Gi     RWX            glusterfs-csi   35m
gcs-pvc2   Bound    pvc-e60a6bf3-f482-11e8-be25-52540049d944   1000Gi     RWX            glusterfs-csi   22m
gcs-pvc3   Bound    pvc-0e261e42-f483-11e8-be25-52540049d944   1000Gi     RWX            glusterfs-csi   21m
gcs-pvc4   Bound    pvc-3ae677ab-f483-11e8-be25-52540049d944   2Gi        RWX            glusterfs-csi   19m
```
