### ISSUE TITLE
Non-root GD2?

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#134]
And even non-root GlusterFS as whole.
I'm wondering if we can do this.

Right now, since we arent' starting any daemons yet, I run GD2 as a normal user, with CAP_SYS_ADMIN privileges. But once GD2 starts to start bricks, it will need to run as root.

If GD2 were a standalone app, it could continue to run happily with just CAP_SYS_ADMIN.

But bricks need to run as root right now. So i'm wondering if we could use user namespaces, to make brick process believe they are root and work around this.

This would close of a huge attack area against GD2 and GlusterFS.

The drawback right now is that both CAP_SYS_ADMIN and user namespaces are a  Linux only concept.

**Comment by prashanthpai** [comment]
Besides `CAP_SYS_ADMIN` is very much equivalent to root.

**Comment by kshlm** [comment]
> Besides CAP_SYS_ADMIN is very much equivalent to root.

Equivalent in a lot of ways, expect for file permissions.

**Comment by kshlm** [comment]
I was messing around and I was able to run everything non-root. I had to set the following capabilities for `glusterfsd`,
`CAP_SYS_ADMIN CAP_DAC_OVERRIDE CAP_DAC_READ_SEARCH CAP_FOWNER CAP_CHOWN`.

**Comment by tim-win** [comment]
This ended up being extremely helpful. Great use of setcap.

**Comment by purpleidea** [comment]
> But bricks need to run as root right now. 

Anyone know why this is?

**Comment by prashanthpai** [comment]
> Anyone know why this is?

There are multiple reasons I think. The one off the top of my head (and done frequently in I/O path) is that the brick process needs to set and access extended attributes in `trusted.` namespace, which requires it to be root or have `CAP_SYS_ADMIN` capability.

**Comment by aravindavk** [comment]
Closing this as we are not working on this issue and not a priority. Please re-open if this needs to be supported.

**Comment by purpleidea** [comment]
> Please re-open if this needs to be supported.

I don't think non-admins can re-open, but this certainly should be an important feature to consider IMHO. I'm not using Gluster any more, so it's not a priority for me, but I still think it's valuable =D
