### ISSUE TITLE
Rebalance status endpoint never comes back

### ISSUE THREAD

**Issue by shtripat** [gluster/glusterd2#1348]
### Observed behavior
I created a distribute volumes withe 3 bricks and added some files to the same by mounting it. After this added another additional disk to the volumes and executed rebalance start API `/volumes/{volname}/rebalance/start`. It returned a UUID successfully. Now when I execute rebalance status endpoint `/volumes/{volname}/rebalance` it never comes out and hangs.

### Expected/desired behavior
Once rebalance started for a volume, I should be able to list the rebalance status details using REST endpoint.

### Details on how to reproduce (minimal and precise)
Steps to simulate the issue
1. Create a distribute volumes with say 3 bricks
2. Mount the volume
3. Add few files with random data to the mount
4. Add another brick to the volume
5. Start rebalance using REST endpoint `/volumes/{volname}/rebalance/start`
6. Check for the rebalance status using REST endpoint `/volumes/{volname}/rebalance`

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): glusterd2-5.0-0.dev.39.git65dafcd.el7.x86_64
- Operating system used: centos 7.4
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: rpm
- Using External ETCD: (yes/no, if yes ETCD version): yes, etcd version: etcd-3.2.22-1.el7.x86_64
- If container, which container image: NA
- Using kubernetes, openshift, or direct install: direct install
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: NA

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by Madhu-1** [comment]
Fixed by #1347
