### ISSUE TITLE
Integrate gRPC with GlusterFS

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#135]
We'll be using gRPC as the RPC framework of choice in GD2. #128 is tracking progress for this.

Related to this, we'll also need to integrate gRPC with GlusterFS to allow bricks, daemons and clients to communicate with GD2.

**Comment by kshlm** [comment]
#128 changed the default inter GD2 RPC framework to gRPC. I'll leave this issue open till integration with glusterfsd is done.

**Comment by prashanthpai** [comment]
We're using sunrpc for interaction with glusterfsd and other gluster daemons. Closing this issue.
