### ISSUE TITLE
glusterd2 log should be in UTC timestamp

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#1355]
### Observed behavior
glusterd2.log dumps entries in local timezone which isn't convenient from the perspective of other gluster services following the UTC timezone logging.

### Expected/desired behavior
glusterd2.log to follow UTC timezone.

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): 
- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: 
- Using External ETCD: (yes/no, if yes ETCD version):
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by aravindavk** [comment]
https://stackoverflow.com/questions/40502309/how-can-i-set-the-logrus-time-to-utc

Create UTC formatter in `$SRC/pkg/logging`

**Comment by Madhu-1** [comment]
@aravindavk working on this one?

**Comment by Madhu-1** [comment]
do we need UTC formatting function?
can this be done like below 
`log.SetFormatter(&log.TextFormatter{FullTimestamp: true, TimestampFormat: time.UTC.String()})`

i will do my testing and update this issue with this minimal changes
