### ISSUE TITLE
error getting volume status after deleting multiple pvc

### ISSUE THREAD

**Issue by ksandha** [gluster/glusterd2#1362]
getting error in volume status after deleting 1000 pvc
```
[root@gluster-kube1-0 /]# glustercli volume status
Volume : pvc-001ea694-f79a-11e8-881b-5254001e787d
Error getting volume status

Response headers:
X-Gluster-Cluster-Id: 11f04639-0a1b-4303-a9c9-89efa449c74f
X-Gluster-Peer-Id: bc30babd-7128-497e-8ae6-a666d81f37ea
X-Request-Id: 988b2cdd-b223-4311-95c8-9407db102df7

Response body:
etcdserver: mvcc: database space exceeded
[root@gluster-kube1-0 /]# 
[root@gluster-kube1-0 /]# 

```
### Observed behavior
Getting above error while running glustercli volume status

### Expected/desired behavior
As there are no pvc , there should be any error in volume status.

### Details on how to reproduce (minimal and precise)
1) Create 1000 pvc . Almost 750 were in bound state and rest were in pending state.

2) delete all the pvc 
```
[vagrant@kube1 ~]$ kubectl get pvc 
No resources found.
[vagrant@kube1 ~]$ 
```
3) login to the gd2 pod and check the volume  status. 
```
[root@gluster-kube1-0 /]# glustercli volume status
Volume : pvc-001ea694-f79a-11e8-881b-5254001e787d
Error getting volume status

Response headers:
X-Gluster-Cluster-Id: 11f04639-0a1b-4303-a9c9-89efa449c74f
X-Gluster-Peer-Id: bc30babd-7128-497e-8ae6-a666d81f37ea
X-Request-Id: ef67de96-d505-4745-98df-6e34dc4169b5

Response body:
etcdserver: mvcc: database space exceeded
[root@gluster-kube1-0 /]# 

```

my observation:- 
seems like the etcd dabase couldn't cleanup after volume deletion. 

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): 
```
[root@gluster-kube1-0 /]# rpm -qa | grep gluster
glusterfs-6dev-0.311.git0566ecc.el7.x86_64
glusterfs-api-6dev-0.311.git0566ecc.el7.x86_64
python2-gluster-6dev-0.311.git0566ecc.el7.x86_64
glusterfs-geo-replication-6dev-0.311.git0566ecc.el7.x86_64
glusterd2-5.0-0.dev.48.gitd996927.el7.x86_64
glusterfs-libs-6dev-0.311.git0566ecc.el7.x86_64
glusterfs-client-xlators-6dev-0.311.git0566ecc.el7.x86_64
glusterfs-cli-6dev-0.311.git0566ecc.el7.x86_64
glusterfs-fuse-6dev-0.311.git0566ecc.el7.x86_64
glusterfs-server-6dev-0.311.git0566ecc.el7.x86_64
gluster-prometheus-exporter-0.3-dev.26.git8107970.el7.x86_64

```
- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container:  container
- Using External ETCD: (yes/no, if yes ETCD version):yes
- If container, which container image: 
- Using kubernetes, openshift, or direct install:  kubernetes
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
[root@gluster-kube1-0 /]# glusterd2 --version
glusterd version: v6.0-dev.48.gitd996927
git SHA: d996927
go version: go1.9.4
go OS/arch: linux/amd64
[root@gluster-kube1-0 /]# 

    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by ksandha** [comment]
[glusterd2.log](https://github.com/gluster/glusterd2/files/2643477/glusterd2.log)

Attached are the glusterd2 logs
```
[vagrant@kube1 ~]$ kubectl get pods -n gcs
NAME                                   READY   STATUS    RESTARTS   AGE
csi-attacher-glusterfsplugin-0         2/2     Running   0          3h17m
csi-nodeplugin-glusterfsplugin-85p9x   2/2     Running   0          3h17m
csi-nodeplugin-glusterfsplugin-ggg58   2/2     Running   0          3h17m
csi-nodeplugin-glusterfsplugin-t8lkc   2/2     Running   0          3h17m
csi-provisioner-glusterfsplugin-0      3/3     Running   0          3h17m
etcd-5k7gzt2gg9                        1/1     Running   0          3h22m
etcd-hw87l72ztq                        1/1     Running   0          3h21m
etcd-operator-7cb5bd459b-4bqhb         1/1     Running   0          3h23m
etcd-tkl549ks2v                        1/1     Running   0          3h20m
gluster-kube1-0                        1/1     Running   1          3h20m
gluster-kube2-0                        1/1     Running   0          3h20m
gluster-kube3-0                        1/1     Running   0          3h20m
[vagrant@kube1 ~]$ 

```

**Comment by atinmu** [comment]
from glusterd2.log:

time="2018-12-04 10:29:08.726490" level=error msg="failed to obtain lock" error="etcdserver: mvcc: database space exceeded" lockID=pvc-853f3af9-f799-11e8-881b-5254001e787d reqid=304a6979-acc3-419a-ab32-082cbffad509 source="[lock.go:180:transaction.(*Txn).lock]" txnid=ab4b3719-6c17-4c34-bb59-432ce37bf7f1
time="2018-12-04 10:29:08.729115" level=info msg="10.233.64.9 - - [04/Dec/2018:10:29:08 +0000] \"POST /v1/volumes/pvc-853f3af9-f799-11e8-881b-5254001e787d/stop HTTP/1.1\" 500 78" reqid=304a6979-acc3-419a-ab32-082cbffad509

So did we query the etcd endpoints to see if any volume information exists or not?

I'm not sure what's the space quota limit we have for the etcd in GCS setup (@kshlm ?). https://github.com/etcd-io/etcd/issues/7986#issuecomment-303896330 gives some perspective to this problem too.

**Comment by Madhu-1** [comment]
>getting error in volume status after deleting 1000 pvc

@ksandha are you able to create 1000 PVC

**Comment by ksandha** [comment]
> > getting error in volume status after deleting 1000 pvc
> 
> @ksandha are you able to create 1000 PVC

I am able to create 750 bound pvc after that i started deleting the pvc. One more issue i am hitting is #1349 with this.

**Comment by kshlm** [comment]
The space quota here is an internal etcd quota limit that is set by default is 2GiB. When this limit is reached, etcd needs to have compaction performed manually. Etcd servers could be set up to perform automatic compaction, but I'm not sure if the etcd operator sets up the etcd cluster this way.

Also, I don't think compaction would help us here. Having the volfiles of a 1000 volumes stored in etcd is probably causing us to hit this limit right now. Each volfile is a few Kilobytes, and having a thousand of those would mean a few GBs worth of data stored in etcd. We need to rethink our strategy of storing volfiles in etcd.

The etcd internal space quota can be increased upto 8GiB, but that will also be reached when we store a few thousand volumes in etcd.

**Comment by Madhu-1** [comment]
> Having the volfiles of a 1000 volumes stored in etcd is probably causing us to hit this limit right now

@kshlm i think we are not storing the volfiles in ETCD as aravinda introduced volfile templates @aravindavk can yoy confirm on this.

**Comment by kshlm** [comment]
@Madhu-1 volfile templates are used for generating volfiles. But IIRC, we still store the generated volfiles (maybe just the client volfiles) in etcd.

**Comment by aravindavk** [comment]
Only client volfiles are stored in etcd. Looks like we have to store that as well to avoid using etcd space. I will send PR to save Client volfile to disk(Or make it configurable)

**Comment by aravindavk** [comment]
> Also, I don't think compaction would help us here. Having the volfiles of a 1000 volumes stored in etcd is probably causing us to hit this limit right now. Each volfile is a few Kilobytes, and having a thousand of those would mean a few GBs worth of data stored in etcd. We need to rethink our strategy of storing volfiles in etcd.

I overlooked this comment last week. Even if a volfile takes 10KiB, 1000 volumes volfile will consume  less than 80MiB space.
