### ISSUE TITLE
GD2 smoke test failing due to xlator name change.

### ISSUE THREAD

**Issue by rishubhjain** [gluster/glusterd2#1380]
Bit-rot test failing in GD2 smoke tests with error message
 `Transaction step bitrot-enable.Commit failed on peer a71030f6-7d38-4cb5-aea6-793be99f8162 with error: xlator not found: bit-rot\nTransaction step bitrot-enable.Commit failed on peer 501da00f-ff0b-4b72-8f2e-b8937512b645 with error: xlator not found: bit-rot`.

https://build.gluster.org/job/gd2-smoke/3054/console

**Comment by rishubhjain** [comment]
Requires change in glusterfs code:
https://review.gluster.org/#/c/glusterfs/+/21733/2/xlators/features/bit-rot/src/bitd/bit-rot.c
Bit-rot xlator identifier changed from `bit-rot` to `bit-rot server`.

**Comment by atinmu** [comment]
Fixed through #612
