### ISSUE TITLE
TestBrickMux is failing spuriously in GD2-smoke job

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#1387]
Reference : https://build.gluster.org/job/gd2-smoke/3111/console

**Comment by atinmu** [comment]
https://build.gluster.org/job/gd2-smoke/3109/console
https://build.gluster.org/job/gd2-smoke/3111/console

**Comment by vpandey-RH** [comment]
https://build.gluster.org/job/gd2-smoke/3109/console - This error is quite frequent with e2e. I think its not related to BrickMux.

https://build.gluster.org/job/gd2-smoke/3111/console - This seems like an issue with  starting a new GD2 instance.

**Comment by atinmu** [comment]
Will be Fixed through https://github.com/gluster/glusterd2/pull/1455

**Comment by atinmu** [comment]
#1455 is merged. Closing it.
