### ISSUE TITLE
minimum brick size validation during Volume create

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#1389]
Auto provisioned volume create validates the minimum volume size but does not validate the minimum brick size. Following command fails 

```
glustercli volume create gv4 --size 500M --distribute 50 --subvols-zones-overlap
```

Validation required after calculating brick size

**Comment by aravindavk** [comment]
@harigowtham do you want to take this up?

**Comment by harigowtham** [comment]
@aravindavk. Yes, I'll take it up.
