### ISSUE TITLE
Unable to create any type of volume on gd2 standalone

### ISSUE THREAD

**Issue by Shrivaibavi** [gluster/glusterd2#1390]
### Observed behavior

```
[root@dhcp35-30 ~]# glustercli volume create xyz --replica 3 10.70.35.30:/bricks/brick1/xyz0 10.70.35.106:/bricks/brick1/xyz1 10.70.35.240:/bricks/brick1/xyz2 10.70.35.30:/bricks/brick1/xyz3 10.70.35.106:/bricks/brick1/xyz4 10.70.35.240:/bricks/brick1/xyz5 --create-brick-dir
Volume creation failed

Response headers:
X-Gluster-Cluster-Id: 8aa6daa1-3d77-4df3-a938-115f5797fd2a
X-Gluster-Peer-Id: 2115479a-c493-4b44-9119-aa78b0dfcd5e
X-Request-Id: 95d8a71b-790d-4652-9afd-fd9f49c9ac07

Response body:
timeout in synchronizing txn
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# glustercli volume create xyz replica 3 10.70.35.30:/bricks/brick1/xyz0 10.70.35.106:/bricks/brick1/xyz1 10.70.35.240:/bricks/brick1/xyz2 10.70.35.30:/bricks/brick1/xyz3 10.70.35.106:/bricks/brick1/xyz4 10.70.35.240:/bricks/brick1/xyz5 --create-brick-dir
Volume creation failed

Response headers:
X-Gluster-Cluster-Id: 8aa6daa1-3d77-4df3-a938-115f5797fd2a
X-Gluster-Peer-Id: 2115479a-c493-4b44-9119-aa78b0dfcd5e
X-Request-Id: 00ac9d13-ba9c-4004-b8ab-736c875cd9a3

Response body:
timeout in synchronizing txn
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# 
[root@dhcp35-30 ~]# glustercli volume create abc replica 3 10.70.35.30:/bricks/brick0/abc1 10.70.35.106:/bricks/brick0/abc2 10.70.35.240:/bricks/brick0/abc3 --create-brick-dir
Volume creation failed

Response headers:
X-Gluster-Cluster-Id: 8aa6daa1-3d77-4df3-a938-115f5797fd2a
X-Gluster-Peer-Id: 2115479a-c493-4b44-9119-aa78b0dfcd5e
X-Request-Id: cd001440-f956-48ed-adf0-d9d46ff36059

Response body:
timeout in synchronizing txn
```

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master):

 glusterd version: v6.0-dev.69.git5f88917
git SHA: 5f88917
go version: go1.11.2
go OS/arch: linux/amd64

- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: 
- Using External ETCD: (yes/no, if yes ETCD version): yes
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
[glusterd2.log](https://github.com/gluster/glusterd2/files/2671781/glusterd2.log)
[glusterd2.log](https://github.com/gluster/glusterd2/files/2671785/glusterd2.log)
[glusterd2.log](https://github.com/gluster/glusterd2/files/2671786/glusterd2.log)

- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by kshlm** [comment]
I tracked the request-id through the logs. The transaction is only reaches 2 of the nodes. The 3rd node isn't acting upon the transaction. This is causing the transaction to time out.

The 3rd node appears to be running an older GD2 version without the changes to the txn engine. Two of the nodes were restarted around 2018-12-12 10:02:11, with the new GD2 version. The 3rd node hasn't been restarted and has been running for a very long time. As the 3rd node doesn't have the new engine, it doesn't notice the transactions and act upon them. Leading to timeouts.

@Shrivaibavi Please retest the scenario in a fresh environment with the same version of GD2 installed everywhere. Please report back your findings here.

**Comment by Shrivaibavi** [comment]
@kshlm retested. It is working fine. Hence closing the issue
