### ISSUE TITLE
--size parameter in volume create CLI isn't accepting MB format

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#1398]
### Observed behavior

root@b9bad6008a5e:/home/go/src/github.com/gluster/glusterd2/build# ./glustercli volume create ivp-vol1 --size=100M
Volume creation failed

Response headers:
X-Request-Id: a2c102fb-9957-4def-86dd-6e15123661f8
X-Gluster-Cluster-Id: 8d9dae2d-b422-476a-aa5d-5f7e6cb5eb1d
X-Gluster-Peer-Id: 75a41e07-8722-427c-bd8c-89e5cb694447

Response body:
invalid Volume Size, Minimum size required is 20971520

It seems the MB format in the size input isn't entertained.

### Expected/desired behavior

1. Volume create should go through
2. Also can we mention the minimum size in (KB/MB as well) ?

### Details on how to reproduce (minimal and precise)
As explained in the description

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): master
- Operating system used: 
- Glusterd2 compiled from sources, as a package (rpm/deb), or container: 
- Using External ETCD: (yes/no, if yes ETCD version): external etcd, 3.2.2
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 

### Other useful information

- glusterd2 config files from all nodes (default /etc/glusterd2/glusterd2.toml)
- glusterd2 log files from all nodes (default /var/log/glusterd2/glusterd2.log)
- ETCD configuration
- Contents of `uuid.toml` from all nodes (default /var/lib/glusterd2/uuid.toml)
- Output of `statedump` from any one of the node

### Useful commands

- To get glusterd2 version
    ```
    glusterd2 --version
    ```
- To get ETCD version
    ```
    etcd --version
    ```
- To get output of statedump
    ```
    curl http://glusterd2-IP:glusterd2-Port/statedump
    ```

**Comment by rishubhjain** [comment]
@atinmu Yes, I guess we missed out on MB, we have added for other formats https://github.com/gluster/glusterd2/blob/master/glustercli/cmd/utils.go#L32

**Comment by aravindavk** [comment]
PR #1386 is merged which contains the fix

**Comment by Madhu-1** [comment]
reopening this issues, as we need to handle `MB` `mib` `GB` `Gib` formats in glustercli
```
[root@dhcp43-209 build]# ./glustercli volume create test115 --size=20MiB --replica=3 -v
Invalid Volume Size specified
[root@dhcp43-209 build]# ./glustercli volume create test115 --size=20MB --replica=3 -v
Invalid Volume Size specified
```

**Comment by rishubhjain** [comment]
@Madhu-1 check https://github.com/gluster/glusterd2/blob/master/glustercli/cmd/utils.go#L58, I am not sure why it is not accepting MiB and MB

**Comment by Madhu-1** [comment]
@rishubhjain PTAL #1416
