### ISSUE TITLE
[RFE] Support for Loopback devices as bricks

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#1418]
Auto provisioning Volumes by default provisions the bricks using LVM. Alternatively Loop devices can be used to create Bricks.

## Register device(LVM vs Loop):

| LVM                                              | Loop                                             |
| ------------------------------------------------ | ------------------------------------------------ |
| Create PV                                        | -                                                |
| Create VG                                        | -                                                |
| Collect Available size and save details in Store | Collect Available size and save details in Store |

## Unregister device

| LVM                                           | Loop                                          |
| --------------------------------------------- | --------------------------------------------- |
| Remove VG                                     | -                                             |
| Remove PV                                     | -                                             |
| Remove details from Store if no bricks exists | Remove details from Store if no bricks exists |

## Create Brick

| LVM                                              | Loop                                             |
| ------------------------------------------------ | ------------------------------------------------ |
| Create Thinpool                                  | Create directory                                 |
| Create LV                                        | Create Loop device                               |
| Create FS                                        | Create FS                                        |
| Mount LV                                         | Mount device                                     |
| Create Brickdir                                  | Create Brickdir                                  |

## Mount/Unmount Brick

| LVM                                              | Loop                                             |
| ------------------------------------------------ | ------------------------------------------------ |
| Mount/Unmount LV                                 | Mount/Unmount loop device                        |

## Remove Brick

| LVM                                              | Loop                                             |
| ------------------------------------------------ | ------------------------------------------------ |
| Unmount brick if mounted                         | Unmount brick if mounted                         |
| Remove LV                                        | Remove loop file                                 |
| Remove Thinpool if number of LVs is zero         | Remove directory if no files exists              |

## Get Available Size

| LVM                                              | Loop                                             |
| ------------------------------------------------ | ------------------------------------------------ |
| Using LVM commands                               | Using statvfs or df command                      |

**Comment by JohnStrunk** [comment]
For "loop", do we have an opinion on the device being given to gd2? Should it be a block device or a mounted file system? (I ask because there's no mention of formatting when the device is registered)

**Comment by aravindavk** [comment]
> For "loop", do we have an opinion on the device being given to gd2? Should it be a block device or a mounted file system? (I ask because there's no mention of formatting when the device is registered)

I was thinking directory path in mounted file system. Do we need to manage the bricks hosting Volume?

**Comment by JohnStrunk** [comment]
We'll already have sufficient permissions, so we could format and mount the lower fs ourselves. It also provides us the opportunity to add vdo in the future.

We'd need to examine whether there are reliability implications though since we would be responsible for the unmount at shutdown.

I don't know which way we should go with this. Probably start with the file system just because there are fewer unknowns there.

**Comment by poornimag** [comment]
With LVM being replaced by loop devices, How do we plan to handle disks with different size,with LVM the disks are pooled and carved to required sizes? Since the loopback brick cannot span across devices? The +1 scale will become more restrictive? Users will have to add disks of same/minimum size devices?

**Comment by JohnStrunk** [comment]
The brick can be created with any size up to the size of the lower-level file system. The restriction this is adding is that we can't string together multiple physical devices (lower-level file systems) and create a **single** brick that spans that whole capacity. We do have the ability to use dht to glue the smaller bricks together.
Going forward, we actually want to limit the max size of a brick to ease load and capacity balancing, so this may not be a big issue in practice.
