### ISSUE TITLE
Peer add failed when the removed peer is added back to the trusted pool

### ISSUE THREAD

**Issue by PrasadDesala** [gluster/glusterd2#1436]
Peer add failed when the removed peer is added back to the trusted pool.

### Observed behavior

[root@gluster-kube1-0 /]# glustercli peer add b6d7a82f-2a8d-4ce6-9d51-a404aec74997
Peer add failed

Response headers:
X-Gluster-Cluster-Id: 796a0a22-29c9-48b4-b26a-0153b8850a58
X-Gluster-Peer-Id: d0576643-b50e-4a95-831b-1222aa04c5dd
X-Request-Id: a2af2579-d305-4c50-8eef-3ae7c5a40e99

Response body:
failed to send join cluster request

### Expected/desired behavior

Peer add should succeed

### Details on how to reproduce (minimal and precise)
1) Have a 3 node gcs setup with all the 3 nodes in trusted pool.
2) Remove a node(n3)  from the trusted pool "glustercli peer remove 5187223f-d7a7-4b42-ab39-5afc4036e344"
3) Now, add back the node (n3) to the trusted pool (ID of n3 has changed)
glustercli peer add b6d7a82f-2a8d-4ce6-9d51-a404aec74997

### Information about the environment:

- Glusterd2 version used (e.g. v4.1.0 or master): v6.0-dev.93.gitd4ca2cb
- Operating system used: CentOS 7.5.1804
- Glusterd2 compiled from sources, as a package (rpm/deb), or container:  Container
- Using External ETCD: (yes/no, if yes ETCD version): Yes version: 3.3.8
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: Kubernetes

Seeing below error in glusterd2 logs:

time="2018-12-26 12:18:39.376744" level=error msg="failed RPC call" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup b6d7a82f-2a8d-4ce6-9d51-a404aec74997 on 10.233.0.3:53: no such host\"" remote="b6d7a82f-2a8d-4ce6-9d51-a404aec74997:24008" rpc=PeerService.Join source="[peer-rpc-clnt.go:47:peers.(*peerSvcClnt).JoinCluster]"
time="2018-12-26 12:18:39.376944" level=error msg="sending Join request failed" error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup b6d7a82f-2a8d-4ce6-9d51-a404aec74997 on 10.233.0.3:53: no such host\"" peer="b6d7a82f-2a8d-4ce6-9d51-a404aec74997:24008" reqid=a2af2579-d305-4c50-8eef-3ae7c5a40e99 source="[addpeer.go:82:peers.addPeerHandler]"

**Comment by oshankkumar** [comment]
Can you try adding peer using host address of peer.

**Comment by PrasadDesala** [comment]
> Can you try adding peer using host address of peer.

That worked. I can see both hostname and IP in PEER ADDRESSES for that node.

+--------------------------------------+-----------------+-------------------------------------+-------------------------------------+--------+------+
|                  ID                  |      NAME       |          CLIENT ADDRESSES           |           PEER ADDRESSES            | ONLINE | PID  |
+--------------------------------------+-----------------+-------------------------------------+-------------------------------------+--------+------+
| 65039218-8974-45bf-9e98-62fedd0ff79f | gluster-kube3-0 | gluster-kube3-0.glusterd2.gcs:24007 | 10.233.66.6:24008                   | yes    |   22 |
|                                      |                 |                                     | gluster-kube3-0.glusterd2.gcs:24008 |        |      |
| baf7c848-f83d-4d2c-9752-b84b87024b67 | gluster-kube2-0 | gluster-kube2-0.glusterd2.gcs:24007 | gluster-kube2-0.glusterd2.gcs:24008 | yes    |   25 |
| d0576643-b50e-4a95-831b-1222aa04c5dd | gluster-kube1-0 | gluster-kube1-0.glusterd2.gcs:24007 | gluster-kube1-0.glusterd2.gcs:24008 | yes    | 2446 |
+--------------------------------------+-----------------+-------------------------------------+-------------------------------------+--------+------+

**Comment by rishubhjain** [comment]
Glusterd2 cannot probe peer using peerID

**Comment by rishubhjain** [comment]
Can you close the issue?

**Comment by Madhu-1** [comment]
Peer add always work with IP address. You wont be able to add the peer with
its ID. once you delete the peer from the trusted storage pool its
associated information will be deleted from the ETCD.

**Comment by PrasadDesala** [comment]
> Peer add always work with IP address. You wont be able to add the peer with its ID. once you delete the peer from the trusted storage pool its associated information will be deleted from the ETCD.

Once the peer is detached from the node, a new ID is being generated for the node. Is there a possibility to use that ID for the new peer request? 

If it only works with IP address, can we make the failure message a bit more clear; the current message is showing as "Peer add failed" with some response body. As we are doing the peer remove with node ID the chances are more that the user will try peer add with node ID and from the error it might be difficult for the user to understand the reason of failure.

**Comment by oshankkumar** [comment]
```
ERRO[2018-12-26 14:10:55.718996] failed RPC call                               error="rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: lookup 79951e95-0d60-4bcf-9c0b-20325ac0a6a6 on 192.168.122.1:53: no such host\"" remote="79951e95-0d60-4bcf-9c0b-20325ac0a6a6:24008" rpc=PeerService.Join source="[peer-rpc-clnt.go:47:peers.(*peerSvcClnt).JoinCluster]"
```
as I can see in the gd2 logs, it is very clear that it is trying to dial some tcp address, so a user needs to pass some IP/ hostname/fqdn address in agrs.
@Madhu-1 can you please suggest, do we need some more error logs here.

**Comment by rishubhjain** [comment]
I think what @PrasadDesala wants is a clearer response, something like ` peer add failed : please use hostname or IP instead of peer ID` . Logs are pretty clear but user might not refer to logs.
