### ISSUE TITLE
Modifed volume set options are not reflecting in "glustercli volume get <volname> all"

### ISSUE THREAD

**Issue by PrasadDesala** [gluster/glusterd2#1445]
I have changed the default value of distribute.min-free-disk from 10% to 60%. The new values are reflected in the glustercli volume info output but the changes are not reflected in the output of "glustercli volume get <volname> all".

Volume Name: pvc-d16a6e66-0a70-11e9-8594-525400e31a9f
Type: Replicate
Volume ID: 47c213ce-24ff-4fd6-bac2-ebbf5cc69dce
State: Started
Capacity: 1.0 GiB
Transport-type: tcp
Options:
    cluster/replicate.self-heal-daemon: on
    debug/io-stats.count-fop-hits: on
    performance/io-cache.io-cache: off
    performance/quick-read.quick-read: off
    performance/read-ahead.read-ahead: off
    performance/write-behind.write-behind: off
    cluster/distribute.min-free-disk: 60%
    debug/io-stats.latency-measurement: on
    performance/md-cache.md-cache: off
    performance/open-behind.open-behind: off
    performance/readdir-ahead.readdir-ahead: off
Number of Bricks: 3
Brick1: gluster-kube2-0.glusterd2.gcs:/var/run/glusterd2/bricks/pvc-d16a6e66-0a70-11e9-8594-525400e31a9f/subvol1/brick1/brick
Brick2: gluster-kube3-0.glusterd2.gcs:/var/run/glusterd2/bricks/pvc-d16a6e66-0a70-11e9-8594-525400e31a9f/subvol1/brick2/brick
Brick3: gluster-kube1-0.glusterd2.gcs:/var/run/glusterd2/bricks/pvc-d16a6e66-0a70-11e9-8594-525400e31a9f/subvol1/brick3/brick

[root@gluster-kube1-0 /]# glustercli volume get pvc-d16a6e66-0a70-11e9-8594-525400e31a9f all
+-------------------------------+----------+--------+---------------+--------------+
|             NAME              | MODIFIED | VALUE  | DEFAULT VALUE | OPTION LEVEL |
+-------------------------------+----------+--------+---------------+--------------+
| nufa.lookup-unhashed          | no       | on     | on            | Basic        |
| nufa.min-free-disk            | no       | 10%    | 10%           | Basic        |
| nufa.min-free-inodes          | no       | 5%     | 5%            | Basic        |
| nufa.rebalance-stats          | no       | off    | off           | Basic        |
| nufa.rsync-hash-regex         | no       |        |               | Basic        |
| nufa.extra-hash-regex         | no       |        |               | Basic        |
| nufa.weighted-rebalance       | no       | on     | on            | Basic        |
| nufa.rebal-throttle           | no       | normal | normal        | Basic        |
| quota.enable                  | no       | off    | off           | Basic        |
| distribute.lookup-unhashed    | no       | on     | on            | Basic        |
| distribute.min-free-disk      | no       | 10%    | 10%           | Basic        |
| distribute.min-free-inodes    | no       | 5%     | 5%            | Basic        |
| distribute.rebalance-stats    | no       | off    | off           | Basic        |
| distribute.rsync-hash-regex   | no       |        |               | Basic        |
| distribute.extra-hash-regex   | no       |        |               | Basic        |
| distribute.weighted-rebalance | no       | on     | on            | Basic        |
| distribute.rebal-throttle     | no       | normal | normal        | Basic        |
| switch.lookup-unhashed        | no       | on     | on            | Basic        |
| switch.min-free-disk          | no       | 10%    | 10%           | Basic        |
| switch.min-free-inodes        | no       | 5%     | 5%            | Basic        |
| switch.rebalance-stats        | no       | off    | off           | Basic        |
| switch.rsync-hash-regex       | no       |        |               | Basic        |
| switch.extra-hash-regex       | no       |        |               | Basic        |
| switch.weighted-rebalance     | no       | on     | on            | Basic        |
| switch.rebal-throttle         | no       | normal | normal        | Basic        |
| changelog.changelog           | no       | off    | off           | Basic        |
| changelog.capture-del-path    | no       | off    | off           | Basic        |
+-------------------------------+----------+--------+---------------+--------------+

### Observed behavior

Modifed volume set options are not reflecting in "glustercli volume get <volname> all"

### Expected/desired behavior

Modifed volume set options should reflect in "glustercli volume get <volname> all" output as well.

### Details on how to reproduce (minimal and precise)

1) Create a 3 node gcs setup using valgrind.
2) Create a pvc
3) Change the default volume option of distribute.min-free-disk from 10% to 60%

### Information about the environment:

    Glusterd2 version used (e.g. v4.1.0 or master):
    glusterd version: v6.0-dev.93.gitd4ca2cb
    git SHA: d4ca2cb
    go version: go1.11.2
    go OS/arch: linux/amd64
    Operating system used: CentOS 7.5
    Glusterd2 compiled from sources, as a package (rpm/deb), or container: Container
    Using External ETCD: (yes/no, if yes ETCD version): Yes version: 3.3.8
    If container, which container image:
    Using kubernetes, openshift, or direct install:
    If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: Kubernetes

**Comment by rishubhjain** [comment]
Can you provide command that you used to modify the option? And it would be really helpful if you could provide output you get after you run the modifying command and the logs.

**Comment by aravindavk** [comment]
This line needs to be modified

https://github.com/gluster/glusterd2/blob/master/glusterd2/commands/volumes/volume-options-get.go#L81

Add xl.Category + “/“ as prefix

**Comment by PrasadDesala** [comment]
@aravindavk 

I repeated the same test on v6.0-dev.114.gitd51f60b and still see the issue. Changed the min-free.disk value to 50%, modified value is shown in volume info but still the changes are not reflected in get options for that volume.

[root@gluster-kube1-0 /]# glustercli volume info pvc-67809720-1e3a-11e9-8308-525400bf5c84

Volume Name: pvc-67809720-1e3a-11e9-8308-525400bf5c84
Type: Replicate
Volume ID: 377c1243-3b95-4f4c-8c3d-03a5854c5a9d
State: Started
Capacity: 5.0 GiB
Transport-type: tcp
Options:
    cluster/replicate.self-heal-daemon: off
    performance/md-cache.md-cache: off
    performance/quick-read.quick-read: off
    performance/read-ahead.read-ahead: off
    performance/readdir-ahead.readdir-ahead: off
    performance/write-behind.write-behind: off
    cluster/distribute.min-free-disk: 50
    debug/io-stats.count-fop-hits: on
    debug/io-stats.latency-measurement: on
    performance/io-cache.io-cache: off
    performance/open-behind.open-behind: off
....

[root@gluster-kube1-0 /]# glustercli volume get pvc-67809720-1e3a-11e9-8308-525400bf5c84 all
+-------------------------------+----------+--------+---------------+--------------+
|             NAME              | MODIFIED | VALUE  | DEFAULT VALUE | OPTION LEVEL |
+-------------------------------+----------+--------+---------------+--------------+
....
.
| distribute.min-free-disk      | no       | 10%    | 10%           | Basic        |
...
+-------------------------------+----------+--------+---------------+--------------+

**Comment by PrasadDesala** [comment]
This is tested on the latest available image. 
The fix for this patch will be available in tomorrow image. So, will re-run this test on that image.
