### ISSUE TITLE
pvc request failed to create volume with error "timeout in synchronizing txn"

### ISSUE THREAD

**Issue by PrasadDesala** [gluster/glusterd2#1458]
**Describe the bug**
pvc creation is getting stuck at pending state when the requested size is more than the actual device size.
The actual device size my machine is having is 10Gb but I sent a request to create a PVC of size 50GB. PVC create command succeed but the status is being shown as Pending for a long time.

[vagrant@kube1 ~]$ kubectl -n gcs describe pvc dbench123
Name:          dbench123
Namespace:     gcs
StorageClass:  glusterfs-csi
Status:        Pending
Volume:        
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner: org.gluster.glusterfs
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      
Access Modes:  
Events:
  Type       Reason                Age                   From                                                                                          Message
  ----       ------                ----                  ----                                                                                          -------
  Warning    ProvisioningFailed    24m                   org.gluster.glusterfs_csi-provisioner-glusterfsplugin-0_e9313507-0f49-11e9-8331-0a580ae9400d  failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: Post http://glusterd2-client.gcs:24007/v1/volumes: dial tcp 10.233.1.74:24007: connect: connection refused
  Warning    ProvisioningFailed    23m (x2 over 24m)     org.gluster.glusterfs_csi-provisioner-glusterfsplugin-0_e9313507-0f49-11e9-8331-0a580ae9400d  failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
  Warning    ProvisioningFailed    22m                   org.gluster.glusterfs_csi-provisioner-glusterfsplugin-0_e9313507-0f49-11e9-8331-0a580ae9400d  failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = error in fetching volume details Get http://glusterd2-client.gcs:24007/v1/volumes/pvc-f732d5c2-0f49-11e9-897e-525400933534: dial tcp 10.233.1.74:24007: connect: connection refused
  Normal     Provisioning          8m1s (x7 over 24m)    org.gluster.glusterfs_csi-provisioner-glusterfsplugin-0_e9313507-0f49-11e9-8331-0a580ae9400d  External provisioner is provisioning volume for claim "gcs/dbench123"
  Warning    ProvisioningFailed    7m49s (x3 over 20m)   org.gluster.glusterfs_csi-provisioner-glusterfsplugin-0_e9313507-0f49-11e9-8331-0a580ae9400d  failed to provision volume with StorageClass "glusterfs-csi": rpc error: code = Internal desc = failed to create volume: timeout in synchronizing txn
  Normal     ExternalProvisioning  4m29s (x81 over 24m)  persistentvolume-controller                                                                   waiting for a volume to be created, either by external provisioner "org.gluster.glusterfs" or manually created by system administrator

**Steps to reproduce**
1) Create a 3 node gcs system using vagrant.
2) Create a PVC of size more than the actual device size.

**Actual results**
pvc creation stuck at pending state when the created size is more than the actual device size

**Expected behavior**
pvc creating should not get stuck at pending state.

**Comment by Madhu-1** [comment]
@PrasadDesala please attach glusterd2 logs

**Comment by Madhu-1** [comment]
@oshankkumar PTAL

**Comment by PrasadDesala** [comment]
> @PrasadDesala please attach glusterd2 logs

[kube-3-glusterd2.log.gz](https://github.com/gluster/glusterd2/files/2723893/kube-3-glusterd2.log.gz)
[kube-2-glusterd2.log.gz](https://github.com/gluster/glusterd2/files/2723894/kube-2-glusterd2.log.gz)
[kube-1-glusterd2.log.gz](https://github.com/gluster/glusterd2/files/2723895/kube-1-glusterd2.log.gz)

**Comment by PrasadDesala** [comment]
@Madhu-1 @rishubhjain 
1) When the device size is 10GB and requested PVC size is 50GB it returned error,
error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
2) With the above pvc is pending state, when we requested PVC size of 1GB it returned error,
error: code = Internal desc = failed to create volume: timeout in synchronizing txn

The error codes they are returning is different. Is the second issue because of the first?

**Comment by JohnStrunk** [comment]
> > > @Madhu-1 @rishubhjain
> > > 
> > > 1. When the device size is 10GB and requested PVC size is 50GB it returned error,
> > >    error: code = Internal desc = failed to create volume: no space available or all the devices are not registered
> > 
> > 
> > This is an expected behaviour
> 
> Yes, the behavior should be expected as there is no space available on the device to create pvc but here the pvc creating is stuck at pending state. Shouldn't it fail after some retry attempts?

Kubernetes will typically let the resource pend indefinitely.

**Comment by atinmu** [comment]
timeout in synchronizing transaction is fixed through https://github.com/gluster/glusterd2/pull/1462
