### ISSUE TITLE
golint warnings shouldn't be ignored

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#156]
`make verify` currently runs `golint` as a part of `gometalinter` which is configured to mask warnings.
This has created a lot of code which doesn't follow the suggested Go coding style. This needs to be fixed.

**Comment by prashanthpai** [comment]
I'm fixing most of it right now. Will send a PR soon.

**Comment by kshlm** [comment]
@prashanthpai All of them? Or just for your PR? If it's all of them, awesome job!

**Comment by kshlm** [comment]
Also `make verify` needs to be updated to not mask golint. It would be better to have separate golint run outside of gometalinter.

**Comment by prashanthpai** [comment]
@kshlm Most of them, yes, except few places (transaction package) where it's generated code and adding `//golint:ignore` line into them did not seem to work for me.

Check out https://github.com/gluster/glusterd2/pull/157

**Comment by prashanthpai** [comment]
@kshlm For some reason, make verify gets stuck on my system for a very long time. Running `gometalinter` directly doesn't run most of the other checks.

```
[ppai@gd2-1 glusterd2]$ gometalinter 
main.go:19::warning: cyclomatic complexity 11 of function main() is high (> 10) (gocyclo)
config.go:15:2:warning: const defaultRpcAddress should be defaultRPCAddress (golint)
config.go:16:2:warning: const defaultRpcPort should be defaultRPCPort (golint)
main.go:64:5:warning: should omit comparison to bool constant, can be simplified to !gdctx.Restart (gosimple)
config.go:46::warning: Errors unhandled.,LOW,HIGH (gas)
WARNING: deadline exceeded by linter aligncheck on . (try increasing --deadline)
WARNING: deadline exceeded by linter varcheck on . (try increasing --deadline)
WARNING: deadline exceeded by linter interfacer on . (try increasing --deadline)
WARNING: deadline exceeded by linter unconvert on . (try increasing --deadline)
WARNING: deadline exceeded by linter structcheck on . (try increasing --deadline)
WARNING: deadline exceeded by linter errcheck on . (try increasing --deadline)
```

**Comment by kshlm** [comment]
For the problem with golint, check this https://github.com/kshlm/glusterd2/commit/daec652bab1946e0727ac226994d8c4611f6e6fd

I'd begun working on this a little while ago. I stopped because I didn't want fix all the lint warning at the time.

**Comment by kshlm** [comment]
> @kshlm For some reason, make verify gets stuck on my system for a very long time. Running gometalinter directly doesn't run most of the other checks.

Most of the checkers got killed by the deadline. It's too short. I set the deadline to 5 minutes to have all checkers run.

**Comment by prashanthpai** [comment]
> For the problem with golint, check this kshlm@daec652

There's also https://github.com/golang/lint/pull/249 and https://github.com/golang/lint/issues/239
