### ISSUE TITLE
Prototype flexible volgen

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#163]
We've currently decided to go ahead with a design inspired by systemd-units for specifying translator dependencies in the volume graph, which will be used to generate actual graphs. More information regarding this can be found in the [wiki][1] and this [mail thread][2].

I've begun a prototype implementation of this at [kshlm/glusterd2-volgen][3]. Once the prototype begins working for a brick graph, I'll move the code into this repo.

[1]: https://github.com/gluster/glusterd2/wiki/Flexible-Volgen
[2]: https://www.gluster.org/pipermail/gluster-devel/2016-October/051297.html
[3]: https://github.com/kshlm/glusterd2-volgen

**Comment by kshlm** [comment]
Things left to be done
- [x] File format for node files
 - Currently uses TOML, which works well enough. If needed, we could define a new DSL for this.
- [x] Loader for loading nodefiles
- [ ] Dependency resolver to build a target graph
- [ ] Handle variable number of children
 - Cluster translators can have a varying number of children
- [ ] Assign correct IDs and options to nodes
 - How do we correctly assign IDs and options to client translators
- [ ] Handle cross graph/target dependencies
 - Cache invalidation with upcall requires translators on both client and server graphs
- [ ] Complex connections between graphs
 - JBR has complex connections between client and bricks and, bricks and other bricks.

**Comment by prashanthpai** [comment]
Closing this as #364 got merged.
