### ISSUE TITLE
RPC Framework

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#201]
GD2 has an RPC framework for,
- peer to peer internal communication
- GD2 to GlusterFS daemon communication.

gRPC is used as the framework of choice for this.

**Comment by prashanthpai** [comment]
I'm closing this as we're moving ahead with using Sun RPC for now. The primary reasons for this are:
 * lack of high-level grpc API for C language
 * having to modify existing C code

Can be re-opened later if sunrpc doesn't work well or if grpc comes up with a high-level consumable C API.
