### ISSUE TITLE
Glusterd2 should return real port information for bricks

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#208]
The generated client volfiles do not have port information for the bricks. This coupled with the fact that we don't support portmap or volfile-fetch yet, means that we cannot mount using the volfile directly.

A simple fix till portmap becomes available would be to generate volfiles with the ports included.

**Comment by prashanthpai** [comment]
> A simple fix till portmap becomes available would be to generate volfiles with the ports included.

I manually added the ports and mounting works. However, ports aren't available during volfile generation as the bricks aren't up yet. A simple fix would be to replace the ports in volfile every time there's a volume start and/or stop.

**Comment by prashanthpai** [comment]
PR #246 addresses this.
