### ISSUE TITLE
TLS encryption for client to server (brick communication) 

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#214]
GD2 should have TLS/SSL or similar encryption support implemented.

**Comment by kshlm** [comment]
gRPC which uses HTTP2 is secure by default. We have disabled it for the time being. This will be corrected before we finally release. The ReST and SunRPC interfaces also need to be secure by default, which are not particularly hard to implement.

The major thing we need to think about is how we would be creating and using default keys/certs without user intervention.

**Comment by purpleidea** [comment]
@atinmu Please stop randomly assigning issues to be without discussion first. Thanks

**Comment by atinmu** [comment]
@prashanthpai @aravindavk What work are pending here?

**Comment by prashanthpai** [comment]
> @prashanthpai @aravindavk What work are pending here?

First step - we need to check current state of:

* TLS between client (glusterfs mount) and glusterd1
* TLS between client and brick processes after initial handshake

**Comment by kshlm** [comment]
> First step - we need to check current state of:
> 
> TLS between client (glusterfs mount) and glusterd1
> TLS between client and brick processes after initial handshake

Just dumping what I remember. Ask me if you need any further clarifications.

Currently with GD1 and glusterfs, TLS is implemented using OpenSSL, and IIRC is limited to TLS1.0 and above, with a specific cipher list and encryption options (DEFAULT_CIPHER_LIST, DEFAULT_DH_PARAM, DEFAULT_EC_CURVE etc) which can be configured during runtime.

TLS is integrated with the rpc socket transport, and gets enabled when ssl_enabled is set on the transport and relevant options for the cert, private key and allowed ca files are set. The RPC transport is a layer in the RPC lib below sunrpc layer which implements SunRPC protocol. The TLS connection setup happens before the rest of the SunRPC framework comes into play, so this happens before the RPC handshakes happen.

TLS is used for 3 main things with GlusterFS right now.
1. On wire encryption - Nothing extra to add about this.
2. Authentication - To ensure that the client connecting is who it says it is. This is done by setting the list of CAs whose signed certs are allowed.
3. Authorization - To ensure that the authenticated client is authorized to access the volume. This is only done with the data network encryption, not the management encryption, and uses the `auth.ssl-allow` option. This is also handled above the rpc-transport layer by the in the sunrpc layer.

With GD1 by default the same certificate, private key and ca list are used by all GlusterFS processes on a node. There is no separation between these for the management and data networks.

**Comment by prashanthpai** [comment]
For the first cut, I'll be sending a PR to enable TLS for client to brick communication i.e I/O path. The client and brick volfiles expect transport options to be present as follows:

```
volume test-server
    type protocol/server
    option transport.listen-backlog 1024
    option transport.socket.keepalive-count 9
    option transport.socket.keepalive-interval 2
    option transport.socket.keepalive-time 20
    option transport.tcp-user-timeout 0
    option transport.socket.ssl-enabled on
    option transport.socket.keepalive 1
    option auth.addr./export/brick1/data.allow *
    option auth-path /export/brick1/data
    option auth.login.2bed1644-d45c-4a5b-ba99-180a1c7bad4e.password d4540b76-715a-4958-a6be-6ef00efdf227
    option auth.login./export/brick1/data.allow 2bed1644-d45c-4a5b-ba99-180a1c7bad4e
    option transport.address-family inet
    option transport-type tcp
    subvolumes /export/brick1/data
end-volume
```
```
volume test-client-0
    type protocol/client
    option send-gids true
    option transport.socket.keepalive-count 9
    option transport.socket.keepalive-interval 2
    option transport.socket.keepalive-time 20
    option transport.tcp-user-timeout 0
    option transport.socket.ssl-enabled on
    option password d4540b76-715a-4958-a6be-6ef00efdf227
    option username 2bed1644-d45c-4a5b-ba99-180a1c7bad4e
    option transport.address-family inet
    option transport-type tcp
    option remote-subvolume /export/brick1/data
    option remote-host gd2-1
    option ping-timeout 42
end-volume
```

**Comment by prashanthpai** [comment]
The second part to do is allow authorization of clients i.e provide a list of clients that are authorized to access a particular volume. This requires certain xlator optoins to be turned on in server xlator.

In the following example, we allow two entities named `gd2-` and `Anyone` to access the volume:

```log
152: volume test-server
153:     type protocol/server
154:     option transport.socket.listen-port 49152
155:     option rpc-auth.auth-glusterfs on
156:     option rpc-auth.auth-unix on
157:     option rpc-auth.auth-null on
158:     option rpc-auth-allow-insecure on
159:     option transport-type tcp
160:     option transport.address-family inet
161:     option auth.login./export/brick1/data.allow 535d7e15-48f6-428a-9347-3ce3c69fbf21
162:     option auth.login.535d7e15-48f6-428a-9347-3ce3c69fbf21.password 1ba50b70-fcd0-4e09-9b15-fb425485ca4b
163:     option auth-path /export/brick1/data
164:     option auth.login./export/brick1/data.ssl-allow gd2-1,Anyone
165:     option auth.addr./export/brick1/data.allow *
166:     option transport.socket.keepalive 1
167:     option transport.socket.ssl-enabled on
168:     option transport.tcp-user-timeout 0
169:     option transport.socket.keepalive-time 20
170:     option transport.socket.keepalive-interval 2
171:     option transport.socket.keepalive-count 9
172:     option transport.listen-backlog 1024
173:     subvolumes /export/brick1/data
174: end-volume
```

**Comment by prashanthpai** [comment]
The `glusterfs` fuse mount doesn't have command line options to provide a custom path to SSL certs. It's unfortunately hardcoded to a file in `/etc/ssl/glusterfs*`. I'll try to get as much parity with state of glusterd1.
