### ISSUE TITLE
Brick multiplexing support

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#219]
Placeholder issue to track adding support for brick multiplexing.

**Comment by purpleidea** [comment]
On Fri, Jan 13, 2017 at 1:14 AM, Prashanth Pai <notifications@github.com>
wrote:

> Placeholder issue to track adding support for brick multiplexing.



Is there a core (glusterfs) upstream ticket for this issue or any
design/docs page about it? Thanks!

**Comment by prashanthpai** [comment]
@purpleidea Here's everything that's out there:

* [Feature page](https://github.com/gluster/glusterfs-specs/blob/master/under_review/multiplexing.md) and tracker [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1385758)
* [Detailed walthrough](https://docs.google.com/document/d/1yOoLv1zMCShd8PUFnGGKzZsOpshvFmgJxIwLERhErds/edit#heading=h.vam0sl52njw) of the implementation
* [Implementation](http://review.gluster.org/#/c/14763/) posted for review

**Comment by purpleidea** [comment]
@prashanthpai Great links, thanks!

**Comment by atinmu** [comment]
@raghavendra-talur I'd like you to pick this up for GCS-Sprint1.

**Comment by atinmu** [comment]
@raghavendra-talur Circling back to see if the first cut document is ready for review?

**Comment by prashanthpai** [comment]
I have opened the following separate issues for pending stuff (not GCS focus) not addressed by PR #219:

* Extend brick multiplexing to volume expand (add brick) operation: https://github.com/gluster/glusterd2/issues/1303
* Implement 'cluster.max-bricks-per-process' option: https://github.com/gluster/glusterd2/issues/1304

**Comment by atinmu** [comment]
This can't be completed by GCS/0.3 release. Moving it to 0.4.

**Comment by amarts** [comment]
Note that relevant GlusterFS patch is now merged!
