### ISSUE TITLE
Brick status showing offline when glusterd is down on peer node and restarted glusterd on the other node in the two node cluster.

### ISSUE THREAD

**Issue by Byreddys** [gluster/glusterd2#243]
Details about the issue are there in BZ- https://bugzilla.redhat.com/show_bug.cgi?id=1257854.

Reason for creating this issue here is - https://bugzilla.redhat.com/show_bug.cgi?id=1257854#c9

**Comment by prashanthpai** [comment]
I'm closing this one as it's a glusterd1 bug. If found in glusterd2, we'll reopen or file  a new one. This can be better tracked in issue #325
