### ISSUE TITLE
Improve log formatting

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#249]
The log entries should be better structured with some laid down guidelines and conventions which should make it easy for external tools to parse the logs.

**Comment by kshlm** [comment]
We need to improve our logging format to include

- [ ]  Better timestamps
- [ ] Log location (place log function was called)

**Comment by atinmu** [comment]
@devyanikota Interested to take this up?

**Comment by devyanikota** [comment]
@atinmu can take it up. Just fyi, took up issue #404 
Can take this up after that.

**Comment by prashanthpai** [comment]
I don't have anything specific in mind to improve here. @kshlm's checklist has been completed.
