### ISSUE TITLE
Add rest endpoints for peer commands

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#25]
This also requires description of the ReST api for peer commands

**Comment by atinmu** [comment]
Here are my review comments after looking through the APIs for peers:

1. In attach peer wouldn't we need to introduce one more flag to denote whether the glusterd instance should act as an etcd server or client"
2. In get peer, you have mentioned the id to be the parameter. I think we should continue to have name as parameter for both peer & volume commands.
