### ISSUE TITLE
Management API package - REST API SDKs

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#265]
This management API package should be similar to libgfapi but for management. For now, we can focus on go bindings that allows access to glusterfs cluster management operations. This API can be independently used y external consumers and internally by our own CLI implementation.

**Comment by kshlm** [comment]
Requires #251, and will be a part of #205

**Comment by aravindavk** [comment]
Restclient API design is getting complicated than expected, following alternatives shows the issues to use with CLI. 

## Alternative 1:

Restclient always returns object, CLI/consumer can marshal it into whatever format

Example:

    func PeerStatus() ([]Peer, error)

This is good API design, only problem is that it is doing extra Marshal and Unmarshal
which is not required. CLI calls this API, restclient gets JSON output from
server and then unmarshals into respective object. CLI consumes this and again
marshals it to get JSON output.(`gluster peer status --json`)

If we follow this approach, then we should be careful while using multiple
fields in struct for the same entity or derived fields. For example,

    package main
     
    import (
        "encoding/json"
        "encoding/xml"
     
        "fmt"
    )
     
    type Peer struct {
        ID            string `xml:"id" json:"id"`
        Name          string `xml:"name" json:"name"`
        Connected     bool   `xml:"-" json:"connected"`
        ConnectedFlag int    `xml:"connected" json:"-"`
    }
     
    func updatePeerStatus(peer *Peer, connected bool) {
        peer.ConnectedFlag = 0
        if connected {
        	peer.Connected = connected
        	peer.ConnectedFlag = 1
        }
    }
     
    func main() {
        peer := Peer{ID: "p1", Name: "Peer 1"}
        updatePeerStatus(&peer, true)
     
        fmt.Println("Print object")
        fmt.Println(peer)
     
        fmt.Println("Direct JSON output")
        data1, _ := json.Marshal(&peer)
        fmt.Println(string(data1))
     
        fmt.Println("Direct XML output")
        data2, _ := xml.Marshal(&peer)
        fmt.Println(string(data2))
     
        fmt.Println("XML output(JSON->Object->XML)")
        var p Peer
        xml.Unmarshal(data1, &p)
        data3, _ := xml.Marshal(&p)
        fmt.Println(string(data3))
    }

Output shows that we got wrong value for `<connected>` tag in last XML output.

    Print object
    {p1 Peer 1 true 1}
    Direct JSON output
    {"id":"p1","name":"Peer 1","connected":true}
    Direct XML output
    <Peer><id>p1</id><name>Peer 1</name><connected>1</connected></Peer>
    XML output(JSON->Object->XML)
    <Peer><id></id><name></name><connected>0</connected></Peer>


## Alternative 2:

Restclient accepts one more parameter `responseType` and returns `interface{}`

Example,

        func PeerStatus(respType string) (interface{}, error)

Extra Marshal/Unmarshal issue is avoided with this, but

- It adds one extra parameter to all restclient APIs
- If we return interface then auto generated document will not have any info
  about the structure.
- Explicit typecast required even if return type is specified in the input.

      dataRaw, err := PeerStatus("json")
      if err == nil{
              data, ok := dataRaw.(string)
      }

      peerStatusRaw, err := PeerStatus("")
      if err == nil{
                peerStatus, ok := peerStatusRaw.(*Peer)
      }


## Alternative 3:

Provide different functions for JSON/XML.

Example:

    PeerStatus() ([]Peer, error)
    PeerStatusJSON() (string, error)
    PeerStatusXML() (string, error)


Any thoughts?

**Comment by prashanthpai** [comment]
I am closing this as package `restclient` has already been introduced.
