### ISSUE TITLE
Implement volume expand (add brick)

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#267]

**Comment by kshlm** [comment]
Depends on volgen mainly.

**Comment by prashanthpai** [comment]
This also requires to extend current REST API. I propose enabling add and remove brick operations by allowing the REST client to make a `POST` request to the `v1/volumes/{volname}` endpoint.

**Comment by prashanthpai** [comment]
PR #318 fixes this. Closing this issue
