### ISSUE TITLE
Support creation of all types of volumes

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#268]
As of writing this issue, creation of only distribute, replicate and distributed replicate volume types is implemented. Other types like sharded volume and disperse volume should be supported.

**Comment by amarts** [comment]
Isn't this and #269 almost similar?

I will keep updating #269 for all the future reference.

**Comment by prashanthpai** [comment]
@amarts Yes they are similar. This issue intended to track efforts to get glusterd2 to support all types that glusterd1 supports today. Issue #269 intended to collect thoughts on how easy/difficult it would be to add an entirely new volume type (non-existent today) when we switch to glusterd2.

**Comment by prashanthpai** [comment]
Issue #429 and #430 track this progress in more detail. Closing this.
