### ISSUE TITLE
ReST API document

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#27]
Need to create a document describing the ReST API for GlusterD-2.0

**Comment by kshlm** [comment]
I've put up an in-progress document in a [gist][1]. Comments can be posted on the gist itself, or in this issue.

[1]: https://gist.github.com/kshlm/b8acdf053a64eae60ed1

**Comment by kshlm** [comment]
I've put the document in the [wiki][1]. This will be easier for people to edit.

[1]: https://github.com/gluster/glusterd2/wiki/ReST-API

**Comment by atinmu** [comment]
I've updated the wiki with volume commands APIs

**Comment by kshlm** [comment]
Thanks @atinmu

**Comment by nsathyan** [comment]
I think we should also include the provision to version the APIs.  Somehow I did not see it.  If it is already taken care, ignore my comment.  

Regarding the "addresses" passed for Attach peer.  Since it can be FQDN/IP/Hostname/Shortname, wondering if addresstype should be mentioned:

**Comment by kshlm** [comment]
@nsathyan Thanks for bringing up versioning. Versioning in HTTP ReST APIs is generally done by prefixing the ReST endpoints with a version tag. For eg., the endpoint of a versioned volume get request would become `/v1/volumes/{id}`. I'll add this to the wiki.

On the addresses part, differentiating between different address formats is not required IMO. Socket connect accepts address strings of all the mentioned types.

**Comment by prashanthpai** [comment]
Some initial suggestions and thoughts:

* Is there any use-case in exposing op-version as a field as response to GET version request.
* How about a `/info` endpoint that exposes cluster capabilities. For example: does it support snapshot or tiering  etc.
* API to list endpoints.
* A `transaction-id`  field in JSON response. If glusterd log entries use the same transaction id throughout the lifecycle of that request, it will **greatly** aid in debugging.
* A timestamp indicating the system time on the server side node executing the command.
* Distinguish response code when entity to be created/added already exists. Example: Return `201 Created` when adding a new peer and `202 Accepted` if the peer being added already exists. Similar suggestion to things like volume start etc.
* A `PUT` method would be more suitable for volume creation and `POST` method would be suitable for changing volume options (similar to gluster volume set)
* A `HEAD` request on volume endpoint can return results similar to gluster volume status

**Comment by atinmu** [comment]
@prashanthpai : Thanks for your comments, we will look into them and get back.

**Comment by lpabon** [comment]
###  Peers
* Attach and detach peer most likely need to be Asynchronous HTTP calls, *if* these calls take more than 1 second.
* Attach Peer
    * Curious on the purpose of `name` in Attach Peer.  Is that a "human" identification for the peer?  Should that be handled instead by the glusterd client?  I guess my question is, what would happen if this did not exist.  Just curious
* Get peer
    * `online` should probably not be a boolean since there may be more states than just on/off, if not now, then maybe in the future.  Maybe make it a `string` with a key of `status`.
* List Peer
    * Just confused. I think you mean an array of peer information objects.  That way it doesn't confuse with a list of peer IDs.

### Volume
* Create volume
    * I'm almost sure that this should be asynchronous
    * _transport_ documentation shows types in uppercase.  Does that matter?  Should they lowercase? 
    * Instead of taking what we have today in the CLI and using it as an API, should we rethink it a bit? For example, it would be nice to say "I want this volume to be a Replicated-Distributed with Replica 3", and not to have the call figure it out from the input.  Just a suggestion.
* Get volume
    * A lot of values have uppercase, should they?
    * Looks like there are a few issues with the JSON example
* Get volumes
    * This could be a LOT of information coming in one shot.  Could it return a list of volume names, and then have the client decide if it wants to ask info on each?  This is probably the same suggestion I have on Get peers.
* Start/Stop/Delete volumes should probably be asynchronous

### Other comments
* Where is 'add-brick'.

**Comment by lpabon** [comment]
@atinmu @kshlm Example of Asynchronous Operations:
* [Heketi Wiki](https://github.com/heketi/heketi/wiki/API#async)
* [GoDoc for AsyncHttpManager in heketi/rest](https://godoc.org/github.com/heketi/rest)

**Comment by atinmu** [comment]
@lpabon : thanks for your review comments, will go through them and resolve.

**Comment by prashanthpai** [comment]
@lpabon Many volume operations shouldn't take longer than a few seconds. It's additional work for the client to check back on the `Location` response header. **If** at all async operations is needed, my suggestion would be to make this a tunable based on a configurable server side timeout. For example, if the server side timeout is set to 2 seconds,  then, if the request is completed within 2 seconds, there should be no `Location` in response header. If it's taking longer, include one. Users then will have a choice to enable/disable async functionality by increasing/decreasing timeout as per their need.

**Comment by aravindavk** [comment]
1. Please include Brick Online status also in GET /volumes/{name}
Example,

"bricks": [
    {
        "id":"e5c26603-82bf-11e5-9d59-3c970e9eb10d",
        "hostname":"x.x.x.x"
        "path":  "/gluster/brick1",
        "online": true,
    },
    {
        "id":"06c47cc3-82c0-11e5-9d59-3c970e9eb10d",
        "hostname":"y.y.y.y"
        "path":  "/gluster/brick2",
        "online": false
    }
]

## Usage of force option in Create Volume 

Single option to bypass multiple things is not good. For example, force option bypasses the following
1. Use the bricks used by other Volume
2. Allow creating in root dir

A user gets first error that bricks are used by other volume and uses force option to bypass that. User will not get any clue about second error even if its exists.

There should be separate flags for each bypass item also different option in CLI

For example,

"flags": {
    "reuse_bricks": true,
    "allow_root_dir": true
}

and in CLI

gluster volume create ... --allow-root-dir --reuse-bricks

## Volume name should be parameter instead of request body
In Create Volume,

name is sent in request body. For uniformity with Stop/Delete calls we can have volume name as parameter.

Create POST /volumes/{name}
Delete DELETE /volumes/{name}
Stop POST /volumes/{name}/stop
Start POST /volumes/{name}/start

**Comment by lpabon** [comment]
@prashanthpai I think that the mistake is that we think users we'll be waiting.  This is API reference for a software client.  The client will do what you say, but the API needs to be asynchronous to allow clients not to block.

**Comment by prashanthpai** [comment]
@atinmu 

+1 to @aravindavk's suggestion to make volume name part of URL instead of request body during volume creation. This will bring clarity on PUT vs POST. Rule of thumb suggested in this [PUT vs POST](https://stackoverflow.com/questions/630453/put-vs-post-in-rest) article: 

`Do you name your URL objects you create explicitly, or let the server decide? If you name them then use PUT. If you let the server decide then use POST.`

and also,

`PUT is for creating when you know the URL of the thing you will create. POST can be used to create when you know the URL of the "factory" or manager for the category of things you want to create.`

In volume creation case, if volume name is going to be part of URL, use `PUT`. If it's going to be part of request body, use `POST`.

**Comment by lpabon** [comment]
@prashanthpai I ran into the same issue during Heketi.  I looked at other APIs and made the decision not to place names in the URL because of two things: 1. Its is a real pain to URL encode/decode the strings, and there was no need if the string was passed in JSON.  2. Only `id` was passed in the url which was generated by the service.  This is the same style that most of the OpenStack APIs work (except for Swift ;-)).

That's just my opinion. Technically there is nothing wrong doing it either way, I just found it easier to only pass it in the body.

**Comment by kshlm** [comment]
Just a common reply to everyone. The document in its current state is only describing the APIs for basic volume management and peer management, as these are the things we'll be implementing for our first milestone. Finishing up the APIs for other operations (add/remove bricks, rebalance, status, etc.) will require help from all of you. We will also require help in identifying any other APIs we would need to provide.

**Comment by kshlm** [comment]
> Some initial suggestions and thoughts:
> 
> Is there any use-case in exposing op-version as a field as response to GET version request.
I don't see why this information shouldn't be exposed. But this endpoint was mainly a means to get versioning information about the API basically.

> How about a /info endpoint that exposes cluster capabilities. For example: does it support snapshot or tiering etc.
This is good idea. We just need to identify the information we are going to present here. This would be the ideal place to include op-version information IMO.

> API to list endpoints.
I don't see much value in getting just the list of endpoints without any documentation attached. But this shouldn't be hard to do.

> A transaction-id field in JSON response. If glusterd log entries use the same transaction id throughout the lifecycle of that request, it will greatly aid in debugging.
This should be added. Thanks for noticing this.

> A timestamp indicating the system time on the server side node executing the command.
The HTTP headers should include a server-side timestamp. Wouldn't that be enough?

> Distinguish response code when entity to be created/added already exists. Example: Return 201 Created when adding a new peer and 202 Accepted if the peer being added already exists. Similar suggestion to things like volume start etc.
I tried to use the return codes keeping in mind their HTTP meanings. From what I understand, `202 Accepted` means that the server accepted you request for processing but hasn't processed it yet. This is good for asynchronous APIs, but not for the APIs we've described till now, which are all synchronous.

> A PUT method would be more suitable for volume creation and POST method would be suitable for changing volume options (similar to gluster volume set).
I'm skipping this as we have some other discussions happening on this. I'll add my comments to them.

> A HEAD request on volume endpoint can return results similar to gluster volume status
A HEAD request just returns the HTTP headers. That wouldn't be of any help to share status.

**Comment by kshlm** [comment]
> Peers
> 
> Attach and detach peer most likely need to be Asynchronous HTTP calls, if these calls take more than 1 second.

The primary client I was thinking about when writing down these APIs was the CLI, which is generally a synchronous client (if we consider the current CLI which is what we'll be trying to emulate). Synchronous operations keeps things simple. I think it'll be nice if we could support dual-mode APIs, which could either be synchronous or asynchronous, and let the clients decide using a query parameter like `?asynchronous=1`.

> Attach Peer
> Curious on the purpose of name in Attach Peer. Is that a "human" identification for the peer? Should that be handled instead by the glusterd client? I guess my question is, what would happen if this did not exist. Just curious.

Yes this is the human readable/understandable/usable id. If this did not exist, the first address in the address list will be used.

> Get peer
> online should probably not be a boolean since there may be more states than just on/off, if not now, then maybe in the future. Maybe make it a string with a key of status.

The online state and a peer status are two different things. We could have both.

> List Peer
> Just confused. I think you mean an array of peer information objects. That way it doesn't confuse with a list of peer IDs.

Yes. I did mean that.

> Volume
> 
> Create volume
> I'm almost sure that this should be asynchronous

See my comment on peer attach.

> transport documentation shows types in uppercase. Does that matter? Should they lowercase?

Transport types are enums or constants in code, which generally are in upper-case. Using the same case here makes it easier to recognize what are strings, and which strings are constants.

> Instead of taking what we have today in the CLI and using it as an API, should we rethink it a bit? For example, it would be nice to say "I want this volume to be a Replicated-Distributed with Replica 3", and not to have the call figure it out from the input. Just a suggestion.

Could you elaborate this more? I didn't understand.

> Get volume
> A lot of values have uppercase, should they?

> Looks like there are a few issues with the JSON example

We'll fix the JSON.

> Get volumes
> This could be a LOT of information coming in one shot. Could it return a list of volume names, and then have the client decide if it wants to ask info on each? This is probably the same suggestion I have on Get peers.

I agree. With a huge number of volumes, this would be problematic. We should change it to just return a list of volume-names and/or volume-ids.

> Start/Stop/Delete volumes should probably be asynchronous

> Other comments
> 
> Where is 'add-brick'.

This needs to be added. We aren't targeting this for our first release.

**Comment by kshlm** [comment]
> Include Brick Online status in GET /volumes/{name}
> 
> Please include Brick Online status also in GET /volumes/{name}
> Example,
> 
> "bricks": [
> {
>     "id":"e5c26603-82bf-11e5-9d59-3c970e9eb10d",
>     "hostname":"x.x.x.x"
>     "path":  "/gluster/brick1",
>     "online": true,
> },
> {
>     "id":"06c47cc3-82c0-11e5-9d59-3c970e9eb10d",
>     "hostname":"y.y.y.y"
>     "path":  "/gluster/brick2",
>     "online": false
> }
> ]

This is a nice suggestion. But I'm not convinced we need to provide brick status for all volume GET requests. Like the existing `volume info` command I think the GET request should just return volume information. This is a simple read operation from the store. Getting live brick status isn't relatively as simple, and it would involve other hosts in the cluster as well.

We could possibly make GDs keep updating the status of their local daemons into the central store. This would allow us to get brick status with a simple read. I think we should keep this suggestion open, and see if we can make this work.

**Comment by kshlm** [comment]
> Usage of force option in Create Volume
> 
> Single option to bypass multiple things is not good. For example, force option bypasses the following
> 1. Use the bricks used by other Volume
> 2. Allow creating in root dir
> 
> A user gets first error that bricks are used by other volume and uses force option to bypass that. User will not get any clue about second error even if its exists.
> 
> There should be separate flags for each bypass item also different option in CLI
> 
> For example,
> 
> "flags": {
>     "reuse_bricks": true,
>     "allow_root_dir": true
> }
> and in CLI
> 
> gluster volume create ... --allow-root-dir --reuse-bricks

This is an absolute requirement. We have more than enough troubles with just a single bypass flag. Thanks for reminding us of this @aravindavk .
I'll update the wiki with this.

**Comment by kshlm** [comment]
> Volume name should be parameter instead of request body
> 
> In Create Volume,
> 
> name is sent in request body. For uniformity with Stop/Delete calls we can have volume name as parameter.
> 
> Create POST /volumes/{name}
> Delete DELETE /volumes/{name}
> Stop POST /volumes/{name}/stop
> Start POST /volumes/{name}/start

I think we should stop using the volume name as the primary identifier for a volume. The name should just be a human readable/understandable string, which is allowed in the APIs for convenience. The primary volume identifier will be a UUID assigned by GlusterD. This will also be the primary method of access via the API. Since we don't know this UUID before hand we cannot have `POST /volumes/{name}` endpoint.

I'll make this clearer in the document.

**Comment by lpabon** [comment]
@kshlm 
>The primary client I was thinking about when writing down these APIs was the CLI, which is generally a synchronous client (if we consider the current CLI which is what we'll be trying to emulate). Synchronous operations keeps things simple. I think it'll be nice if we could support dual-mode APIs, which could either be synchronous or asynchronous, and let the clients decide using a query parameter like ?asynchronous=1

I think we are confusing two things.  The API interface and the user interface.  The CLI can definitely be synchronous, but the API should be asynchronous.  The reason why is that other applications (like Heketi, UI, whatever), must be provided models to be able to break, cancel, and provide feedback, and that cannot happen with a synchronous blocking model.

For example, Heketi API is asynchronous, but the `heketi-cli` is synchronous.

**Comment by lpabon** [comment]
>I think we should stop using the volume name as the primary identifier for a volume. The name should just be a human readable/understandable string, which is allowed in the APIs for convenience. The primary volume identifier will be a UUID assigned by GlusterD. This will also be the primary method of access via the API. Since we don't know this UUID before hand we cannot have POST /volumes/{name} endpoint.

Absolutely!  I think the same should apply to nodes in the peer api.

**Comment by atinmu** [comment]
###Peers
#### Attach peer  
Shouldn't the endpoint be `/peers` instead of `/peers/`
#### List peers 
Shouldn't the endpoint be `/peers` instead of `/peers/`
Shouldn't the Body contain only the list of peer UUIDs instead of the complete objects, this was a comment from @lpabon

###Volumes
#### Create volume
Shouldn't the endpoint be `/volumes` instead of `/volumes/`
#### Get volumes
Shouldn't the Body contain only the list of volume IDs instead of the complete objects, this was a comment from @lpabon
#### Start/Stop/Delete volume
Shouldn't the endpoints have `id` instead of `name`

**Comment by lpabon** [comment]
Hi, any updates on the documentation?

**Comment by lpabon** [comment]
@kshlm Looks like some of the JSON examples are not valid JSON. Also, do you want to review this at the Gluster Summit?  We can take some time to make sure we look it over again.  It has been a while.
