### ISSUE TITLE
Replace node (move node to a different cluster)

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#277]
This was a usecase from the containers team (kubernetes + gluster)

**Comment by atinmu** [comment]
@prashanthpai Could you elaborate further on the use case more?

**Comment by atinmu** [comment]
## Checklist
- [ ] ReST APIs availibility in wiki
- [ ] CLI commands
- [ ] Sufficient logging
- [ ] Availibility of metrics data if applicable
- [ ] Xlator options table upto date?
- [ ] Test cases & test coverage of the functionality

**Comment by amarts** [comment]
Need more details here please. In the meantime, I am updating #472

**Comment by aravindavk** [comment]
Closing this bug as duplicate of #472 

#472 covers all the combination of Replace brick/Peer
