### ISSUE TITLE
merging libmgmt branch to master

### ISSUE THREAD

**Issue by amarts** [gluster/glusterd2#302]
@kshlm @prashanthpai @aravindavk @purpleidea @atinmu 

Raising the issue as I didn't see any PR for it. 

The expectation is while glusterd2 works as default 'config' manager for glusterfs project, and replaces the current glusterd codebase, there is lot more which could be done with this project.

To keep in line with that bigger goal, we would need multiple ways to manage states. Hence, it would be great to keep the current transaction model along with resource model of libmgmt in codebase, so when a new contribution comes, they can have options of using one of the two approaches.

It is fine to be keeping either one as 'optional' (mainly the issue comes because of tightly coupled `etcd` in both codebase).

Lets have more discussion about this here in the thread, if any.

**Comment by amarts** [comment]
@atinmu ☝️

**Comment by atinmu** [comment]
https://github.com/gluster/glusterd2/pull/247 is the one what you are interested for?

**Comment by purpleidea** [comment]
@atinmu I think he's referring to one which would pull mgmt into git master and which @kshlm did some nice work to hook into his supervisor code so that it starts up with everything else... Currently a `grep` on git master doesn't yield the string `purpleidea`, so I assume the import isn't in there yet.

**Comment by prashanthpai** [comment]
@purpleidea @atinmu  I see that the glusterd repo has two branches - `libmgmt` and `feat/libmgmt`. The code present there is incomplete and cannot be merged to master in it's current state. 

To get things moving forward and get libmgmt in glusterd2 repo, I'd like to see review-able PR which does not break the current master (including the existing etcd stuff and transaction framework).

**Comment by purpleidea** [comment]
@prashanthpai I think that @kshlm had a working branch which did all of this. It had the transaction code along side the mgmt stuff, which as discussed could let me use mgmt resources for underlying things such as mkfs for disks, and the etcd stuff and so on, while in parallel you could build your transaction code.

**Comment by prashanthpai** [comment]
Closing issue as it has been fixed in PR #303
