### ISSUE TITLE
Default values of volume set for new volumes should be configurable

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#312]
During a conversation with rtalur IRL, he had the following suggestion and request: `A user should be able to set default for volume set options (example write behind off). These defaults should be applied to all new volumes created in the cluster`

**Comment by aravindavk** [comment]
+1

Final = Global defaults + User defaults + User Configured

**Comment by atinmu** [comment]
Yes, I've seen an user asking for a similar infra where one can use a particular tunable for all the volumes. With current infra, one has to execute volume set for individual volumes to achieve the same. Probably a default option config file which glusterd will parse at its init to override the defaults?

**Comment by amarts** [comment]
What is this 'user defaults' ? Do we have different users in CLI? or user defaults here is the things configured as default from the 'admin' user?

I am fine with the idea. This does solve some use-cases, where we know for certain work-loads some xlators wouldn't work.

**Comment by atinmu** [comment]
Isn't this already possible now with the options field we can pass in the volume create request itself?

**Comment by prashanthpai** [comment]
> Isn't this already possible now with the options field we can pass in the volume create request itself?

Yes, that's possible today but user has to explicitly do it for every volume created.
IIUC, the use case was for options that will be "implicitly" applied to all new volumes created.

**Comment by aravindavk** [comment]
Closing this issue since this is now possible by editing volfiles Templates. (https://github.com/gluster/glusterd2/pull/1229). Please re-open if this is not addressing the issue
