### ISSUE TITLE
Better API to specify which bricks form a replica set

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#313]
Currently, the list of bricks provided during volume create needs to be ordered and this ordering decides which bricks form a replica set. I can imagine that this can be irritating for admins to craft the request so and can also be prone to human errors.

**Comment by amarts** [comment]
👍 But from glusterd2 point of view, i would keep it ordered, and bring another layer of intelligence in CLI tool to handle it?

**Comment by purpleidea** [comment]
@prashanthpai Can you elaborate more on this issue? Was there some discussion I missed about this? Thanks!

**Comment by prashanthpai** [comment]
@purpleidea With glusterd1, a volume create for a distributed-replicate volume (2x2) looks like this:

```sh
# gluster volume create test replica 2 host1:/brick1 host2:/brick2 host3:/brick3 host4:/brick4
```

In the above example, `host1:/brick1` and `host2:/brick2` form a replica pair and the other two form another replica pair. The replica set is chosen on the basis of the order in which bricks are specified in the volume create command.

This proposal is to allow admin to specify which bricks form a replica pair explicitly in the API request and not implicitly by ordering the list of bricks.

**Current (json request for volume create)**: There's no explicit and clear way to define replica sets
```json
{
	    "name": "test",
	    "replica" : 2,
	    "bricks": [
		"192.168.56.25:/export/brick",
		"192.168.56.26:/export/brick",
		"192.168.56.27:/export/brick",
		"192.168.56.28:/export/brick"
	    ],
}
```

**Comment by purpleidea** [comment]
@prashanthpai How would this new API or datastructure look for example?

**Comment by prashanthpai** [comment]
> @prashanthpai How would this new API or datastructure look for example? (Your cli example and json example look equivalent)

I don't have anything specific in mind yet. It could be something as simple as nested arrays in json. Each inner array is a replica set of bricks.

**Comment by prashanthpai** [comment]
@aravindavk I'm closing this as the newly filed issue #388 tracks this enhancement.
