### ISSUE TITLE
Unhealthy etcd cluster during peer remove

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#323]
This is the current order of operations on the initiator node during peer remove:

1. Remove peer from the store (list at /peers)
2. Remove remote etcd as member using etcd member API
3. Restart the etcd on the remote peer being removed.

Step 2 can fail when the cluster is unhealthy which is a transient and fully recoverable state. If step 2 fails, the store becomes inconsistent as we would've already removed the peer from store in step 1. The client cannot retry (as the store doesn't contain the peer entry)

The right order should be - remove the etcd member first and then remove entry from the store. In this case, the client can send the remove peer request again.

**Comment by kshlm** [comment]
This shouldn't happen once #324 is merged.

**Comment by atinmu** [comment]
Can we test this and close given #324 is already merged?

**Comment by kshlm** [comment]
With elasticetcd we have mostly solved this. But we have the specific case of peer remove in 2 node clusters that needs to be solved. Closing this issue.
