### ISSUE TITLE
gluster volume status doesn't show bricks on nodes where glusterd is not running

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#325]
Unlink GlusterD 1.0, we should think about how to dump the information about the bricks hosted on a node where glusterd is not running.

One of the suggestion we received is to show like following:

BrickXYZ - 'peer not connected' - N/A .

**Comment by prashanthpai** [comment]
This has been implemented in PR https://github.com/gluster/glusterd2/pull/484
