### ISSUE TITLE
avoid redundant volume options

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#328]
In GD1's volume map entry table we had ended up with lot of redundant volume options because of which different values can't be set for them.  A detailed walk through of volume map entry table would be required especially while writing the volgen part of GD2.

Examples:

performance.cache-size
network.ping-timeout

**Comment by atinmu** [comment]
A place holder to cross check this once all the xlator option changes are merged into glusterfs master. Would be good to test at mvp-1.

**Comment by atinmu** [comment]
I believe this can be closed now..
@prashanthpai @kshlm ?

**Comment by atinmu** [comment]
Is there anything needed to be worked on for this issue apart from testing?

**Comment by prashanthpai** [comment]
> Is there anything needed to be worked on for this issue apart from testing?

Nope, nothing else. We do not store the options. We only load it from the xlators themselves.
