### ISSUE TITLE
local state directory default path should be changed

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#33]

**Comment by kshlm** [comment]
This is configurable using the `-localstatedir` option.

**Comment by atinmu** [comment]
Although its configurable but don't you think current form of the code always consider it as a current working directory?  I've had a comments on this on your peer APIs patch and you mentioned that we'll change it later, that's why I thought of opening up an issue to track it.

**Comment by kshlm** [comment]
Nope it doesn't. It's just takes the current working directory as the default if the option isn't given. It's the default value that needs to be changed.

**Comment by atinmu** [comment]
Thanks @kshlm for clarification. I've changed the heading of the issue.
