### ISSUE TITLE
elasticetcd: store contents wiped on glusterd2 restart (single node) 

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#346]
In a single node cluster, volume information doesn't exist in the store on restart of glusterd2.

Steps to reproduce:
1. Create a volume
2. Restart glusterd2
3. List the volume

Checked this on `master` and also with `kshlm-correct-store-restart` branch (PR #341)

**Comment by kshlm** [comment]
Closed it by mistake.
