### ISSUE TITLE
Volume start fails if '.glusterfs/indices' directory isn't present

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#353]
This [recent change](https://review.gluster.org/17426) requires `.glusterfs/indices` to be present on the brick path.

Log entry from brick which failed to start:

```
[2017-08-08 06:23:11.770085] E [MSGID: 138001] [index.c:2344:init] 0-test-index: Failed to find index basepath /expor
t/brick1/data/.glusterfs/indices. [No such file or directory]
```

**Comment by nikhiljha** [comment]
I'm still getting this error on a brand new glusterfs 6.1 cluster. Creating that directory on the bricks solved the issue.

**Comment by viejillo** [comment]
I see this same error on Gluster 6.5
Creating that directory did not solve the issue on my end
 volume start: engine: failed: Failed to find brick directory /gluster_bricks/engine/engine for volume engine. Reason : No such file or directory
