### ISSUE TITLE
Revisit option name that turns on xlators

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#376]
The xlator option table can also contain options that load (add to graph) or turn on an xlator. For example, to turn on the barrier xlator, as of today, one has to set option named `barrier.barrier` to on. This should rather simply be just `barrier`. IOW, we need a way to identify such options. One approach is to let xlators themselves define which option in option table is a "gobal switch" resulting in the xlator itself being turned on. We can use the newly introduced [flags](https://github.com/gluster/glusterfs/blob/master/libglusterfs/src/options.h#L110) field in the `volume_option_t` struct.

**Comment by amarts** [comment]
I was thinking of solving it by approach mentioned in  https://github.com/gluster/glusterfs/issues/304 Can you check if that solves your problem?

**Comment by aravindavk** [comment]
With the templates support for Volgen(https://github.com/gluster/glusterd2/pull/1229). A Xlator can be enabled by setting `[<graph-name>].<option-name>=on` in Volinfo. (Volume Set/Reset need to be accommodated once template support merges)

Some Xlators understands enable by having a option in the graph as below,

    volume gv7-changelog
        type features/changelog
        option changelog on
        subvolumes gv7-changetimerecorder
    end-volume

And some of the Xlators doesn't need any option to say it is enabled. If xlator present in volfile means enabled. This can be handled by setting `EnabledByOption` field in Volfile template.

**Comment by aravindavk** [comment]
With Glusterfs Patch https://review.gluster.org/21813 and Glusterd2 patch https://github.com/gluster/glusterd2/pull/1370 we can enable/disable xlators if option name with same name as xlator exists in respective options table.
