### ISSUE TITLE
Add design spec

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#4]
We need to add one quickly.

**Comment by atinmu** [comment]
Thanks for opening up this issue. We all need to work on this asap.

**Comment by rajeshjoseph** [comment]
Section: Bootstrapping and managing the centralized store
This section talks about creating the etcd cluster. The doc only talks about creation of new cluster, how about existing clusters? How will existing cluster nodes choose monitoring nodes.

Also if you have created a monitoring cluster as described in the design and later if admin wants to remove a node how will he/she select a replacement node as monitoring node.

I believe you have already taken care of but it will good to have those details in the design.

**Comment by rajeshjoseph** [comment]
Transaction Framework:
It would be good to put some more information on this transaction framework. 
+ I need clarity on how would you handle different types of data, e.g. node specific vs cluster specific data, static information vs dynamic information (e.g. status, space consumed, etc).
+ Will it be a transaction framework or simple interface for etcd? What I mean is that do we have transaction semantics like transaction begin, commit or rollback feature? It would be great to have some clarity on this.

**Comment by atinmu** [comment]
@rajeshjoseph : Thanks for having a look at the doc.
### How will existing cluster nodes choose monitoring nodes
* Whether a node will be acted as etcd server/client will be based on the flag provided during peer probe. Please refer to Jeff's mail given as a link in the section for more details.
* On an upgrade case all the nodes in the cluster will be booted as etcd client as default. Admin would need to form the monitor cluster by setting 'JOIN' option for the peers participating in the mon cluster. A ReST/CLI interface will be provided for the same with out any further probe involved.

### Also if you have created a monitoring cluster as described in the design and later if admin wants to remove a node how will he/she select a replacement node as monitoring node
*  I think the above statements answer this too. Admin can either probe a new node using 'JOIN' flag or use the interface to set 'JOIN' option for a particular peer which he/she wants to add in the mon cluster.

**Comment by atinmu** [comment]
@rajeshjoseph : We haven't reached to a stage where we can answers to these questions straight forwardly as the transaction framework design is yet to begin and the current piece of information is just the goal of it. But having said, we are looking forward to make transaction framework having multiple phases like validation, commit & rollback, these three are must. Locking & unlocking is something we haven't decided yet. We'll keep on adding information to this section once we are into it.

**Comment by kshlm** [comment]
@rajeshjoseph This [page](/gluster/glusterd2/wiki/Transaction-framework) should provide a little more information on how we plan to do the transaction framework.
