### ISSUE TITLE
Use nightly glusterfs RPMs in CI tests

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#409]
...because it takes so long otherwise.

**Comment by nixpanic** [comment]
The CI can use the repositories that are provided at http://artifacts.ci.centos.org/gluster/nightly/

**Comment by prashanthpai** [comment]
Glusterd2 and its CI tests relied on the code and changes in `experimental` branch of glusterfs and that branch didn't have nightly builds. Those code changes from experimental branch are being ported to master branch. Once that's done, we will use nightly builds of master branch.

**Comment by nixpanic** [comment]
If needed, we can do nightly builds of the experimental branch as well. Until now, nobody raised the request. There are only few changes needed to make this work:

- handle `experimental` in the same way as `master` in [`nightly-builds.sh`](https://github.com/gluster/glusterfs-patch-acceptance-tests/blob/master/centos-ci/scripts/nightly-builds.sh)
- add triggers for `experimental` to [nightly-rpm-builds.yml](https://github.com/gluster/glusterfs-patch-acceptance-tests/blob/master/centos-ci/jobs/nightly-rpm-builds.yml)

**Comment by prashanthpai** [comment]
Fixed in PR https://github.com/gluster/glusterd2/pull/492
