### ISSUE TITLE
Events APIs integration

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#418]
Events APIs support is required in Gd2, Currently `glustereventsd` is independent daemon outside Glusterd, So that it can receive client events even if Glusterd is down. In future we can embed this server also in gd2, but current plan is to add support to run existing glustereventsd with gd2.

Supported CLI operations of Events API, and details about gd2 eventsapi plugin

## Enable/disable

Start managing glustereventsd from gd2

    POST /v1/events/enable
    POST /v1/events/disable

## gluster-eventsapi reload

    POST /v1/events/reload

Send SIGUSR2 to running `glustereventsd` in all peer nodes

## gluster-eventsapi status

    GET /v1/events/

Show running status of glustereventsd from all peer nodes

## gluster-eventsapi webhook-add and gluster-eventsapi webhook-mod

    POST /v1/events/webhook

- Add to etcd store
- generate webhooks.json in all peer nodes
- Reload glustereventsd by sending SIGUSR2

## gluster-eventsapi webhook-del

    DELETE /v1/events/webhook

- Delete webhook details from store
- Regenerate webhooks.json in all peer nodes
- Reload glustereventsd by sending SIGUSR2

## gluster-eventsapi webhook-test

    POST /v1/events/webhook/test

Try to reach the webhook URL from all peer nodes by sending a dummy POST request and show the status

## gluster-eventsapi config-get

    GET /v1/events/config

Get the config from etcd store

## gluster-eventsapi config-set

    POST /v1/events/config

Once set, if config requires restart then restart glustereventsd else reload.

## gluster-eventsapi config-reset

    DELETE /v1/events/config

Same as above.

In future, we need to store 30 minutes(or configurable) of events in etcd itself, so that consumers can consume events from single URL(GET /v1/events) instead of registering as Webhook.(Very useful if nodes do not have access to webhook URL, for example consuming events from laptop)

**Comment by amarts** [comment]
Thanks @aravindavk for providing API endpoints.

Meantime, should we also provide json format too for getting clarity? or you prefer it to evolve.

**Comment by nnDarshan** [comment]
Myself @aravindavk @prashanthpai had a discussion related to this issue. Where there was a suggestion to expose the events via an API end point rather than using the approach in gd1 where eventsapi service pushes events to web-hooks of all the clients who have registered for listening the events. 
With the current suggestion, there should be a ttl(say 30mins) to the events. So that that etcd is not overloaded with events. With this approach clients have to query this API endpoint periodically and get the events.
@aravindavk @atinmu @prashanthpai @kshlm Please provide your suggestions on which approach to take.

**Comment by atinmu** [comment]
> With the current suggestion, there should be a ttl(say 30mins) to the events. So that that etcd is not overloaded with events. With this approach clients have to query this API endpoint periodically and get the events.

There are two concerns what I have with this approach:

1. etcd can consume lot of CPU and memory if we try to overload it with too much of data (I am arriving at this based on the conversation I had with tendrl folks). In Gluster there are some connection events which can get toggled through continuously (BRICK_CONNECT, BRICK_DISCONNECT for eg). So even though we implement a ttl based approach, we'd still end up heavy loading the etcd database.

2. Typically all the events should be real time as close as possible. In this case, given we're asking the consumer to pull in for the events the question remains on the frequency of this poll. A push based notification is still a better approach IMO. 

I'd like to hear others thoughts as well.

**Comment by aravindavk** [comment]
TTL can be reduced to 15 mins I guess.

> etcd can consume lot of CPU and memory if we try to overload it with too much of data (I am arriving at this based on the conversation I had with tendrl folks). In Gluster there are some connection events which can get toggled through continuously (BRICK_CONNECT, BRICK_DISCONNECT for eg). So even though we implement a ttl based approach, we'd still end up heavy loading the etcd database.

Compared to metrics collection, These events traffic is not heavy.  Events gathering is distributed across the nodes,  and event will be broadcasted using the internal events framework. I don't think comparison with Tendrl makes sense here. (If I understood right, Tendrl is pushing get-state data from each node to etcd and aggregation is done in etcd. Lot of lock/read/update etc)

> Typically all the events should be real time as close as possible. In this case, given we're asking the consumer to pull in for the events the question remains on the frequency of this poll. A push based notification is still a better approach IMO.

Existing Webhook push can be retained, without breaking the backward compatibility.

There is a difference in the poll API here. API will not do any computations but simply read the events from etcd and returns it.

Providing API has lot of advantageous compared to Webhooks. 
- Gluster nodes need not have access to external monitoring/management application.
- No extra registration required except using Gluster REST APIs
- Easy integration with CLI( `glustercli events` can show all events happened in last 15 mins)
- In case of Webhook, if webhook listener dies, events will be missed till that Webhook listener comes back. But in case of APIs, Events will not get missed, even if listener dies and restarts.
- Websockets integration is possible.(Provides realtime notification to consumers, which was in initial plan of EventsAPi)
- No overhead of storing Webhook's auth details in etcd store.

**Comment by aravindavk** [comment]
All the APIs mentioned in the description will remain same to provide the existing feature via webhook. 

Additionally `glustereventsd` can be easily migrated to Glusterd2 under `$SRC/glusterd2/servers`. Eventsd uses UDP to listen to the local events for other Gluster processes and Client processes.(Default port can be used using Mux)

Once eventsd receives Event, it will internally broadcast using the internal Events Framework with TTL 5-15 mins. and then pushes the message to webhook if any webhooks registered.(go routine, One webhook push should not block other messages) 

Additional to above APIs, we need a new API to list the events with different query params

    GET /v1/events
    GET /v1/events?after_ts=1514540739

**Comment by shtripat** [comment]
>> Compared to metrics collection, These events traffic is not heavy. Events gathering is distributed across the nodes, and event will be broadcasted using the internal events framework. I don't think comparison with Tendrl makes sense here. (If I understood right, Tendrl is pushing get-state data from each node to etcd and aggregation is done in etcd. Lot of lock/read/update etc)

+1 to this

**Comment by atinmu** [comment]
@aravindavk is there any work left here?

**Comment by aravindavk** [comment]
> @aravindavk is there any work left here?

- [ ] User driven events coverage from Gd2(which are available in Gd1)
- [ ] Changing port number in glusterfs code(with GD2, port will be same as client port)
- [ ] JWT signing support for signing webhooks
- [ ] Documentation

**Comment by aravindavk** [comment]
API endpoints are implemented for Events APIs. I will open new issue to track the pending issues related to Events APIs
