### ISSUE TITLE
API Error codes

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#419]
HTTP status codes are very limited, we need to return separate error code in gd2 REST APIs. For example, When Volume start command is called twice, "Error: Volume already started", HTTP status code will be 500. With this error code, it is very difficult for any application to make sense of this data unless it parses the error string.

On error JSON response should have Error code and error message. For example,

    {
        "error_code":  <NUM>,
        "error": MESSAGE
    }

`pkg/api` can publish the list of error codes.

**Comment by aravindavk** [comment]
Support for adding API error codes is available. New feature implementation can add its error code when required. Closing this issue.

**Comment by prashanthpai** [comment]
The API should support returning an array of errors. I'll soon send a PR to slightly improve it.
