### ISSUE TITLE
Self Heal commands for Gd2 managed Volumes

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#427]
Collected the Heal commands details from AFR team.

## Volume Start
Start self heal daemon in nodes with atleast one brick which belong to replicate/EC/Arbiter volume.

## Volume Stop
If all Replicate/EC/Arbiter volumes are stopped then stop Self heal daemon.

## Enable/Disable
Remember the enable or disable state so that it will be used for other APIs. Note: Self heal daemons are not stopped with gd1, can we stop self heal daemons if it is disabled?

CLI:

    volume heal <VOLNAME> enable | disable

APIs:

    POST /v1/volumes/:name/heal/enable
    POST /v1/volumes/:name/heal/disable

## Trigger Heal

CLI:

    volume heal <VOLNAME> full

API:

    POST /v1/volumes/:name/heal

Glusterd will notify running self heal daemons. Have to get more details about the notification mechanism

## Heal Info
With Gd1, CLI is running another command as child process and displays stdout of the child process.

With Gd2, Glusterd2 will run the same CLI command and converts stdout as JSON response

CLI:

    volume heal <VOLNAME> statistics [heal-count [replica <HOSTNAME:BRICKNAME>]]
    volume heal <VOLNAME> info [summary | split-brain]

APIs:

    GET /v1/volumes/:name/heal

## Options

CLI:

    volume heal <VOLNAME> granular-entry-heal {enable | disable}

API:

    POST /v1/volumes/:name/heal/granular-entry/enable
    POST /v1/volumes/:name/heal/granular-entry/disable

## Split brain

CLI:

    volume heal <VOLNAME> split-brain {bigger-file <FILE> | latest-mtime <FILE> |source-brick <HOSTNAME:BRICKNAME> [<FILE>]}

**Comment by atinmu** [comment]
## Checklist
- [ ] ReST APIs availibility in wiki
- [ ] CLI commands
- [ ] Sufficient logging
- [ ] Availibility of metrics data if applicable
- [ ] Xlator options table upto date?
- [ ] Test cases & test coverage of the functionality

**Comment by itisravi** [comment]
The glfsheal binary which is used for getting heal info is also used for split-brain resolution. If resolving split-brain fails, it prints various error messages to stdout. In GD2, we would need to make sure that these are also captured and eventually propagated to the gluster CLI or the clients which interact with GD2 using the rest APIs.

**Comment by aravindavk** [comment]
> The glfsheal binary which is used for getting heal info is also used for split-brain resolution. If resolving split-brain fails, it prints various error messages to stdout. In GD2, we would need to make sure that these are also captured and eventually propagated to the gluster CLI or the clients which interact with GD2 using the rest APIs.

Please post the sample output of each commands. Created example for converting HealInfo to JSON here https://play.golang.org/p/xMbW-oG-RJP

**Comment by atinmu** [comment]
@vpandey Can you please specify what's pending on the self heal side?

**Comment by vpandey-RH** [comment]
@atinmu Still working on index/full-heal API , won't be able to complete it by the end of this sprint. Since, all the self heal APIs can't be completed in this sprint (although I think index/full-heal APIs can be finished this week) will take up remove brick api in the next sprint( GCS-Sprint2).

**Comment by atinmu** [comment]
@vpandey-RH Please have an issue filed for index & full heal API so that I can tag it for Sprint1 and then move this to Sprint2. Once done, acknowledge.

**Comment by vpandey-RH** [comment]
@atinmu  Acknowledged.

**Comment by aravindavk** [comment]
Closing this tracker issue since self-heal feature is implemented. Please open separate issues if any fix required to self heal feature.
