### ISSUE TITLE
Arbiter volume type support in GD2

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#429]
volume create should be able to create an arbiter volume. This github issue is to track for the related work required in this area.

**Comment by atinmu** [comment]
## Checklist
- [ ] ReST APIs availibility in wiki
- [ ] CLI commands
- [ ] Sufficient logging
- [ ] Availibility of metrics data if applicable
- [ ] Xlator options table upto date?
- [ ] Test cases & test coverage of the functionality

**Comment by aravindavk** [comment]
Arbiter volfile support added with #388. CLI support and other required things for Arbiter support is available via #480
