### ISSUE TITLE
disperse volume support in GD2

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#430]
volume create should be able to create a dispersed volume. This github issue is to track for the related work required in this area.

**Comment by atinmu** [comment]
## Checklist
- [ ] ReST APIs availibility in wiki
- [ ] CLI commands
- [ ] Sufficient logging
- [ ] Availibility of metrics data if applicable
- [ ] Xlator options table upto date?
- [ ] Test cases & test coverage of the functionality

**Comment by atinmu** [comment]
@kmlmhnn Now that we have the code in place can we update wiki where ever applicable? Also is it safe to consider tests cases and coverage to be completed?

**Comment by kmlmhnn** [comment]
@atinmu The wiki has been updated. `testDisperse` covers all the basic operations like creating, starting, mounting etc.

**Comment by atinmu** [comment]
The rest of these metrics can be confirmed along with running all the disperse related regression suites with GD2.

**Comment by prashanthpai** [comment]
As per @kmlmhnn, there is nothing else do be done here.
