### ISSUE TITLE
Replicate volume support in GD2

### ISSUE THREAD

**Issue by karthik-us** [gluster/glusterd2#453]
Missing template graph for replicate volume. Creating pure replicate volume is currently not supported in GD2. This issue is to track the related work in that area.

**Comment by atinmu** [comment]
## Checklist
- [ ] ReST APIs availibility in wiki
- [ ] CLI commands
- [ ] Sufficient logging
- [ ] Availibility of metrics data if applicable
- [ ] Xlator options table upto date?
- [ ] Test cases & test coverage of the functionality
