### ISSUE TITLE
gluster volume profile in GD2

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#455]

**Comment by atinmu** [comment]
## Checklist
- [ ] ReST APIs availibility in wiki
- [ ] CLI commands
- [ ] Sufficient logging
- [ ] Availibility of metrics data if applicable
- [ ] Xlator options table upto date?
- [ ] Test cases & test coverage of the functionality

**Comment by atinmu** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1393532 has an ask to make the profile data available in json format.

**Comment by vpandey-RH** [comment]
@atinmu @kotreshhr I would like to give it a try, if no one's working on this.

**Comment by atinmu** [comment]
@kotresshhr - Please ack if you haven't started working on it so that
Vishal can get this started.

**Comment by atinmu** [comment]
@kotreshhr ^^

**Comment by kotreshhr** [comment]
I am not working on this, Vishal can start working on this.

**Comment by atinmu** [comment]
Even though a first cut PR #962 exists, but doesn't seem like it can be made ready and merged by end of Sprint 1. Moving this to Sprint 2.

**Comment by aravindavk** [comment]
Since PR #962 available for review, adding to `GCS/0.3`

**Comment by vpandey-RH** [comment]
@pranithk   Tested the patch, seems to work fine for volume profile.

**Comment by atinmu** [comment]
The glusterfs patch is now in, can we take this to closure now?

**Comment by vpandey-RH** [comment]
@atinmu  As the patch was merged today so just waiting for the glusterfs build to be updated. So, we might have an update by tomorrow

**Comment by atinmu** [comment]
Fixed through https://github.com/gluster/glusterd2/pull/962
