### ISSUE TITLE
gluster volume reset CLI & API in GD2

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#456]

**Comment by atinmu** [comment]
## Checklist
- [ ] ReST APIs availibility in wiki
- [ ] CLI commands
- [ ] Sufficient logging
- [ ] Availibility of metrics data if applicable
- [ ] Xlator options table upto date?
- [ ] Test cases & test coverage of the functionality

**Comment by atinmu** [comment]
Anything else needs to be done on volume reset API and CLI completion? Do we have the glustercli in place for this API?

**Comment by prashanthpai** [comment]
> Anything else needs to be done on volume reset API and CLI completion? Do we have the glustercli in place for this API?

Have to integrate volume rest API with actor framework and see ensure self heal daemon start/stop works.

**Comment by atinmu** [comment]
> Have to integrate volume rest API with actor framework and see ensure self heal daemon start/stop works.

Thanks, Also please confirm if cli is in place or not?

**Comment by vpandey-RH** [comment]
Sure, will work on it.

**Comment by devyanikota** [comment]
@aravindavk @prashanthpai in the above checklist, can you please confirm apart from tests(last point) if anything else needs to be done? thank you.

**Comment by atinmu** [comment]
Is @devyanikota still owning this up and taking it to completion? Or is it @vpandey-RH you?

**Comment by vpandey-RH** [comment]
@atinmu  I have added the CLI as well as the e2e test for this which was missing after the rest API was completed by @devyanikota  . The PR is still under review.

**Comment by atinmu** [comment]
Closed through #882
