### ISSUE TITLE
replace-brick command in GD2

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#472]

**Comment by atinmu** [comment]
@karthik-us @itisravi When are planning to start to work on this?

**Comment by karthik-us** [comment]
@atinmu will start to work on this once I finish with the arbiter issue (should be done by this week), which is targeted for 3.4.

**Comment by atinmu** [comment]
Who from AFR team can take this up?

@karthik-us @itisravi ^^

**Comment by JohnStrunk** [comment]
Adding to @amarts usecase above:
> Regular hardware recycle: Normally after every 5 years (or whenever the h/w warranty expires), the whole set of hardwares need to be recycled, which means, even the data present in the node needs to be migrated.
-> In this particular case, we have a planned period for migration.

(As discussed in the container strategy meetings this week)
We also have an interest in migrating bricks within the cluster for load-balancing reasons (capacity, performance, or other resource usage). In these cases, just like above, the existing brick is still good/usable, so it should be kept to ensure data resiliency while the new copy is being brought up to date.

While this doesn't add much (anything?) in technical requirements over Amar's item, it implies much more frequent usage of the functionality. With this frequent usage, snapshots would need to be migrated also. In a once per n years, we could get away w/ skipping the snaps.

**Comment by atinmu** [comment]
@prashanthpai Can we pick this up for GCS-sprint1 ?

**Comment by prashanthpai** [comment]
> @prashanthpai Can we pick this up for GCS-sprint1 ?

Deferring it as it may need more discussion if we target to improve it. And it likely has dependencies on remove brick, self heal and rebalance.

**Comment by aravindavk** [comment]
## MVP0: 

- If source brick is auto provisioned, target brick is not required in API request. For example,

    curl -XPOST <url>/volumes/{volname}/replace -d '{"source-peerid": "8749ba5a-b9f7-4e63-b08f-d6d546cccc53", "source-brick-path": "/exports/bricks/gv1/brick2/brick"}'

    - Based on the bricks allocation strategy of that volume, choose a node and device which can be used for creating new brick. (New node should not be in same zone as other bricks of the volume and other filters which were used during volume create)
    - Create thinpool and lv on the selected node and prepare brick mount
    - Stop glusterfsd of old brick if running
    - Remove glusterfsd daemon entry from daemon mgmt store
    - Replace the brick details in Volinfo and regenerate volfiles(Retain the brick position same as old brick)
    - Start the new brick process(Depending on the volume state)


- If source brick is manually provisioned, accept source and target.
    - Validate target brick
    - Stop glusterfsd of old brick if running
    - Remove glusterfsd daemon entry from daemon mgmt store
    - Replace the brick details in Volinfo and regenerate volfiles(Retain the brick position same as old brick)
    - Start the new brick process(Depending on the volume state)
 

@amarts @JohnStrunk @atinmu @prashanthpai @raghavendra-talur @kshlm @ShyamsundarR  Please check if these steps looks good. Feel free to add if I missed anything

**Comment by amarts** [comment]
Update from another discussion:

Would be great to consider below asks along with replace brick
1) We should be able to add before remove when doing a replace. Good because:
1a) We maintain resiliency to failure during move
1b) Failure or abort of the replace operation can be handled by just deleting the new brick and returning to old graph.
2) GD2 should be able to auto-replace if a node is down for an extended period. (future GD2 plugin that triggers the API of replace-brick)

@JohnStrunk
