### ISSUE TITLE
Add support to set arbitrary metadata on peer and volume object 

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#482]
...glusterd2 shall not interpret these metadata (K/V pairs) set by users (or programs) in anyway. Glusterd2 may however impose a size restriction.

This additional metadata can be set and consumed by tools that needs to tag peers for say rack awareness or in future tag volumes or even devices with a "class".

A pre-requisite for implementing this is providing option to edit peer object after creation. Refer issue #462 and #356

**Comment by rishubhjain** [comment]
@prashanthpai So one of the additional metadata can be group/zone the peer belongs to which can be saved along with Peer information and this metadata can be used by  the heketi plugin (after integration). Does this sound right?

**Comment by prashanthpai** [comment]
@rishubhjain Yes. Correct. Glusterd2 will not interpret these metadata in any way. They are key-value pairs.

**Comment by rishubhjain** [comment]
@atinmu @prashanthpai @kmlmhnn I am working on this issue, User will be able to group the nodes for stack awareness by providing the group number while attaching peer . This is partial implementation of this issue, but it will be used for dynamic volume provisioning.

Example post request:

{
    "addresses": [
        "host1name1",
        "host1name2"
    ],
    "group": "1"
}

**Comment by prashanthpai** [comment]
@rishubhjain Consider not introducing a new member to `Peer` struct just for group. You can create `Metadata` as the member which can contain many key value pairs with "group" being one of them,

**Comment by amarts** [comment]
After this is available:

*  We need a mechanism to add further logic in volume create based on these tags (may be like hooks, provide filters? (or consume it in IVP when available).
* Similar for volume tags, it should be available for plugins, so they can decide further options. For example, I will consume the volumes which are set with a tag 'Block' as the backend volume for block files, and nothing else. (ie, block cli itself fails if we provide other volume) and things like this.

None of the core functionality should depend on these tags, but the higher level functionalities can depend on it.

**Comment by prashanthpai** [comment]
Listing (filtering) based on some key and/or value has been done for volume listing (https://github.com/gluster/glusterd2/issues/462) by @vpandey-RH 

@rishubhjain or @vpandey-RH Any takers to do the same for peer listing as well ?

**Comment by vpandey-RH** [comment]
@prashanthpai  I can start working on this if @rishubhjain  is not looking to work on this.

**Comment by rishubhjain** [comment]
@vpandey-RH Go ahead

**Comment by prashanthpai** [comment]
Arbitrary metadata can now be set on both peer and volume object.

**Comment by prashanthpai** [comment]
@vpandey-RH++ @rishubhjain++
