### ISSUE TITLE
Listen on socket file in /var/run/gluster for incoming RPCs

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#491]
Self heal is one of the daemons which communicates with glusterd2 over the socket file.

**Comment by aravindavk** [comment]
I think `glfsheal` is communicating with glusterd using RPC. If we can get more details about this tool, we can check the possibility of converting this as an Glusterd2 API itself.

    Usage: glfsheal <VOLNAME> [bigger-file <FILE> | latest-mtime <FILE> | source-brick  <HOSTNAME:BRICKNAME> [<FILE>] | split-brain-info | info-summary]

**Comment by itisravi** [comment]
@aravindavk glfsheal is a gfapi based program. IIRC, @vpandey-RH was saying that glfs_init() itself was failing in glfs-heal.c. So whatever changes needs to be done in gd2 for gfapi based client programs (for example https://github.com/gluster/glusterfs/tree/master/api/examples) to work will ensure that glfs-heal.c also works.

**Comment by prashanthpai** [comment]
Gd2 currently supports mounting volumes over FUSE and libgfapi. Libgfapi clients can talk to glusterd2 and get volfile over TCP ( port 24007) or over Unix domain socket. Self heal uses the latter.

`glfs-heal.c`:

```c
#define DEFAULT_GLUSTERD_SOCKFILE             DATADIR "/run/glusterd.socket"
...
        ret = glfs_set_volfile_server (fs, "unix", DEFAULT_GLUSTERD_SOCKFILE, 0);
        if (ret) {
                ret = -errno;
                gf_asprintf (&op_errstr, "Setting the volfile server failed, "
                             "%s", strerror (errno));
                goto out;
        }
```

Glusterd2 has to listen and serve on `/var/run/glusterd.socket`
