### ISSUE TITLE
Implement volume get functionality

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#496]
With current gluster cli one can use `gluster volume get <volname|all> <option|all> to fetch out specific option details for volume(s). The same needs to be implemented in GlusterD2 as well.

**Comment by kshlm** [comment]
We should ensure that `volume get all` filters out options for xlators that are not present in the volume. Similarly, we should ensure that `volume get <options>` only allows options for xlators present in the volume. Volume set should also ensure the same.

**Comment by aravindavk** [comment]
API can return all the options with following fields, CLI or consumer can filter while displaying.

    [
        {
            "name": OPTION_NAME,
            "value": OPTION_VALUE,
            "configurable": true|false,
            "modified": true|false,
            "advanced": true|false,
            "default_value": DEFAULT_VALUE   # Only if modified == true
        },..
    ]

**Comment by samikshan** [comment]
@kshlm @aravindavk

2 questions:
1. Should the API return all options for volumes and CLI handle specific volume option requests by filtering out from the API response? Since we might have a lot of options per volume we might want the API to be able to handle requests for specific option(s) per volume. What do you think?

2. What is a good way to filter out options for xlators that are not present in a volume? I checked the volgen2 code it isn't immediately clear to me how to do this filtering.

**Comment by aravindavk** [comment]
>    Should the API return all options for volumes and CLI handle specific volume option requests by filtering out from the API response? Since we might have a lot of options per volume we might want the API to be able to handle requests for specific option(s) per volume. What do you think?

API can accept option name and return only that option.

    GET /volumes/<volname>/options
    GET /volumes/<volname>/options?name=<opt-name1>&name=<opt-name2>...

>    What is a good way to filter out options for xlators that are not present in a volume? 

No good way right now. We should maintain list of supported xlators for each volume types. Volinfo should have list of features enabled for that volume(This can be done during enable/disable of a feature. For example: `quota enable`).

> I checked the volgen2 code and it isn't immediately clear to me how to do this filtering.

Generated volfile will have the content even though a feature is not enabled. Each Xlator will decide it to be active or not based on option inside that. For example,

    volume gv1-changelog
        type features/changelog
        option changelog on

Once we start maintaining list of enabled features for a Volume then we can optimize Volfile generation, Volume get functionality. For now we can return all Options.

**Comment by atinmu** [comment]
@prashanthpai Can you please take this to the closure in GCS-Sprint1? If you agree, please put it against the milestone.

**Comment by prashanthpai** [comment]
@atinmu Actually, most of the work on this one is being done by @samikshan and @Madhu-1

**Comment by Madhu-1** [comment]
@atinmu we can close this as well. #861  is merged now.
