### ISSUE TITLE
validator function of volume options

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#501]
There are certain volume level options maintained in volume map entry table in glusterd1 where specific validation functions are used which validates certain voinfo related parameters. With GD2, as we move towards maintaining all the options only in xlator files, how do we deal such situations where validation has to be carried in glusterd2 code path?

**Comment by atinmu** [comment]
@kshlm @aravindavk @prashanthpai What are the thoughts to tackle this problem?

**Comment by aravindavk** [comment]
Two ways,

We can have a map of config name and validator func, which can be called during volume_set. But glusterd code will have info about config name, if name changes gd2 code need to be changed

Other way is to provide more Validation func names which can be specified in xlators

GF_OPT_VALIDATE_VOLUME_STARTED, GF_OPT_VALIDATE_VOLUME_STOPPED etc

**Comment by kmlmhnn** [comment]
This is the approach suggested by @aravindavk and @prashanthpai :
Each xlator has an associated validation function. 
All the validation functions should match a particular signature and these functions are registered when the xlators are loaded.
The validation is performed whenever a volume create or volume option set request is received.

**Comment by aravindavk** [comment]
Some clarifications

> Each xlator has an associated validation function.

xlator can have optional validation function defined in Gd2 code and register with Gd2 using exposed validation function. (Example, `xlator.RegisterValidationFunc(XLATOR_ID, func)`)

This will internally maintained as map as `xlatorValidationFuncs  map[string]func`

During volume set, if custom function is defined, then that will be executed(Note: Reference of Volinfo should be sent to validation function)

> The validation is performed whenever a volume create or volume option set request is received.

Only during Volume Set.

**Comment by atinmu** [comment]
Closed through #530
