### ISSUE TITLE
Provide a way to tag internal xlator options

### ISSUE THREAD

**Issue by nbalacha** [gluster/glusterd2#502]
In GD1, we could keep users from setting options by not adding them to the GD1 volopt structures. This allowed xlators to have "internal" options which had to be explicitly passed via the command line to certain processes. With GD2, this behaviour will change (options will not be visible but can still be set if the user knows about them). We should have a flag which will prevent the option from being set from the CLI/Rest interface.

For example DHT has the options commit-hash, rebalance-cmd etc, which are only used when starting rebalance processes.

**Comment by nbalacha** [comment]
This sounds like it is already available via OPT_FLAG_SETTABLE. Is this correct? If yes, I will close this issue.

**Comment by aravindavk** [comment]
> This sounds like it is already available via OPT_FLAG_SETTABLE. Is this correct? If yes, I will close this issue.

Yes.

Also GD2 will not maintain any information about options like GD1. On GD2 start, it will read available options from *.so files directly(Including the Flags).

I think with the existing details, we can filter/group/validate the options without having copy of option details in GD2.
