### ISSUE TITLE
Fix TOCTOU races in rest handlers

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#510]
In REST handlers, there are TOCTOU (Time of check to time of use) races in code paths where we fetch something from store, do validations and then act on it. Something might have changed in between. Currently, locks are only held during the lifetime of the transaction. Locks need to be held outside of transactions too or the validations itself be a step (under locks) in the transaction.

Example:
```
1: volinfo = get_from_store()
2: do validation of request w.r.t volinfo
3. change volinfo based on request and store
```

The state of volinfo may have changed between step1 and step3 which makes the validation invalid.

Reported by @rafikc30

**Comment by kshlm** [comment]
2 ways to fix this.
Either,
1. Do request validation as a txn step. Or,
2. Lock outside txn and then validate request.

2 is easier to do, so I'd prefer we go that way.

**Comment by prashanthpai** [comment]
- [ ] Volume Create
- [ ] Volume Start
- [ ] Volume Stop
- [ ] Volume Delete
- [ ] Volume Set

**Comment by prashanthpai** [comment]
- [ ] Bitrot
- [ ] Georep
- [ ] Quota
