### ISSUE TITLE
Add support for bricks list without explicit subvols for Volume Create

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#521]
With the introduction of subvols, Volume Create request becomes lengthy for plain distribute Volumes and for Volumes with homogeneous sub volumes.

Volume Request API can also accept just list of bricks as before and split into sub volumes before storing in etcd as Volinfo.

For example, following request with list of bricks will be converted as list of subvols

    {
                "name": "testvol",
                "replica" : 2,
                "bricks": [
            	    "<uuid1>:/export/brick1/data",
            	    "<uuid2>:/export/brick2/data",
            	    "<uuid1>:/export/brick3/data",
            	    "<uuid2>:/export/brick4/data"
                ],
                "force": true
    }

Converted Volume request

    {
            "name": "testvol",
            "subvols": [
                {
                    "type": "replicate",
                    "bricks": [
                        {"nodeid": "<uuid1>", "path": "/export/brick1/data"},
                        {"nodeid": "<uuid2>", "path": "/export/brick2/data"}
                    ],
                    "replica": 2
                },
                {
                    "type": "replicate",
                    "bricks": [
                        {"nodeid": "<uuid1>", "path": "/export/brick3/data"},
                        {"nodeid": "<uuid2>", "path": "/export/brick4/data"}
                    ],
                    "replica": 2
                }
            ],
            "force": true
    }

**Comment by kshlm** [comment]
Why!!
I'd rather not support this. Let's leave the old format juggling to CLI. Anyone who uses to use the ReST API, should use the new format. There is no need to support any sort of backwards compatibility here, as any user of this API will be a new user.

**Comment by aravindavk** [comment]
> I'd rather not support this. Let's leave the old format juggling to CLI. Anyone who uses to use the ReST API, should use the new format. There is no need to support any sort of backwards compatibility here, as any user of this API will be a new user.

This is not for backward compatibility, added this for Convenience. API request format is repeatitive if  a Volume has only one subvolume or homogeneous subvolumes.

**Comment by prashanthpai** [comment]
When the overall directive is to move away from normal users (not power users) having to understand terminologies such as `bricks`, understanding `subvol` terminology is additional burden IMO. However, I'd still want users to be able to specify replica/redundancy sets clearly.

**Comment by atinmu** [comment]
I kind of agree with Aravinda. Having user to have an easier way to
construct the API request would add value from an user perspective.
Thoughts?

**Comment by aravindavk** [comment]
Not required now. CLI can handle API complexity as discussed. Closing this issue.
