### ISSUE TITLE
API endpoint for monitoring the current list of problems detected in the cluster

### ISSUE THREAD

**Issue by brainfunked** [gluster/glusterd2#538]
## API Endpoint for Health Monitoring

`To enable monitoring systems to track and report health of the gluster deployment, it is essential to have a single API endpoint from where the health of the cluster can be read.` While such an endpoint could be used to provide the health information for the whole cluster, I would propose an endpoint that provides just a list of the currently existing _alert conditions_ (`/alerts` perhaps?). This endpoint would be used in conjunction with the [events API](https://github.com/gluster/glusterd2/issues/418).

## Alert Conditions

These are stateful alerts for different components (volumes, bricks, processes, cluster quorum, peers etc.) of the cluster that have a lifecycle: they come into existence, change state and after varying amounts of time can cease to exist. Monitoring systems need to be able to report upon the entire lifecycle of such alerts to enable administrators to debug problems. Quoting from [tendrl's list of alerts](https://github.com/Tendrl/documentation/wiki/List-of-Alerts-and-Notifications-in-Tendrl), these are some of the alert conditions that tendrl currently reports:

- volume status (volume, cluster)
- volume state (volume, cluster)
- brick status (volume, host, cluster)
- peer status (cluster)
- rebalance status (volume, cluster)
- geo-replication status (cluster)
- quorum of volume lost (volume, cluster)
- quorum of volume regained (volume, cluster)
- svc  connected (cluster)
- svc disconnected (cluster)
- minimum number of bricks not up in EC subvolume (volume, cluster)
- minimum number of bricks up in  EC subvolume (volume, cluster)
- afr quorum met for subvolume (volume, cluster)
- afr quorum fail for subvolume (volume, cluster)
- afr subvolume up (volume, cluster)
- afr subvolume down (volume, cluster)

## Alert Conditions and Events

Alert conditions are not merely events. As mentioned, alert conditions are stateful and need to be tracked through their entire lifecycle by a monitoring system. The events API would be used to notify of changes to the state of the alerts. For example, for each of the alert conditions mentioned above would produce at least two events: exists, no longer exists. There could be additional state changes in between these two events.

`While the monitoring system does need to track all the changes to the alert conditions, gd2 itself doesn't need to.` It would be enough for gd2 to simply maintain the `/alerts` endpoint with the list of _currently existing_ alert conditions: essentially, the current list of problems that exist in the cluster, with a timestamp indicating when the particular problem came into existence. When a problem no longer exists, it can be removed from the list. By co-relating the timestamps in the events and on the alert conditions, a monitoring system would be able to generate the lifecycle for any alert condition.

`It is essential that all the alert conditions for the cluster be available under a single API endpoint.` It drastically increases the cost of monitoring a cluster should a monitoring system have to query multiple endpoints and parse their responses to generate such a list.

**Comment by atinmu** [comment]
I personally don't think maintaining separate endpoints for alerts is going to benefit us. From GD2 and storage management plane perspective what we'd need a mechanism to let others know about a change in the state of the existing configuration which the consumer(s) might be interested to know and for that event itself is good enough. Having a segregation between alerts and events at the GD2 layer doesn't make much sense until and unless you can explain the justification behind this requirements in a different way.

**Comment by atinmu** [comment]
If we have reached to a consensus on what GD2's goal and role is to w.r.t generating events, this issue can be closed (IMO).

@brainfunked any other thoughts, objections?

**Comment by aravindavk** [comment]
Closing this issue, we are tracking Events API here https://github.com/gluster/glusterd2/issues/418 and Metrics API here https://github.com/gluster/glusterd2/issues/483. Please add comments to one of these issues if anything is missing
