### ISSUE TITLE
Fix volume delete workflow

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#55]
deleting a volume throws an error saying volume not found even if the volume exists

**Comment by lpabon** [comment]
I suggest writing unit tests to minimize errors.

**Comment by atinmu** [comment]
@lpabon : Agreed. We'll definitely have unit tests for these work flows. Honestly I started with volume create test (volume/volume_test.go) and it worked locally but the problem is to perform setxattr/getxattr we need root privilege and then the tests started failing in wercker build system as it has non root privilege. We need to find out a way how we can mock out these things, any idea here?

**Comment by kshlm** [comment]
@lpabon Any ideas about a mocking toolkit?

**Comment by atinmu** [comment]
@kshlm : I just got an idea from @lpabon on how to mock it. Will shoot a patch pretty soon.
