### ISSUE TITLE
Update other routes with information required for API doc generation

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#584]
The generated [REST API doc](https://github.com/gluster/glusterd2/blob/master/doc/endpoints.md) currently contains request and response structs for core APIs and not for other plugins (like geo-rep, quota etc)

Plugin contributors can refer to [this example](https://github.com/gluster/glusterd2/blob/master/glusterd2/commands/volumes/commands.go#L22-L23) and [add fields](https://github.com/gluster/glusterd2/blob/master/glusterd2/servers/rest/route/route.go#L11-L19) accordingly including request type, response type and description.

**Comment by harigowtham** [comment]
@prashanthpai sure. Will update quota.

**Comment by atinmu** [comment]
Can we please cross check all the end points and keep the API doc up to date?

@rishubhjain @Madhu-1 can one of you take this up please?

**Comment by Madhu-1** [comment]
@atinmu  sure , I will look into it

**Comment by aravindavk** [comment]
Closing this issue since all available apis are included in the documentation.
