### ISSUE TITLE
GlusterD2 fails to start with 4.0.0rc1 Fedora 27 packages

### ISSUE THREAD

**Issue by kshlm** [gluster/glusterd2#588]
I built rc1packages for GD2 in my [copr][1] to test against Gluster-4.0.0rc1 packages. I'm using the packages for Fedora 27 available from [d.g.o][2].

GD2 fails to load the server xlator against this build of glusterfs. The full error log is

```
FATA[2018-02-28 15:02:53.345686] Failed to load xlator options                 error="dlopen(/usr/lib64/glusterfs/4.0.0rc1/xlator/protocol/server.so) failed; dlerror = /usr/lib64/glusterfs/4.0.0rc1/xlator/protocol/server.so: undefined symbol: glusterfs_mgmt_pmap_signout" source="[main.go:79:main.main]"
```

It may be an issue with the glusterfs rpms themselves, as a manually and externally built GD2 also fails with the same error. I'm not yet 100% sure if this is the case.

[1]: https://copr.fedorainfracloud.org/coprs/kshlm/glusterd2/
[2]: https://download.gluster.org/pub/gluster/glusterfs/qa-releases/4.0rc1/Fedora/fedora-27/x86_64/

**Comment by kshlm** [comment]
@prashanthpai Is this error message familiar to you?

**Comment by prashanthpai** [comment]
I had a quick glance and it looked familiar. There's some context about the error in comments of this patch: http://review.gluster.org/#/c/19163/

**Comment by prashanthpai** [comment]
Basically server.so needs `glusterfs_mgmt_pmap_signout` which is in glusterfsd binary and server.so doesn't (and shouldn't) explicitly link against it. The solution is to move it out pmap functionalities to it's own shared library or move it to say libglusterfs and have server.so link against that library.

**Comment by prashanthpai** [comment]
The fix in glusterfs source was merged into [master](https://review.gluster.org/19664) and [4.0 release](https://review.gluster.org/#/c/19675/) branch.
