### ISSUE TITLE
Failed to start GlusterD2

### ISSUE THREAD

**Issue by rishubhjain** [gluster/glusterd2#598]
I am getting an error https://pastebin.com/Y7NBAKpC, when I try to start the glusterd service after updating my code (syncing up with master), This issue is mostly because of changes introduces in https://github.com/gluster/glusterd2/pull/59. Are there any changes in settings that are supposed to be made before stariting the service after these changes?

**Comment by rishubhjain** [comment]
@kshlm Please check

**Comment by kshlm** [comment]
The trace suggests that GD2 crashes with an invalid access when trying to load xlator options. The xlator option struct has been updated recently to conform with the GlusterFS master branch.

Update your glusterfs install to the latest master branch and try again.

**Comment by rishubhjain** [comment]
After updating glusterfs the issue gets resolved.
