### ISSUE TITLE
Group options if GD2

### ISSUE THREAD

**Issue by poornimag** [gluster/glusterd2#614]
With GD1 there was a facility for setting group options. These group options are files in glusterfs code repo, which will be shipped in rpm and will be installed in /var/lib/glusterd/groups/
Eg:
$ cat extras/group-metadata-cache 
features.cache-invalidation=on
features.cache-invalidation-timeout=600
performance.stat-prefetch=on
performance.cache-invalidation=on
performance.md-cache-timeout=600
network.inode-lru-limit=50000

$ gluster vol set <VOLNAME> group metadata-cache

We need the group option support in gd2 as well. It need not be in /var/lib/glusterd/groups and not have the same format of the group file, in that case migration from ggd1 to gd2 should handle this. The following are the requirements:
1. Should be able to ship the group options(either file or..)
2. Admin should be able to create their own group options.
3. There should be a way to unset the group option:
   $ gluster vol reset <VOLNAME> group metadata-cache  #or something similar
    On executing this, the options in the group metadata-cache should be reset to their default values.
4. There should be a way list the available groups
   $ gluster vol <VOLNAME> group list [info]  #or something similar
   Should have an option to list the text info about all the group options
    Eg: gluster vol patchy group list info
          metadata-cache - Enable this group option for caching the metadata on the client side..
          The info text should be part of the group (file) itself. 
5. There should be a way to show the info of a given group
    $ gluster vol <VOLNAME> group <group-name> info  #or something similar

It would be good to have this by 4.1, if there is absolutely no bandwidth, please let us know, we can try it with assistance from one of the developers.

**Comment by atinmu** [comment]
@poornimag AFAIU, this functionality is already in place in current GD2. I remember Kamal has already implemented it and here it is https://github.com/gluster/glusterd2/issues/454 . Please cross check and close this issue if you're happy with the current implementation.

**Comment by poornimag** [comment]
@atinmu but apparently the group options are hardcoded in the code?

**Comment by aravindavk** [comment]
@poornimag It is already available, You can register a group using `POST /v1//volumes/options-group`, Get using `GET /v1//volumes/options-group` and delete a group using `DELETE /v1/volumes/options-group`. (Ref: `$SRC/glusterd2/commands/volumes/`).

I don't see Volume Set API which understands Group. @kmlmhnn please confirm if that is available.

**Comment by amarts** [comment]
the primary goal is to support the group profile as it exists today.

But I am suggesting to have group profile list and group profile info in it. This is possible by having the format of the group file changed to json format, with a detailed description about the group itself in the file.

the template i suggest is something like below:

```
{ "name": "gluster-block",
   "options": [ { "key": "performance.io-cache",
                        "value": "off" },
                     { "key": "performance.io-cache",
                        "value": "off" },
                     ....
                   ],
  "description": "This profile is best suited for running 
'gluster-block' project on top of gluster volumes. These
options are found to be giving more performance and 
also provide best user experience on the product",
}
```
This way,  we don't depend on the file name, and the update group option request would make sure all the required fields are present.

Comments welcome.

**Comment by aravindavk** [comment]
Based on the comments above, following Changes required in our APIs

- [ ] Accept "Description" with Group Add API (`POST /volumes/options-group`)
- [ ] Add support to detect available groups JSON files in predefined path and register automatically on Glusterd2 start. With this feature, Groups can be customized during install/packaging.

**Comment by prashanthpai** [comment]
@aravindavk summed it up perfectly.

We must remove [hard-coded values](https://github.com/gluster/glusterd2/blob/master/glusterd2/commands/volumes/grouped-options.go#L8) from code.

I was curious on what should glusterd2 on picking up files from predefined paths: What if an user creates (or edits) a custom profile file and does it on one node ? Should glusterd2 use that through-out the cluster ?

**Comment by aravindavk** [comment]
> I was curious on what should glusterd2 on picking up files from predefined paths: What if a user creates (or edits) a custom profile file and does it on one node ? Should glusterd2 use that through-out the cluster ?

Very valid. I think we can limit this use case only for providing group options during Installation/packaging(Can't prevent technically, but we can skip this part in user documentation). Users will always create extra groups via API.

**Comment by atinmu** [comment]
@poornimag do you want to take this up and make the group profile story complete?

**Comment by poornimag** [comment]
@aravindavk i do not completely understand when you say "You can register a group using POST /v1//volumes/options-group, Get using GET /v1//volumes/options-group and delete a group using DELETE /v1/volumes/options-group. (Ref: $SRC/glusterd2/commands/volumes/)." 
What i see in the code is OptionGroupList, OptionGroupCreate, OptionGroupDelete, this means that the group can be created runtime? i.e. we can group a set of volume options and create a JSON file for it or so? What about shipping groups itself, as in we currently install a file with options in /var/lib/glusterd and it is necessary to be able to ship these groups as a part of rpms?

@atinmu Sure

**Comment by amarts** [comment]
Here is what I envisioned, I guess Aravinda/Ppai also are in same page I guess.

1. We can ship some groups with the code, they will be defined as json, but are added automatically when the program starts. Technically, it can also follow same code path as 2 below, but done during init.
2. We also can add a group in run-time, using POST request, and this needs a json flie/format as the input.
3. Group list, group info, and group reset, and group delete  will all work out of memory (or can be based on etcd etc, which can be technical details).
4. If user wants to '**update**' a group, internally we can treat it as group delete, and group create, or ask user to  do the same if you want to keep the number of routes simple.

**Comment by poornimag** [comment]
I think the only thing that remains is to put the volume options to a file, instead of keeping it in gd2 codebase. Is there anything else?
For this, we need to handle the scenarios where the file is different on each node(due to different versions) and if we want to store it in etcd as well. Any thoughts on how to handle this scenario?

**Comment by atinmu** [comment]
@poornimag Do we have all group profiles which exist today in coverage?

**Comment by aravindavk** [comment]
> If users want a custom profile, they can use the REST API to add them.
> If GlusterFS developers need to add/edit a "officially supported" profile, it can be in the code and hence will end up in the glusterd2 binary available over normal release channels.

I think we need an option to customize each deployments, we can have json files in codebase, which can be replaced/customized during build. 

@amarts thoughts?

**Comment by poornimag** [comment]
@atinmu yes AFAIK all the group options are there, along with additional ones, 
https://github.com/gluster/glusterd2/blob/ff117730aae14c3dd2cb896dc1bb8f46cf9ff00a/glusterd2/commands/volumes/grouped-options.go

**Comment by atinmu** [comment]
Can this issue be closed?

**Comment by atinmu** [comment]
@poornimag Do we have an infra in place by which we can reset a group profile completely? If not, this was an ask from couple of users in GD1 and good to implement. Can you please confirm?

**Comment by atinmu** [comment]
@prashanthpai As discussed, did you get a chance to look at this? We can track that as a separate issue and close this one as well if this enhancement is not in place.

**Comment by prashanthpai** [comment]
> @prashanthpai As discussed, did you get a chance to look at this? We can track that as a separate issue and close this one as well if this enhancement is not in place.

That's not present. I'll file a separate issue for it to be tracked.
