### ISSUE TITLE
Spurious failures of e2e tests

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#617]
These tests fail often (1 out of 5 times) in my VM:

```sh
--- FAIL: TestAddRemovePeer (16.15s)
        Error Trace:    peer_ops_test.go:40
	Error:      	Expected nil, but got: &url.Error{Op:"Post", URL:"http://127.0.0.1:24007/v1/peers", Err:(*http.httpError)(0x8dd950)}
	Test:       	TestAddRemovePeer
=== RUN   TestRESTAPIAuth
--- PASS: TestRESTAPIAuth (2.04s)
=== RUN   TestRestart
--- FAIL: TestRestart (5.11s)
        Error Trace:    restart_test.go:51
	Error:      	Expected nil, but got: &errors.errorString{s:"os: process already finished"}
	Test:       	TestRestart
```

Especially **TestAddRemovePeer**

**Comment by prashanthpai** [comment]
```
08:11:01 --- FAIL: TestGeorepCreateDelete (2.82s)
08:11:01 	assertions.go:247: 
                          
	Error Trace:	georep_test.go:17
08:11:01 		
	Error:      	Expected nil, but got: &errors.errorString{s:"timeout: could not query rest server"}
08:11:01 		
	Test:       	TestGeorepCreateDelete
```

**Comment by prashanthpai** [comment]
```log
09:30:26     --- FAIL: TestBitrot/Replica-volume (0.08s)
09:30:26     	assertions.go:247: 
                          
	Error Trace:	bitrot_test.go:131
09:30:26     		
	            	
			bitrot_test.go:73
09:30:26     		
	Error:      	Expected nil, but got: &restclient.UnexpectedStatusError{msg:"Unexpected Status", expected:200, actual:500, resp:"Transaction step vol-start.StartBricks failed on peer 95e978b3-a8a9-4609-8f61-2a3313dfc27f with error: exit status 1\nTransaction step vol-start.StartBricks failed on peer a7f9b66a-0ca9-4581-8f85-00c2f9734206 with error: exit status 1\n"}
09:30:26     		
```

**Comment by prashanthpai** [comment]
I've seen two types of spurious failures:

* The peer add /remove failures should go away once elastic etcd issues are fixed OR when we move e2e tests to external etcd. Related issues: https://github.com/gluster/glusterd2/issues/714 https://github.com/gluster/glusterd2/issues/332 https://github.com/gluster/glusterd2/issues/930
* Failure to start brick because of race in pmap port allocation. This may go away if we fix https://github.com/gluster/glusterd2/issues/924

**Comment by prashanthpai** [comment]
The last few fixes have improved stability of `e2e` tests but `TestBitrot/Replica-volume` is still failing often.

**Comment by phlogistonjohn** [comment]
@Madhu-1 For the first message, if you convert the bytes to characters you get `losetup: /tmp/gd2_func_test/TestSnapshot/bricks/1/patchy_snap_loop: failed to set up loop device: Permission denied'

The general unhelpful output of the process exit errors makes me wonder if the tests could benefit from something that converts these into something readable automatically (Probably print the error code and first N characters of the error text.

**Comment by prashanthpai** [comment]
I'm going to take a stab to look into `TestBitrot/Replica-volume` failure as that is the only test causing us to retrigger CI test runs. Fixing it is also a pre-requisite for us to run glusterd2 tests for patches sent to glusterfs repo.

@phlogistonjohn Do you intend to resume work on https://github.com/gluster/glusterd2/issues/659 anytime soon ?

**Comment by Madhu-1** [comment]
@prashanthpai  earlier I used to run test cases with embedded ETCD, as per recent changes in #1072
I started using external ETCD.

 all test cases are failing,  what could be the cause for this?

```
[root@glusterd2]# make functest
dep package is available
gometalinter package is available

=== RUN   TestBitrot
--- FAIL: TestBitrot (3.75s)
	require.go:765: 
			Error Trace:	bitrot_test.go:18
			Error:      	Expected nil, but got: &errors.errorString{s:"timeout: could not query rest server"}
			Test:       	TestBitrot
=== RUN   TestGeorepCreateDelete
--- FAIL: TestGeorepCreateDelete (3.75s)
	require.go:765: 
			Error Trace:	georep_test.go:17
			Error:      	Expected nil, but got: &errors.errorString{s:"timeout: could not query rest server"}
			Test:       	TestGeorepCreateDelete
=== RUN   TestSelfHeal
--- FAIL: TestSelfHeal (3.76s)
	require.go:765: 
			Error Trace:	glustershd_test.go:16
			Error:      	Expected nil, but got: &errors.errorString{s:"timeout: could not query rest server"}
			Test:       	TestSelfHeal
=== RUN   TestAddRemovePeer
--- FAIL: TestAddRemovePeer (4.31s)
	require.go:765: 
			Error Trace:	peer_ops_test.go:20
			Error:      	Expected nil, but got: &errors.errorString{s:"timeout: could not query rest server"}
			Test:       	TestAddRemovePeer
=== RUN   TestRESTAPIAuth
--- FAIL: TestRESTAPIAuth (3.76s)
	require.go:794: 
			Error Trace:	restapi_auth_test.go:16
			Error:      	Received unexpected error:
			            	timeout: could not query rest server
			Test:       	TestRESTAPIAuth
=== RUN   TestRestart
```

**Comment by Madhu-1** [comment]
I had an issue with glusterfs code, after updating the glusterfs code seems like test cases are getting passed.

**Comment by prashanthpai** [comment]
This blanket issue have been addressed over multiple PRs. I don't see spurious failures anymore on centos CI. I'll open a dedicated issue for `TestBitrot/Replica-volume` is I see it fail again. Have filed separate issues for each failures on gd2 smoke tests on gluster infra.
