### ISSUE TITLE
PID file support

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#627]
PID file support is required when multiple glusterd2 services run in the same node for testing. pidfile makes it easy to signal/stop the running Glusterd2 service.

Example,

    glusterd2 --pidfile=/var/run/gluster/glusterd2.pid

**Comment by prashanthpai** [comment]
@aravindavk We can put UUID in there and all of them can co-exist.

`/var/run/gluster/glusterd2-<uuid>.pid`
