### ISSUE TITLE
Consider removing logging from glustercli

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#629]
Currently, glustercli creates and logs to a file named `glustercli.log` in current working directory. All errors/info/warnings can be printed to stdout and the verbosity of printing can be controlled via a command line option.

**Comment by prashanthpai** [comment]
> @prashanthpai Are we sure we want to do that? what happen when an user sees an issue an report back with all the log files? Would we be able to any obvious issues at the cli end?

There's barely any processing at all on the CLI side. Things that would've been in the log will be in stdout instead. It is uncommon for similar tools to log. For example `etcdctl` and `heketi-cli` do not log. Further, there may not permission to create `glustercli.log` in places where the CLI tool is run. Currently it creates the file in $PWD.

**Comment by aravindavk** [comment]
Looks like both @rishubhjain and @Madhu-1 are working on this same issue

https://github.com/gluster/glusterd2/pull/644 and https://github.com/gluster/glusterd2/pull/693

Please assign the issue before starting the work on the issue to avoid the conflict.

**Comment by prashanthpai** [comment]
#693 got merged and it removes logging to a file.
