### ISSUE TITLE
Behaviour of `omitempty` in response structs for non-golang clients

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#654]
The `encoding/json` package in golang supports `omitempty' as a struct tag.

From documentation:
**The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any empty array, slice, map, or string.**

This is very useful in REST API's request structs. It brings clarity and convenience. 

When used in REST API's response structs and the clients are also written in golang (import response structs from `api` package), things will work as expected.

However, what about json decoders of other languages ? Does absence of a particular field (because it was empty) in JSON response cause failure in unmarshalling ?

**Comment by rishubhjain** [comment]
For python we can add default values to avoid the key not found error while unmarshalling the response, but for other languages we will have to check whether they handle such scenarios or not. In case there are any omitempty fields in response structs then we should mention in the document about its behaviour.

**Comment by aravindavk** [comment]
Is `omitempty` useful in request struct? In Go, we can initialize structure without initializing all fields. How is using `omitempty` different from that feature?

    package main

    import (
	    "fmt"
	    "encoding/json"
    )

    type AA struct {
        One string `json:"one"`
        Two int    `json:"two,omitempty"`
        Three bool `json:"three,omitempty"`
    }

    func main() {
            var data AA
            err := json.Unmarshal([]byte(`{"one": "ONE"}`), &data)
            fmt.Println(data.One, data.Two, data.Three, err)
    }

I think "omitempty" is more useful in response struct. If we want to hide some field in JSON output then we can use "-" as json field name(Ex: Password) 

    type User struct {
        Username string `json:"username"`
        Password string  `json:"-"`
    }

**Comment by prashanthpai** [comment]
> Is omitempty useful in request struct? In Go, we can initialize structure without initializing all fields. 

You're right. However, `omitempty` currently serves as a really crude way of [documenting the API](https://godoc.org/github.com/gluster/glusterd2/pkg/api#VolCreateReq) to indicate to API users that fields with `omitempty` are optional.

**Comment by rishubhjain** [comment]
> You're right. However, omitempty currently serves as a really crude way of documenting the API to 
    indicate to API users that fields with omitempty are optional.

I think we should explicitly mention in the API document that which all fields are optional, both for response as well as request.
