### ISSUE TITLE
Provision to allow plugins to register callbacks for volume set operation

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#664]
Plugins should able to execute some action when user sets a set of specific volume options.

**Comment by aravindavk** [comment]
+1

On all Volume nodes or on all Peer nodes?

**Comment by prashanthpai** [comment]
> On all Volume nodes or on all Peer nodes?

For now I plan to limit this to only volume nodes.

**Comment by prashanthpai** [comment]
I'll base fixing this on top of fix for https://github.com/gluster/glusterd2/issues/665
