### ISSUE TITLE
Make glusterd2 binaries from latest master as nightly job

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#670]
We do not have frequent releases and our master branch moves fast. Currently, master is almost always more stable that an old released version of glusterd2.

It's a pain for non-developers to set up entire Go environment to just test/use glusterd2. Non-developers (users, testers) just have to download and run the binaries.

It's necessary to have nightly job to build binaries from master or at least make [build artefacts](https://wiki.centos.org/QaWiki/CI/GettingStarted#head-a46ee49e8818ef9b50225c4e9d429f7a079758d2) available on Centos CI.

**Comment by atinmu** [comment]
@kshlm Can you please get this done asap so that QE can start picking up the builds from nightly and continue with the testing?

**Comment by shirshendu** [comment]
This will also be very helpful to the RHGS-WA team, to be able to consistently work with an up-to-date glusterd2 build.

**Comment by r0h4n** [comment]
+1 on master@nightly  builds.  Any help required with setting this up @prashanthpai @kshlm  ?

**Comment by prashanthpai** [comment]
@r0h4n I believe @kshlm is already on it. He's sent a [PR](https://github.com/gluster/glusterd2/pull/775) which has a script to generate the builds. I guess it's only a matter of how the build can be made available.

**Comment by atinmu** [comment]
Anything pending here @kshlm ?

**Comment by kshlm** [comment]
Nightly RPMs are being built for EL7 at [centos-ci][1]. More information on how to use them can be found in the [nightly builds][2] wiki entry.

[1]: https://ci.centos.org/view/Gluster/job/gluster_gd2-nightly-rpms/
[2]: https://github.com/gluster/glusterd2/wiki/Nightly-Builds
