### ISSUE TITLE
Incorrect peer status Title's

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#676]
**Below are the incorrect Titles in peer status**

1. Instead of "UUID" Title given like "ID"
2. Instead of "HOST NAME" Title given like "NAME"
3. No Space between "PEERADDRESSES"

**Peer status output**:
+--------------------------------------+-----------------------------------+--------------------+
|                  ID                  |               NAME                |   PEERADDRESSES    |
+--------------------------------------+-----------------------------------+--------------------+
| 3ad52256-3d40-4097-9d73-04c4ee262010 | dhcp35-52.lab.eng.blr.redhat.com  | 10.70.35.52:24008  |
| d38c5856-a620-45f4-a09f-2113cdaec3c4 | dhcp35-79.lab.eng.blr.redhat.com  | 10.70.35.79:24008  |
| f91e6b4f-52ce-4264-8f19-55f58c6f0669 | dhcp35-137.lab.eng.blr.redhat.com | 10.70.35.137:24008 |
+--------------------------------------+-----------------------------------+--------------------+

**Comment by prashanthpai** [comment]
> Instead of "UUID" Title given like "ID"

UUID is a data type and an implementation detail, `ID` is logical field that describes the peer.

> Instead of "HOST NAME" Title given like "NAME"

This is also intended. Name defaults to host name of the system but should be changeable in future and settable by admin.

> No Space between "PEERADDRESSES"

That needs to be fixed.
