### ISSUE TITLE
Glustercli commands are failing with short forms of volume like vol

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#677]
Desc:
Glustercli commands are failing with short forms of volume like vol.

For Example:
./glustercli vol info

above command is failing with below error
Error:
Error: unknown command "vol" for "glustercli"

Did you mean this?
	pool
	volume

Run 'glustercli --help' for usage.
unknown command "vol" for "glustercli"

Did you mean this?
	pool
	volume

**Comment by prashanthpai** [comment]
We do not intend to support short forms. For user friendliness and convenience, there's bash completion. glustercli isn't meant to support everything the older one did exactly the way it was.
