### ISSUE TITLE
Peer detach failing with 3 node cluster

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#687]
Desc: 

Peer detach is failing with 3 node cluster with below  error
command:
./glustercli peer detach 10.70.35.52

Error:
Peer detach failed

Error: Unable to find Peer ID

**Comment by aravindavk** [comment]
Please update the output of `./glustercli peer status`

**Comment by rmadaka** [comment]
./glustercli peer status
+--------------------------------------+-----------------------------------+--------------------+
|                  ID                  |               NAME                |   PEERADDRESSES    |
+--------------------------------------+-----------------------------------+--------------------+
| 071a213c-917c-41ed-8fa0-885a4f13a431 | dhcp35-235.lab.eng.blr.redhat.com | 10.70.35.235:24008 |
| 20e2aa14-08e0-4433-b6f8-929758685b16 | dhcp35-52.lab.eng.blr.redhat.com  | 10.70.35.52:24008  |
| feb00dd2-1bd9-4b92-b70f-0b4bbb70b8ed | dhcp35-219.lab.eng.blr.redhat.com | 10.70.35.219:24008 |

**Comment by rishubhjain** [comment]
@rmadaka Is this still reproducible?, if yes, can you provide logs?

**Comment by rmadaka** [comment]
Currently we are using "glustercli peer remove <peerID>"  command, closing this issue
