### ISSUE TITLE
Some times replica-3 volume creation failing 

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#688]
Some times replica-3 volume creation failing, some time replica-3 volume creation success.

i have created brick directory manually under mount point on all 3 nodes.

Volume creation failing with below error:
Command:
./glustercli volume create vol8 replica 3 10.70.35.219:/bricks/brick0/vol8 10.70.35.235:/bricks/brick0/vol8 10.70.35.52:/bricks/brick0/vol8

Errors:

Volume creation failed

Error: Request failed with HTTP Status code 500
Brick path is under root partition

**Comment by atinmu** [comment]
@rmadaka When you file the issues, please point out to the glusterd2 logs to enable developers to take a look at it to find out immediate pointers.

**Comment by rmadaka** [comment]
Pasted logs here:

INFO[2018-04-24 18:50:48.240022] ::1 - - [24/Apr/2018:18:50:48 +0530] "GET /v1/peers HTTP/1.1" 200 656  reqid=1ec4a643-521c-4228-901e-ae370a24c6ce
DEBU[2018-04-24 18:50:48.250645] Starting transaction                          reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[transaction.go:86:transaction.(*Txn).Do]" txnid=192f410c-faff-4530-a6a2-3cc30408d705
DEBU[2018-04-24 18:50:48.250771] running step function                         reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol1.Lock txnid=192f410c-faff-4530-a6a2-3cc30408d705
DEBU[2018-04-24 18:50:48.250839] attempting to lock                            key=locks/vol1 reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[lock.go:45:transaction.createLockStepFunc.func1]" txnid=192f410c-faff-4530-a6a2-3cc30408d705
DEBU[2018-04-24 18:50:48.253765] lock obtained                                 key=locks/vol1 reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[lock.go:49:transaction.createLockStepFunc.func1]" txnid=192f410c-faff-4530-a6a2-3cc30408d705
DEBU[2018-04-24 18:50:48.253828] running step function                         reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-create.CreateVolinfo txnid=192f410c-faff-4530-a6a2-3cc30408d705
DEBU[2018-04-24 18:50:48.262569] running step function                         reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-create.ValidateBricks txnid=192f410c-faff-4530-a6a2-3cc30408d705
DEBU[2018-04-24 18:50:48.263555] connected to remote                           remote="10.70.35.52:24008" remotepeer="c3583dfa-3805-4d1d-b434-594566a0af27(dhcp35-52.lab.eng.blr.redhat.com)" reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=192f410c-faff-4530-a6a2-3cc30408d705
DEBU[2018-04-24 18:50:48.264297] connected to remote                           remote="10.70.35.235:24008" remotepeer="eb2bf38a-e8ba-4b55-9226-16b1d2376805(dhcp35-235.lab.eng.blr.redhat.com)" reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=192f410c-faff-4530-a6a2-3cc30408d705
ERRO[2018-04-24 18:50:48.267768] TxnSvc.Runstep failed on peer                 error="Brick path is under root partition" remotepeer="eb2bf38a-e8ba-4b55-9226-16b1d2376805(dhcp35-235.lab.eng.blr.redhat.com)" reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[rpc-client.go:78:transaction.RunStepOn]" txnid=192f410c-faff-4530-a6a2-3cc30408d705
ERRO[2018-04-24 18:50:48.267832] Transaction failed, rolling back changes      error="Brick path is under root partition" reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[transaction.go:92:transaction.(*Txn).Do]" txnid=192f410c-faff-4530-a6a2-3cc30408d705
DEBU[2018-04-24 18:50:48.267860] running step function                         reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol1.Unlock txnid=192f410c-faff-4530-a6a2-3cc30408d705
DEBU[2018-04-24 18:50:48.267885] attempting to unlock                          key=locks/vol1 reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[lock.go:62:transaction.createLockStepFunc.func2]" txnid=192f410c-faff-4530-a6a2-3cc30408d705
DEBU[2018-04-24 18:50:48.269202] lock unlocked                                 key=locks/vol1 reqid=acc2c4a3-9d6e-4621-ba86-033823439471 source="[lock.go:65:transaction.createLockStepFunc.func2]" txnid=192f410c-faff-4530-a6a2-3cc30408d705
INFO[2018-04-24 18:50:48.271013] ::1 - - [24/Apr/2018:18:50:48 +0530] "POST /v1/volumes HTTP/1.1" 500 71  reqid=acc2c4a3-9d6e-4621-ba86-033823439471

**Comment by aravindavk** [comment]
> @rmadaka When you file the issues, please point out to the glusterd2 logs to enable developers to take a look at it to find out immediate pointers.

+1

Please provide the details which helps to debug faster. In this case are all the bricks are mounted? Please share the output of Mount command or df. I am suspecting one of the brick may be unmounted and brick directory is created in root partition itself.

**Comment by rmadaka** [comment]
i have seen some issue in my setup , it seems because of my machines issue, volume creation was failing ,  now i am able to create replica 3 volume successfully every time.
