### ISSUE TITLE
Volume Creation success for bricks under root directory

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#707]
Volume Creation success for bricks under root directory, It's not a consistent behavior but  i am hitting this issue most of the time. 
Note: Not all bricks should be under root path, Out of 3 node cluster one or two node bricks should be under root path.
Most of the time i am hitting this issue when one node brick under root path out of 3 node cluster.

Repro steps:

-> Create 3 node cluster (n1, n2, n3)
-> Create any one node(n1) brick under root path like /mnt/mnt1/vol1 (this is not mount point)
-> For remaining two nodes(n2, n3) create  actual bricks not under root path.
-> Then start creating replica 3 volume, most of the time it will be successful.

Note: 
-> If we create root brick directory manually ,  able to see proper brick pid.
-> If we don't create root brick directory manually,  brick pid  will be '0'.

Logs:
DEBU[2018-04-26 17:20:39.033635] RunStep request received                      reqid=d28a0f53-be5f-40d0-b0ec-4e6b098d45a5 source="[rpc-service.go:31:transaction.(*txnSvc).RunStep]" stepfunc=vol-create.ValidateBricks txnid=865a7d5b-ee49-4f6c-8db9-71437ceecbfd
DEBU[2018-04-26 17:20:39.033828] running step                                  reqid=d28a0f53-be5f-40d0-b0ec-4e6b098d45a5 source="[rpc-service.go:39:transaction.(*txnSvc).RunStep]" stepfunc=vol-create.ValidateBricks txnid=865a7d5b-ee49-4f6c-8db9-71437ceecbfd
DEBU[2018-04-26 17:20:39.038625] RunStep request received                      reqid=d28a0f53-be5f-40d0-b0ec-4e6b098d45a5 source="[rpc-service.go:31:transaction.(*txnSvc).RunStep]" stepfunc=vol-create.InitBricks txnid=865a7d5b-ee49-4f6c-8db9-71437ceecbfd
DEBU[2018-04-26 17:20:39.038732] running step                                  reqid=d28a0f53-be5f-40d0-b0ec-4e6b098d45a5 source="[rpc-service.go:39:transaction.(*txnSvc).RunStep]" stepfunc=vol-create.InitBricks txnid=865a7d5b-ee49-4f6c-8db9-71437ceecbfd

**Comment by prashanthpai** [comment]
This is a really major bug in the undo path:

```go
        done := make(chan error)
        defer close(done)

        for i, node = range nodes {
                go runStepFuncOnNode(name, c, node, done)
        }

        // TODO: Need to properly aggregate results
        var err error
        for i >= 0 {
                err = <-done
                i--
        }
        return err
```

The errors returned from different nodes are drained from the channel and are ignored except for the last response.

**Comment by prashanthpai** [comment]
cc @kshlm

**Comment by rmadaka** [comment]
With latest GD2 binaries , Volume creation not success for bricks under root directory.
