### ISSUE TITLE
Race in validation and actor function registration

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#713]
Plugins invoke `RegisterValidationFunc` and `RegisterOptionActor` from `init()` function of their respective packages. There's no deterministic order in which `init()` is invoked.

Very often, when invoking `init()`, xlators may not have been read or loaded yet. Loading xlators happens explicitly in `main()`

**Comment by aravindavk** [comment]
How about making `RegisterOptionActor` adds entry to a list instead of Xlator. Once Xlator loads, it can read this list and assign Actor to Xlator.
