### ISSUE TITLE
not able to start glusterd2

### ISSUE THREAD

**Issue by Madhu-1** [gluster/glusterd2#715]
Getting Data race while starting glusterd2

Logs:

/var/run/gluster/glusterd2.socket server=sunrpc source="[server.go:137:sunrpc.(*SunRPC).acceptLoop]" transport=unix
INFO[2018-05-02 14:37:29.220650] Started GlusterD ReST server                  ip:port="192.168.122.57:24007" source="[rest.go:91:rest.(*GDRest).Serve]"
INFO[2018-05-02 14:37:29.220835] started server                                address="192.168.122.57:24007" server=sunrpc source="[server.go:137:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
WARNING: DATA RACE
Write at 0x00c4207a0510 by goroutine 135:
  github.com/gluster/glusterd2/glusterd2/events.handleEvents()
      /home/vagrant/src/github.com/gluster/glusterd2/glusterd2/events/eventhandler.go:98 +0x112
  github.com/gluster/glusterd2/glusterd2/events.Register.func1()
      /home/vagrant/src/github.com/gluster/glusterd2/glusterd2/events/eventhandler.go:77 +0x4c

Previous read at 0x00c4207a0510 by goroutine 50:
  github.com/gluster/glusterd2/glusterd2/events.handleEvents.func1()
      /home/vagrant/src/github.com/gluster/glusterd2/glusterd2/events/eventhandler.go:102 +0x38

Goroutine 135 (running) created at:
  github.com/gluster/glusterd2/glusterd2/events.Register()
      /home/vagrant/src/github.com/gluster/glusterd2/glusterd2/events/eventhandler.go:76 +0xb3
  github.com/gluster/glusterd2/glusterd2/events.StartGlobal()
      /home/vagrant/src/github.com/gluster/glusterd2/glusterd2/events/global.go:100 +0x67
  github.com/gluster/glusterd2/glusterd2/events.Start()
      /home/vagrant/src/github.com/gluster/glusterd2/glusterd2/events/events.go:41 +0x2f
  main.main()
      /home/vagrant/src/github.com/gluster/glusterd2/glusterd2/main.go:105 +0x65b

Goroutine 50 (finished) created at:
  github.com/gluster/glusterd2/glusterd2/events.handleEvents()
      /home/vagrant/src/github.com/gluster/glusterd2/glusterd2/events/eventhandler.go:101 +0x1d5
  github.com/gluster/glusterd2/glusterd2/events.Register.func1()
      /home/vagrant/src/github.com/gluster/glusterd2/glusterd2/events/eventhandler.go:77 +0x4c

**Comment by prashanthpai** [comment]
@Madhu-1 

Can you describe reproducer steps for the same ?

**Comment by atinmu** [comment]
@Madhu-1 Is this still reproducible?

**Comment by Madhu-1** [comment]
@prashanthpai  I have built the glusterd2 with ```-race``` flag. 
@atinmu, I need to reproduce it again with new bits
