### ISSUE TITLE
Volume creation failing with host-names

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#724]
If we provide brick path with host-name  volume creation is failing with below error messages.
******************************************************************************************************************************
./glustercli volume create vol1 replica 3  dhcp35-52.lab.eng.blr.redhat.com:/bricks/brick0/vol1 dhcp35-219.lab.eng.blr.redhat.com:/bricks/brick0/vol1 dhcp35-235.lab.eng.blr.redhat.com:/bricks/brick0/vol1
Error getting brick UUIDs

Error: could not find UUIDs of bricks specified
*********************************************************************************************************************************

Note: If we provide brick path with ip or uuid volume creation is successfull like below.
f1d12b93-6114-41ca-862a-2a381ee0c782:/bricks/brick0/vol3
or
10.70.35.219:/bricks/brick0/vol2

Volume creation only failing for brick path with host names.

logs:
INFO[2018-05-03 17:18:01.843904] ::1 - - [03/May/2018:17:18:01 +0530] "GET /v1/peers HTTP/1.1" 200 656  reqid=d7cfb223-ad62-4427-a0a8-bef16dbf387c

**Comment by Madhu-1** [comment]
can you provide more details like 
1)glusterd2 configuration file
2)command used for peer add

**Comment by rmadaka** [comment]
conf.toml:
-------------
workdir = "/var/lib/gd2"
peeraddress = "10.70.35.219:24008"
clientaddress = ":24007"
etcdcurls = "http://10.70.35.219:2379"
etcdpurls = "http://10.70.35.219:2380"

peer add command:
--------------------------

./glustercli peer probe ip/hostname
