### ISSUE TITLE
failed to start geo-replication

### ISSUE THREAD

**Issue by Madhu-1** [gluster/glusterd2#733]
1)need to make gsyncd path configurable.

2)getting below error message when tried to start geo-replication 

fork/exec /usr/local/libexec/glusterfs/gsyncd: no such file or directory

need to have a better error message.

**Comment by aravindavk** [comment]
`gsyncd` is installed as part of `glusterfs` installation. Fix required in

-  Introduce `glusterfsd --print-libexecdir` similar to `glusterfsd --print-logdir`
- Handle error and change the error message.
- This can be optionally made configurable(Trying to avoid this since this is internal detail)

**Comment by Madhu-1** [comment]
Fixed in #1055
