### ISSUE TITLE
failed to delete geo-replication 

### ISSUE THREAD

**Issue by Madhu-1** [gluster/glusterd2#734]
failed to delete geo-replication, if the volume is already deleted

cli geo-replication delete testvol2  root@192.168.122.157::testvol -v 
ERRO[2018-05-07 13:49:23.852849] failed to get Volume details                  error="Request failed with HTTP Status code 404\nvolume not found" volume=testvol
Geo-replication Delete failed.

steps to reproduce 
1)create a volume
2)create a geo-replication
3)delete the volume
4)try to delete geo-replication

**Comment by aravindavk** [comment]
Known issue till we implement a pre hook mechanism for core actions. This issue is applicable for all plugins and also between two plugins. For example, in Glusterd1, Snapshot Create should fail if Geo-rep status is `Started`.

**Comment by aravindavk** [comment]
This issue is mentioned here https://github.com/gluster/glusterd2/issues/557#issuecomment-363334225

**Comment by Madhu-1** [comment]
closing this as we already have a tracker for this
