### ISSUE TITLE
Rename peer commands to be consistent

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#743]
Currently, there are following peer commands in CLI:

`probe <HOSTNAME>`
`detach <HOSTNAME or PeerID>`
`pool list`
`peer status`

This is a mess! We should converge to one common convention:

`peer attach` or `peer add`
`peer detach` or `peer remove`
`peer list`
`peer status`

**Comment by Madhu-1** [comment]
@prashanthpai  am working on this
