### ISSUE TITLE
add strict slashing to rest server

### ISSUE THREAD

**Issue by Madhu-1** [gluster/glusterd2#749]
```
curl http://ip:port/v1/volumes
```
 and 
```
curl http://ip:port/v1/volumes/ 
```
currently, we are getting 404 page not found if URL as a suffix slash

expected:
should give the same response

**Comment by prashanthpai** [comment]
In a way, I think it's a good thing that `/thing` works and `/thing/` doesn't. It's unforgiving but will help in maintaining some discipline and uniformity.

It is also reason about handling null/empty values. For example, if route pattern is `/thing/{id}`, then a request coming in on `/thing/` shouldn't be implicitly treated as id being null/empty.

I'll close this issue now. Feel free to reopen if there's a real use-case with some justification.
