### ISSUE TITLE
Volume creation is successfull but getting message like volume creation failed

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#750]
I have started creating 200 distributed  replica volumes on 6 node cluster through script.

after 130 volumes creation i am able to see message like below.

Volume creation failed

Error: Post http://localhost:24007/v1/volumes: net/http: timeout awaiting response headers

But actually volume creation is successfully .

Note: above scenario tried for 2 times.
           -> First time i have seen  this failed messages started from after 125 volumes creation.
           -> Second time i have seen this failed messages started from after 130 volumes creation

Logs provided for one volume:

DEBU[2018-05-11 17:56:44.583616] Starting transaction                          reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[transaction.go:86:transaction.(*Txn).Do]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.583660] running step function                         reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep200.Lock txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.583697] attempting to lock                            key=locks/rep200 reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[lock.go:45:transaction.createLockStepFunc.func1]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.585717] lock obtained                                 key=locks/rep200 reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[lock.go:49:transaction.createLockStepFunc.func1]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.585759] running step function                         reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-create.CreateVolinfo txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.600862] running step function                         reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-create.ValidateBricks txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.601922] connected to remote                           remote="10.70.35.8:24008" remotepeer="962636a1-4662-4892-ba24-9c76d9cbeb3a(dhcp35-8.lab.eng.blr.redhat.com)" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.602317] connected to remote                           remote="10.70.35.33:24008" remotepeer="1fefa0b7-8261-442f-b817-45484b3bfc75(dhcp35-33.lab.eng.blr.redhat.com)" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.602490] connected to remote                           remote="10.70.35.194:24008" remotepeer="dc2e1be2-7e53-4e3d-a477-1c55dd290f60(dhcp35-194.lab.eng.blr.redhat.com)" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.602855] connected to remote                           remote="10.70.35.52:24008" remotepeer="cf52689a-c81d-4248-bef4-24c800ab4b32(dhcp35-52.lab.eng.blr.redhat.com)" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.602999] connected to remote                           remote="10.70.35.235:24008" remotepeer="83695a05-a36b-4bb4-8ccc-e9f1be712422(dhcp35-235.lab.eng.blr.redhat.com)" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.604115] Brick validation failed                       brick=/bricks/brick0/rep200 error="Brick path is under root partition" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[common.go:152:volumes.validateBricks]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.607158] running step function                         reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-create.InitBricks txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.608300] connected to remote                           remote="10.70.35.194:24008" remotepeer="dc2e1be2-7e53-4e3d-a477-1c55dd290f60(dhcp35-194.lab.eng.blr.redhat.com)" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.609014] connected to remote                           remote="10.70.35.235:24008" remotepeer="83695a05-a36b-4bb4-8ccc-e9f1be712422(dhcp35-235.lab.eng.blr.redhat.com)" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.609128] connected to remote                           remote="10.70.35.8:24008" remotepeer="962636a1-4662-4892-ba24-9c76d9cbeb3a(dhcp35-8.lab.eng.blr.redhat.com)" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.609242] connected to remote                           remote="10.70.35.33:24008" remotepeer="1fefa0b7-8261-442f-b817-45484b3bfc75(dhcp35-33.lab.eng.blr.redhat.com)" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.609348] connected to remote                           remote="10.70.35.52:24008" remotepeer="cf52689a-c81d-4248-bef4-24c800ab4b32(dhcp35-52.lab.eng.blr.redhat.com)" reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:44.614488] running step function                         reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-create.StoreVolume txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:48.906350] running step function                         reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep200.Unlock txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:48.906467] attempting to unlock                          key=locks/rep200 reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[lock.go:62:transaction.createLockStepFunc.func2]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
DEBU[2018-05-11 17:56:48.907876] lock unlocked                                 key=locks/rep200 reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[lock.go:65:transaction.createLockStepFunc.func2]" txnid=bdbe2d40-09c2-4a93-a959-c3c996cc6793
INFO[2018-05-11 17:56:48.908922] new volume created                            reqid=9e5274a9-b16a-49f1-91de-170f4cce5835 source="[volume-create.go:147:volumes.volumeCreateHandler]" volume-name=rep200
INFO[2018-05-11 17:56:48.911088] ::1 - - [11/May/2018:17:56:44 +0530] "POST /v1/volumes HTTP/1.1" 201 1821  reqid=9e5274a9-b16a-49f1-91de-170f4cce5835
DEBU[2018-05-11 17:56:49.590383] attempting to lock                            key=locks/rep200 reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[lock.go:109:transaction.CreateLockFuncs.func1]"
DEBU[2018-05-11 17:56:49.593382] lock obtained                                 key=locks/rep200 reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[lock.go:113:transaction.CreateLockFuncs.func1]"
DEBU[2018-05-11 17:56:49.601660] Starting transaction                          reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[transaction.go:86:transaction.(*Txn).Do]" txnid=40730410-5106-42bc-8866-dbcfcca01c67
DEBU[2018-05-11 17:56:49.601807] running step function                         reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-start.StartBricks txnid=40730410-5106-42bc-8866-dbcfcca01c67
DEBU[2018-05-11 17:56:49.603047] connected to remote                           remote="10.70.35.194:24008" remotepeer="dc2e1be2-7e53-4e3d-a477-1c55dd290f60(dhcp35-194.lab.eng.blr.redhat.com)" reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[rpc-client.go:42:transaction.RunStepOn]" txnid=40730410-5106-42bc-8866-dbcfcca01c67
INFO[2018-05-11 17:56:49.604178] Starting brick                                brick="bd61117e-00d6-4cb0-a191-5bb582720448:/bricks/brick0/rep200" reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[volume-start.go:30:volumes.startAllBricks]" txnid=40730410-5106-42bc-8866-dbcfcca01c67 volume=rep200
DEBU[2018-05-11 17:56:49.604390] Starting daemon.                              args=" --volfile-server 127.0.0.1 --volfile-server-port 24007 --volfile-id rep200.bd61117e-00d6-4cb0-a191-5bb582720448.bricks-brick0-rep200 -p /var/run/gluster/bd61117e-00d6-4cb0-a191-5bb582720448-bricks-brick0-rep200.pid -S /var/run/gluster/8b58c0e860468b42.socket --brick-name /bricks/brick0/rep200 --brick-port 50990 -l /var/lib/gd2/log/glusterfs/bricks/bricks-brick0-rep200.log --xlator-option *-posix.glusterd-uuid=bd61117e-00d6-4cb0-a191-5bb582720448 --xlator-option rep200-server.transport.socket.listen-port=50990" name=glusterfsd path=/usr/sbin/glusterfsd source="[daemon.go:60:daemon.Start]"
DEBU[2018-05-11 17:56:49.604573] connected to remote                           remote="10.70.35.33:24008" remotepeer="1fefa0b7-8261-442f-b817-45484b3bfc75(dhcp35-33.lab.eng.blr.redhat.com)" reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[rpc-client.go:42:transaction.RunStepOn]" txnid=40730410-5106-42bc-8866-dbcfcca01c67
DEBU[2018-05-11 17:56:49.604604] connected to remote                           remote="10.70.35.8:24008" remotepeer="962636a1-4662-4892-ba24-9c76d9cbeb3a(dhcp35-8.lab.eng.blr.redhat.com)" reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[rpc-client.go:42:transaction.RunStepOn]" txnid=40730410-5106-42bc-8866-dbcfcca01c67
DEBU[2018-05-11 17:56:49.604966] connected to remote                           remote="10.70.35.52:24008" remotepeer="cf52689a-c81d-4248-bef4-24c800ab4b32(dhcp35-52.lab.eng.blr.redhat.com)" reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[rpc-client.go:42:transaction.RunStepOn]" txnid=40730410-5106-42bc-8866-dbcfcca01c67
DEBU[2018-05-11 17:56:49.605084] connected to remote                           remote="10.70.35.235:24008" remotepeer="83695a05-a36b-4bb4-8ccc-e9f1be712422(dhcp35-235.lab.eng.blr.redhat.com)" reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[rpc-client.go:42:transaction.RunStepOn]" txnid=40730410-5106-42bc-8866-dbcfcca01c67
INFO[2018-05-11 17:56:49.626782] client connected                              address="127.0.0.1:48951" server=sunrpc source="[server.go:167:sunrpc.(*SunRPC).acceptLoop]" transport=tcp
DEBU[2018-05-11 17:56:49.643201] Child exited                                  pid=16818 source="[daemon.go:88:daemon.Start]" status="<nil>"
DEBU[2018-05-11 17:56:49.643355] Started daemon successfully                   name=glusterfsd pid=16819 source="[daemon.go:112:daemon.Start]"
DEBU[2018-05-11 17:56:49.643526] Signal received                               signal="child exited" source="[main.go:135:main.main]"
INFO[2018-05-11 17:56:49.657074] volume started                                reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[volume-start.go:127:volumes.volumeStartHandler]" volume-name=rep200
DEBU[2018-05-11 17:56:49.659003] attempting to unlock                          key=locks/rep200 reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[lock.go:126:transaction.CreateLockFuncs.func2]"
DEBU[2018-05-11 17:56:49.660831] lock unlocked                                 key=locks/rep200 reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f source="[lock.go:132:transaction.CreateLockFuncs.func2]"
INFO[2018-05-11 17:56:49.660893] ::1 - - [11/May/2018:17:56:49 +0530] "POST /v1/volumes/rep200/start HTTP/1.1" 200 1821  reqid=81e73cc5-638c-49b3-b8a4-42e59a7dda1f

**Comment by prashanthpai** [comment]
Seems to me like bumping up `ResponseHeaderTimeout` should fix it. It is currently set to 3 seconds.

**Comment by rmadaka** [comment]
Verified with latest Glusterd2 binaries, I have tried same above scenario creating 200 volumes with script.

Not found any failed messages for volume creation or volume deletion.
