### ISSUE TITLE
Volume start force failing, after brick killing

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#759]
-> Kill any one brick from volume using kill -9 command,
-> Then perform  './glustercli volume start rep1 force '
-> volume start force failing with below error.

./glustercli volume start rep1 force
volume start failed

Error: Request failed with HTTP Status code 400

-> volume start force not able to start the killed brick.

Logs:

DEBU[2018-05-16 19:29:05.275846] attempting to lock                            key=locks/rep1 reqid=9ae04b94-9c9e-47be-a3ac-ee488e8cce1a source="[lock.go:109:transaction.CreateLockFuncs.func1]"
DEBU[2018-05-16 19:29:05.278693] lock obtained                                 key=locks/rep1 reqid=9ae04b94-9c9e-47be-a3ac-ee488e8cce1a source="[lock.go:113:transaction.CreateLockFuncs.func1]"
DEBU[2018-05-16 19:29:05.279700] attempting to unlock                          key=locks/rep1 reqid=9ae04b94-9c9e-47be-a3ac-ee488e8cce1a source="[lock.go:126:transaction.CreateLockFuncs.func2]"
DEBU[2018-05-16 19:29:05.281112] lock unlocked                                 key=locks/rep1 reqid=9ae04b94-9c9e-47be-a3ac-ee488e8cce1a source="[lock.go:132:transaction.CreateLockFuncs.func2]"
INFO[2018-05-16 19:29:05.281180] ::1 - - [16/May/2018:19:29:05 +0530] "POST /v1/volumes/rep1/start HTTP/1.1" 400 59  reqid=9ae04b94-9c9e-47be-a3ac-ee488e8cce1a

**Comment by aravindavk** [comment]
`force` need to be checked along with `if volinfo.State == volume.VolStarted {`

    	if volinfo.State == volume.VolStarted && !req.Force

Also errors due to start brick should be ignored if `daemon.Start` command returns `ErrAlreadyStarted`

**Comment by Madhu-1** [comment]
volume start doesn't contain any request body in cli/rest client. need to make changes to send a post to the server

current rest client code
```
func (c *Client) VolumeStart(volname string) error {
	url := fmt.Sprintf("/v1/volumes/%s/start", volname)
	return c.post(url, nil, http.StatusOK, nil)
}
```

**Comment by prashanthpai** [comment]
> volume start doesn't contain any request body in cli/rest client

...which is how it should be

**Comment by Madhu-1** [comment]
@prashanthpai  okay
