### ISSUE TITLE
Volume creation of invalid volume type failing with invalid error messages.

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#764]
Tried blow scenarios like:
Example 1:
--------------
./glustercli volume create rep replica3 10.70.35.219:/bricks/brick0/rep1/ 10.70.35.235:/bricks/brick0/rep1/ 10.70.35.52:/bricks/brick0/rep1/
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gluster/glusterd2/glustercli/cmd.bricksAsUUID(0xc42007c4c0, 0x4, 0x4, 0x16, 0x10, 0x4d4855, 0x7d049d, 0x8)
	/home/ppai/work/src/github.com/gluster/glusterd2/glustercli/cmd/volume.go:109 +0x9bd
github.com/gluster/glusterd2/glustercli/cmd.volumeCreateCmdRun(0x9d04a0, 0xc42007c4b0, 0x5, 0x5)
	/home/ppai/work/src/github.com/gluster/glusterd2/glustercli/cmd/volume-create.go:58 +0x94
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).execute(0x9d04a0, 0xc42007c460, 0x5, 0x5, 0x9d04a0, 0xc42007c460)
	/home/ppai/work/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x9d0240, 0x7, 0x8, 0xc4200100f0)
	/home/ppai/work/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:846 +0x334
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).Execute(0x9d0240, 0x76bbe0, 0xc4200797d0)
	/home/ppai/work/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/home/ppai/work/src/github.com/gluster/glusterd2/glustercli/main.go:14 +0x36

Example 2:
-------------
/glustercli volume create rep a 3 10.70.35.219:/bricks/brick0/rep1/ 10.70.35.235:/bricks/brick0/rep1/ 10.70.35.52:/bricks/brick0/rep1/
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/gluster/glusterd2/glustercli/cmd.bricksAsUUID(0xc42005e8b0, 0x5, 0x5, 0x16, 0x10, 0x4d4855, 0x7cf59b, 0x4)
	/home/ppai/work/src/github.com/gluster/glusterd2/glustercli/cmd/volume.go:109 +0x9bd
github.com/gluster/glusterd2/glustercli/cmd.volumeCreateCmdRun(0x9d04a0, 0xc42005e8a0, 0x6, 0x6)
	/home/ppai/work/src/github.com/gluster/glusterd2/glustercli/cmd/volume-create.go:58 +0x94
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).execute(0x9d04a0, 0xc42005e7e0, 0x6, 0x6, 0x9d04a0, 0xc42005e7e0)
	/home/ppai/work/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:760 +0x2c1
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x9d0240, 0x8, 0x9, 0xc420010110)
	/home/ppai/work/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:846 +0x334
github.com/gluster/glusterd2/vendor/github.com/spf13/cobra.(*Command).Execute(0x9d0240, 0x76bbe0, 0xc4200797d0)
	/home/ppai/work/src/github.com/gluster/glusterd2/vendor/github.com/spf13/cobra/command.go:794 +0x2b
main.main()
	/home/ppai/work/src/github.com/gluster/glusterd2/glustercli/main.go:14 +0x36

**Comment by Madhu-1** [comment]
are you using code from the master branch? I think this has been fixed in #700

**Comment by atinmu** [comment]
retest!

**Comment by rmadaka** [comment]
Now invalid volume type throwing proper error messages with latest build, messages seems to be fine closing this issue

below commands tried:
1)
./glustercli volume create vol1 @# 10.70.35.33:/bricks/brick0/rep7 10.70.35.52:/bricks/brick0/rep7 10.70.35.8:/bricks/brick0/rep7
Error getting brick UUIDs

Error: invalid Brick details, use <host>:<path> or <peerid>:<path>

2)
./glustercli volume create rep6 replica3 10.70.35.33:/bricks/brick0/rep6 10.70.35.52:/bricks/brick0/rep6 10.70.35.8:/bricks/brick0/rep6
Error getting brick UUIDs

Error: invalid Brick details, use <host>:<path> or <peerid>:<path>
3)
./glustercli volume create rep6 a 3 10.70.35.33:/bricks/brick0/rep6 10.70.35.52:/bricks/brick0/rep6 10.70.35.8:/bricks/brick0/rep6
Error getting brick UUIDs

Error: invalid Brick details, use <host>:<path> or <peerid>:<path>
