### ISSUE TITLE
Failed to run bitrot scrub-throttle command

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#766]
By default scrub procees is started in lazy-mode but if i want to change the rate to either normal/aggressive  scrub-throttle command is failing with below error.
command1:
---------------

./glustercli bitrot scrub-throttle rep aggressive
Failed to set bitrot scrub throttle to aggressive for volume rep

Error: Request failed with HTTP Status code 500
Validation failed for volume option: Option bit-rot.scrub-throttle is an advanced option. To set it pass the advanced flag

command2:

./glustercli bitrot scrub-throttle rep normal
Failed to set bitrot scrub throttle to normal for volume rep

Error: Request failed with HTTP Status code 500
Validation failed for volume option: Option bit-rot.scrub-throttle is an advanced option. To set it pass the advanced flag

logs:

DEBU[2018-05-17 17:12:22.306529] Starting transaction                          reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6 source="[transaction.go:86:transaction.(*Txn).Do]" txnid=a4950be9-45b1-413c-86ec-485b50464b5f
DEBU[2018-05-17 17:12:22.306685] running step function                         reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep.Lock txnid=a4950be9-45b1-413c-86ec-485b50464b5f
DEBU[2018-05-17 17:12:22.306756] attempting to lock                            key=locks/rep reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6 source="[lock.go:45:transaction.createLockStepFunc.func1]" txnid=a4950be9-45b1-413c-86ec-485b50464b5f
DEBU[2018-05-17 17:12:22.309213] lock obtained                                 key=locks/rep reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6 source="[lock.go:49:transaction.createLockStepFunc.func1]" txnid=a4950be9-45b1-413c-86ec-485b50464b5f
DEBU[2018-05-17 17:12:22.309288] running step function                         reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-option.Validate txnid=a4950be9-45b1-413c-86ec-485b50464b5f
ERRO[2018-05-17 17:12:22.311440] Transaction failed, rolling back changes      error="Validation failed for volume option: Option bit-rot.scrub-throttle is an advanced option. To set it pass the advanced flag" reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6 source="[transaction.go:92:transaction.(*Txn).Do]" txnid=a4950be9-45b1-413c-86ec-485b50464b5f
DEBU[2018-05-17 17:12:22.311529] running step function                         reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep.Unlock txnid=a4950be9-45b1-413c-86ec-485b50464b5f
DEBU[2018-05-17 17:12:22.311566] attempting to unlock                          key=locks/rep reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6 source="[lock.go:62:transaction.createLockStepFunc.func2]" txnid=a4950be9-45b1-413c-86ec-485b50464b5f
DEBU[2018-05-17 17:12:22.313291] lock unlocked                                 key=locks/rep reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6 source="[lock.go:65:transaction.createLockStepFunc.func2]" txnid=a4950be9-45b1-413c-86ec-485b50464b5f
ERRO[2018-05-17 17:12:22.313346] volume option transaction failed              error="Validation failed for volume option: Option bit-rot.scrub-throttle is an advanced option. To set it pass the advanced flag" reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6 source="[volume-option.go:137:volumes.volumeOptionsHandler]"
INFO[2018-05-17 17:12:22.315270] ::1 - - [17/May/2018:17:12:22 +0530] "POST /v1/volumes/rep/options HTTP/1.1" 500 159  reqid=a5bb54b5-24ef-4b71-9564-19ae902910f6
DEBU[2018-05-17 17:13:02.405793] Starting transaction                          reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1 source="[transaction.go:86:transaction.(*Txn).Do]" txnid=9f61dce1-4433-4238-8129-3deb98bd38fe
DEBU[2018-05-17 17:13:02.405875] running step function                         reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep.Lock txnid=9f61dce1-4433-4238-8129-3deb98bd38fe
DEBU[2018-05-17 17:13:02.405932] attempting to lock                            key=locks/rep reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1 source="[lock.go:45:transaction.createLockStepFunc.func1]" txnid=9f61dce1-4433-4238-8129-3deb98bd38fe
DEBU[2018-05-17 17:13:02.408179] lock obtained                                 key=locks/rep reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1 source="[lock.go:49:transaction.createLockStepFunc.func1]" txnid=9f61dce1-4433-4238-8129-3deb98bd38fe
DEBU[2018-05-17 17:13:02.408230] running step function                         reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-option.Validate txnid=9f61dce1-4433-4238-8129-3deb98bd38fe
ERRO[2018-05-17 17:13:02.409863] Transaction failed, rolling back changes      error="Validation failed for volume option: Option bit-rot.scrub-throttle is an advanced option. To set it pass the advanced flag" reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1 source="[transaction.go:92:transaction.(*Txn).Do]" txnid=9f61dce1-4433-4238-8129-3deb98bd38fe
DEBU[2018-05-17 17:13:02.409916] running step function                         reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep.Unlock txnid=9f61dce1-4433-4238-8129-3deb98bd38fe
DEBU[2018-05-17 17:13:02.409949] attempting to unlock                          key=locks/rep reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1 source="[lock.go:62:transaction.createLockStepFunc.func2]" txnid=9f61dce1-4433-4238-8129-3deb98bd38fe
DEBU[2018-05-17 17:13:02.411807] lock unlocked                                 key=locks/rep reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1 source="[lock.go:65:transaction.createLockStepFunc.func2]" txnid=9f61dce1-4433-4238-8129-3deb98bd38fe
ERRO[2018-05-17 17:13:02.411846] volume option transaction failed              error="Validation failed for volume option: Option bit-rot.scrub-throttle is an advanced option. To set it pass the advanced flag" reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1 source="[volume-option.go:137:volumes.volumeOptionsHandler]"
INFO[2018-05-17 17:13:02.413347] ::1 - - [17/May/2018:17:13:02 +0530] "POST /v1/volumes/rep/options HTTP/1.1" 500 159  reqid=3ed9c4b3-a7c6-4502-a2cd-77c63c9c70e1
DEBU[2018-05-17 17:13:19.397124] Starting transaction                          reqid=c3cf1253-3e3f-4786-9fac-ec637c881628 source="[transaction.go:86:transaction.(*Txn).Do]" txnid=eb069124-af56-4640-9ac6-660ecb1e0324
DEBU[2018-05-17 17:13:19.397184] running step function                         reqid=c3cf1253-3e3f-4786-9fac-ec637c881628 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep.Lock txnid=eb069124-af56-4640-9ac6-660ecb1e0324
DEBU[2018-05-17 17:13:19.397235] attempting to lock                            key=locks/rep reqid=c3cf1253-3e3f-4786-9fac-ec637c881628 source="[lock.go:45:transaction.createLockStepFunc.func1]" txnid=eb069124-af56-4640-9ac6-660ecb1e0324
DEBU[2018-05-17 17:13:19.400154] lock obtained                                 key=locks/rep reqid=c3cf1253-3e3f-4786-9fac-ec637c881628 source="[lock.go:49:transaction.createLockStepFunc.func1]" txnid=eb069124-af56-4640-9ac6-660ecb1e0324
DEBU[2018-05-17 17:13:19.400200] running step function                         reqid=c3cf1253-3e3f-4786-9fac-ec637c881628 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-option.Validate txnid=eb069124-af56-4640-9ac6-660ecb1e0324
ERRO[2018-05-17 17:13:19.402094] Transaction failed, rolling back changes      error="Validation failed for volume option: Option bit-rot.scrub-throttle is an advanced option. To set it pass the advanced flag" reqid=c3cf1253-3e3f-4786-9fac-ec637c881628 source="[transaction.go:92:transaction.(*Txn).Do]" txnid=eb069124-af56-4640-9ac6-660ecb1e0324
DEBU[2018-05-17 17:13:19.402171] running step function                         reqid=c3cf1253-3e3f-4786-9fac-ec637c881628 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep.Unlock txnid=eb069124-af56-4640-9ac6-660ecb1e0324
DEBU[2018-05-17 17:13:19.402214] attempting to unlock                          key=locks/rep reqid=c3cf1253-3e3f-4786-9fac-ec637c881628 source="[lock.go:62:transaction.createLockStepFunc.func2]" txnid=eb069124-af56-4640-9ac6-660ecb1e0324
DEBU[2018-05-17 17:13:19.405583] lock unlocked                                 key=locks/rep reqid=c3cf1253-3e3f-4786-9fac-ec637c881628 source="[lock.go:65:transaction.createLockStepFunc.func2]" txnid=eb069124-af56-4640-9ac6-660ecb1e0324
ERRO[2018-05-17 17:13:19.405648] volume option transaction failed              error="Validation failed for volume option: Option bit-rot.scrub-throttle is an advanced option. To set it pass the advanced flag" reqid=c3cf1253-3e3f-4786-9fac-ec637c881628 source="[volume-option.go:137:volumes.volumeOptionsHandler]"
INFO[2018-05-17 17:13:19.407650] ::1 - - [17/May/2018:17:13:19 +0530] "POST /v1/volumes/rep/options HTTP/1.1" 500 159  reqid=c3cf1253-3e3f-4786-9fac-ec637c881628

**Comment by Madhu-1** [comment]
I think you need to set volume options for this.
check log messages

**Comment by aravindavk** [comment]
Patch #770 fixes this issue. Reopen if seen again
