### ISSUE TITLE
Bitrot scrub pause/resume commands are failing

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#767]
Bitrot scrub pause/resume commands are failing with below error messages

./glustercli bitrot scrub rep pause
Failed to pause bitrot scrub for volume rep

Error: Request failed with HTTP Status code 500
Validation failed for volume option: Option bit-rot.scrub-state is an advanced option. To set it pass the advanced flag.

./glustercli bitrot scrub rep resume
Failed to resume bitrot scrub for volume rep

Error: Request failed with HTTP Status code 500
Validation failed for volume option: Option bit-rot.scrub-state is an advanced option. To set it pass the advanced flag

Logs:
------

DEBU[2018-05-17 17:18:23.068615] Starting transaction                          reqid=26dc9158-918a-4569-94cc-fde0d56ead0b source="[transaction.go:86:transaction.(*Txn).Do]" txnid=8d9f2057-8193-4c14-bdb1-ab16703a28fd
DEBU[2018-05-17 17:18:23.068771] running step function                         reqid=26dc9158-918a-4569-94cc-fde0d56ead0b source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep.Lock txnid=8d9f2057-8193-4c14-bdb1-ab16703a28fd
DEBU[2018-05-17 17:18:23.068847] attempting to lock                            key=locks/rep reqid=26dc9158-918a-4569-94cc-fde0d56ead0b source="[lock.go:45:transaction.createLockStepFunc.func1]" txnid=8d9f2057-8193-4c14-bdb1-ab16703a28fd
DEBU[2018-05-17 17:18:23.071310] lock obtained                                 key=locks/rep reqid=26dc9158-918a-4569-94cc-fde0d56ead0b source="[lock.go:49:transaction.createLockStepFunc.func1]" txnid=8d9f2057-8193-4c14-bdb1-ab16703a28fd
DEBU[2018-05-17 17:18:23.071377] running step function                         reqid=26dc9158-918a-4569-94cc-fde0d56ead0b source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-option.Validate txnid=8d9f2057-8193-4c14-bdb1-ab16703a28fd
ERRO[2018-05-17 17:18:23.073171] Transaction failed, rolling back changes      error="Validation failed for volume option: Option bit-rot.scrub-state is an advanced option. To set it pass the advanced flag" reqid=26dc9158-918a-4569-94cc-fde0d56ead0b source="[transaction.go:92:transaction.(*Txn).Do]" txnid=8d9f2057-8193-4c14-bdb1-ab16703a28fd
DEBU[2018-05-17 17:18:23.073221] running step function                         reqid=26dc9158-918a-4569-94cc-fde0d56ead0b source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep.Unlock txnid=8d9f2057-8193-4c14-bdb1-ab16703a28fd
DEBU[2018-05-17 17:18:23.073254] attempting to unlock                          key=locks/rep reqid=26dc9158-918a-4569-94cc-fde0d56ead0b source="[lock.go:62:transaction.createLockStepFunc.func2]" txnid=8d9f2057-8193-4c14-bdb1-ab16703a28fd
DEBU[2018-05-17 17:18:23.074980] lock unlocked                                 key=locks/rep reqid=26dc9158-918a-4569-94cc-fde0d56ead0b source="[lock.go:65:transaction.createLockStepFunc.func2]" txnid=8d9f2057-8193-4c14-bdb1-ab16703a28fd
ERRO[2018-05-17 17:18:23.075038] volume option transaction failed              error="Validation failed for volume option: Option bit-rot.scrub-state is an advanced option. To set it pass the advanced flag" reqid=26dc9158-918a-4569-94cc-fde0d56ead0b source="[volume-option.go:137:volumes.volumeOptionsHandler]"
INFO[2018-05-17 17:18:23.076763] ::1 - - [17/May/2018:17:18:23 +0530] "POST /v1/volumes/rep/options HTTP/1.1" 500 156  reqid=26dc9158-918a-4569-94cc-fde0d56ead0b

**Comment by Madhu-1** [comment]
I think you need to set volume options for this.
check log messages

**Comment by amarts** [comment]
While it is valid to get an error if it is an advanced option, bitrot pause and start may need to be marked as basic.

@kotreshhr this needs to be fixed in the glusterfs code.

**Comment by aravindavk** [comment]
Bitrot feature added to glusterd2 before the changes done to options level. Fix required in `glustercli` to include `Advanced` flag while calling restclient. Alternatively these can be made as basic options as @amarts suggested.

> I think you need to set volume options for this.

@Madhu-1 bitrot glustercli is setting volume options internally

**Comment by amarts** [comment]
@aravindavk I like this idea better. People using it directly should know it is 'advanced'. Lets not make changes in glusterfs codebase, but in cli.

@kotreshhr nothing pending on you then :+1:

**Comment by kshlm** [comment]
I would have preferred that the ReST handler in GD2 added this. But, I believe that scrub pause etc., just use the volume set APIs.
