### ISSUE TITLE
creation of volume with  special characters in volume name (except underscore and hyphen) should fail

### ISSUE THREAD

**Issue by Madhu-1** [gluster/glusterd2#772]

**Comment by prashanthpai** [comment]
@Madhu-1 Out of curiosity, is there any technical reasons for introducing this ?

The PR #773 has a regular expression that limits volume names to English alphabets and numbers. What about non-English volume names ?

Volume names are used in volfiles, xattrs and paths.

**Comment by Madhu-1** [comment]
@prashanthpai  there are limitations in using the special characters in volume name (either in CLI and in URL for any other operation.
we can create volume with a name including special characters, but we cant use those name in CLI or URL to access those resources

and some of the special characters are reserved in [REST](https://tools.ietf.org/html/rfc3986#section-2.2)
we do have a check for this in glusterd1 and HEKETI for the volume name

[glusterd1](https://github.com/gluster/glusterfs/blob/master/cli/src/cli-cmd-parser.c#L406)
[heketi](https://github.com/heketi/heketi/blob/master/pkg/glusterfs/api/types.go#L35)

**Comment by prashanthpai** [comment]
> but we cant use those name in CLI or URL to access those resources

Those volume names have to be URL (percent) encoded during access.

> we do have a check for this in glusterd1 and HEKETI for the volume name

If glusterd1 imposed such restriction, then there aren't volumes present today that violate that rule. I guess it's okay in that case as it won't be a surprise to existing users :+1:
