### ISSUE TITLE
After peer detach  from two node cluster,  current peer glusterd is going to hung state 

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#778]
-> Having two node cluster n1, n2 
-> Detach one peer(n2) from node n1
-> node n1 glusterd is going to hung state. no glusterd commands are working from node n1
Results:
----------

[root@dhcp35-235 ~]# ./glustercli peer status
+--------------------------------------+-----------------------------------+--------------------+
|                  ID                  |               NAME                |   PEERADDRESSES    |
+--------------------------------------+-----------------------------------+--------------------+
| 0ae99b11-1ad8-4533-989b-eca23d741b10 | dhcp35-33.lab.eng.blr.redhat.com  | 10.70.35.33:24008  |
| b3d025dc-e221-4df1-b742-624a98b30071 | dhcp35-235.lab.eng.blr.redhat.com | 10.70.35.235:24008 |
+--------------------------------------+-----------------------------------+--------------------+
[root@dhcp35-235 ~]# ./glustercli peer detach 10.70.35.33:24008
Peer detach success
[root@dhcp35-235 ~]# ./glustercli peer status
Failed to get Peers list

Error: Get http://localhost:24007/v1/peers: net/http: timeout awaiting response headers

Logs 
-----
No logs generated

**Comment by atinmu** [comment]
Does this behavior persists for a 3 node cluster?

**Comment by kshlm** [comment]
This is the same as #332. Closing this in preference to the older issue.
