### ISSUE TITLE
Peer detach successful but throwing error message like peer detach failed

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#779]
-> Having three nodes (n1, n2, n3)
-> Perform peer probe from n1->n2 and n2->n3
-> Now n1, n2, n3 are in cluster
-> Then perform peer detach node n1 from n3.
-> Actually peer detached successfully from cluster but throwing error message like below.

Before Peer detach:
-------------------------
./glustercli peer status
+--------------------------------------+-----------------------------------+--------------------+
|                  ID                  |               NAME                |   PEERADDRESSES    |
+--------------------------------------+-----------------------------------+--------------------+
| 13ea9d4f-d24f-4434-a3cb-f83117196362 | dhcp35-8.lab.eng.blr.redhat.com   | 10.70.35.8:24008   |
| 1df9fc10-a5e8-47ee-bb7b-8678df466a7b | dhcp35-194.lab.eng.blr.redhat.com | 10.70.35.194:24008 |
| b622c5fb-528f-4950-8b6f-d15264941788 | dhcp35-52.lab.eng.blr.redhat.com  | 10.70.35.52:24008  |
+--------------------------------------+-----------------------------------+--------------------+

Performing peer detach:
------------------------------
./glustercli peer detach 10.70.35.194:24008
Peer detach failed

Error: Delete http://localhost:24007/v1/peers/1df9fc10-a5e8-47ee-bb7b-8678df466a7b: net/http: timeout awaiting response headers

After peer detach:
----------------------

./glustercli peer status
+--------------------------------------+----------------------------------+-------------------+
|                  ID                  |               NAME               |   PEERADDRESSES   |
+--------------------------------------+----------------------------------+-------------------+
| 13ea9d4f-d24f-4434-a3cb-f83117196362 | dhcp35-8.lab.eng.blr.redhat.com  | 10.70.35.8:24008  |
| b622c5fb-528f-4950-8b6f-d15264941788 | dhcp35-52.lab.eng.blr.redhat.com | 10.70.35.52:24008 |
+--------------------------------------+----------------------------------+-------------------+

i will be adding logs .i will reproduce the scenario and post the logs here.

**Comment by Madhu-1** [comment]
@rmadaka  can you add glusterd2 logs

**Comment by Madhu-1** [comment]
@rmadaka  if you are able to reproduce this issue, please attach gd2 server logs.

**Comment by rmadaka** [comment]
Not able to reproduce this issue with latest build, closing this issue
