### ISSUE TITLE
Able to use same brick for two volumes before volume start

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#787]
-> Create replica 3 volume with bricks ip1:/b1,  ip2:/b1,  ip3:/b1
-> Volume created successfully
-> don't start the volume
-> Create one more replica 3 volume with one brick from previous volume remaining two bricks are new
like ip1:/b1 , ip2:/b2, ip3:/b2
-> volume created successfully
-> then start the volumes
-> both the volumes started successfully

Commands:

first-volume:

./glustercli volume create rep5 replica 3 10.70.35.235:/bricks/brick0/rep5 10.70.35.33:/bricks/brick0/rep5 10.70.35.52:/bricks/brick0/rep4
rep5 Volume created successfully
Volume ID:  4322700d-afb3-4e5e-b7fd-00ccc09fa31c

second volume:

./glustercli volume create rep6 replica 3 10.70.35.235:/bricks/brick0/rep5 10.70.35.33:/bricks/brick0/rep6 10.70.35.52:/bricks/brick0/rep6
rep6 Volume created successfully
Volume ID:  30721d27-6ccc-4604-bb11-3b786be37146

for above volumes  brick 10.70.35.235:/bricks/brick0/rep5 is same.

volume status for both the volumes:

like above i have tried for 4 volumes pasting volume status below.  In all 4 volumes we can see reused bricks
+--------------------------------------+--------------+---------------------+--------+-------+-------+
|               BRICK ID               |     HOST     |        PATH         | ONLINE | PORT  |  PID  |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
| 74707c4d-ddd9-4d93-8769-373f57a9bf57 | 10.70.35.235 | /bricks/brick0/rep3 | true   | 49154 | 13329 |
| 4be6f5a9-fc59-4781-8cb9-85ac39544ec9 | 10.70.35.33  | /bricks/brick0/rep3 | true   | 49154 | 13262 |
| 5cc08760-83fc-4088-81d2-7ca5135ef24a | 10.70.35.52  | /bricks/brick0/rep3 | true   | 49154 | 13277 |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
Volume : rep4
+--------------------------------------+--------------+---------------------+--------+-------+-------+
|               BRICK ID               |     HOST     |        PATH         | ONLINE | PORT  |  PID  |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
| 8d4ef4e2-c77f-404a-aebd-e5e0cc19082f | 10.70.35.33  | /bricks/brick0/rep4 | true   | 49159 | 13284 |
| 8c069910-528b-40b6-b5d4-aec878751f1f | 10.70.35.52  | /bricks/brick0/rep4 | true   | 49159 | 13299 |
| ecda8b47-6693-4a18-b37a-60f331ff07b8 | 10.70.35.235 | /bricks/brick0/rep3 | true   | 49154 | 13329 |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
Volume : rep5
+--------------------------------------+--------------+---------------------+--------+-------+-------+
|               BRICK ID               |     HOST     |        PATH         | ONLINE | PORT  |  PID  |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
| 9b108346-442e-4690-b406-d1451c51ba5d | 10.70.35.235 | /bricks/brick0/rep5 | true   | 49166 | 13626 |
| d9695d85-6b62-4f91-9051-502c32ed845c | 10.70.35.33  | /bricks/brick0/rep5 | true   | 49169 | 13713 |
| 3109ebbc-7ec1-4d0a-b731-cc726bbf5f3d | 10.70.35.52  | /bricks/brick0/rep4 | true   | 49159 | 13299 |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
Volume : rep6
+--------------------------------------+--------------+---------------------+--------+-------+-------+
|               BRICK ID               |     HOST     |        PATH         | ONLINE | PORT  |  PID  |
+--------------------------------------+--------------+---------------------+--------+-------+-------+
| 3724adfe-1496-4e4d-b73b-094eaf912688 | 10.70.35.33  | /bricks/brick0/rep6 | true   | 49164 | 13573 |
| ef09cc6d-e992-4fbc-8dda-dea639db5086 | 10.70.35.52  | /bricks/brick0/rep6 | true   | 49164 | 13590 |
| 9addf6f1-a333-4c39-8879-ab1a2f5976f6 | 10.70.35.235 | /bricks/brick0/rep5 | true   | 49166 | 13626 |
+--------------------------------------+--------------+---------------------+--------+-------+-------+

Logs:
INFO[2018-05-23 19:06:08.353893] ::1 - - [23/May/2018:19:06:08 +0530] "GET /v1/peers HTTP/1.1" 200 653  reqid=218abfe0-c56a-4e7f-b9e3-be262fa69cad
DEBU[2018-05-23 19:06:08.370268] Starting transaction                          reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[transaction.go:86:transaction.(*Txn).Do]" txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.370389] running step function                         reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep6.Lock txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.370455] attempting to lock                            key=locks/rep6 reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[lock.go:45:transaction.createLockStepFunc.func1]" txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.373459] lock obtained                                 key=locks/rep6 reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[lock.go:49:transaction.createLockStepFunc.func1]" txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.373522] running step function                         reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-create.CreateVolinfo txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.382593] running step function                         reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-create.ValidateBricks txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.383994] connected to remote                           remote="10.70.35.33:24008" remotepeer="6caaddf4-c134-4960-9b49-28ef73e2ce99(dhcp35-33.lab.eng.blr.redhat.com)" reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.384133] connected to remote                           remote="10.70.35.52:24008" remotepeer="faecea15-66ee-4e5a-91f7-4393f84bad3a(dhcp35-52.lab.eng.blr.redhat.com)" reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.384707] Brick validation failed                       brick=/bricks/brick0/rep5 error="Xattr trusted.glusterfs.volume-id already present on /bricks/brick0/rep5" reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[common.go:152:volumes.validateBricks]" txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.389041] running step function                         reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-create.InitBricks txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.389918] connected to remote                           remote="10.70.35.52:24008" remotepeer="faecea15-66ee-4e5a-91f7-4393f84bad3a(dhcp35-52.lab.eng.blr.redhat.com)" reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.390416] connected to remote                           remote="10.70.35.33:24008" remotepeer="6caaddf4-c134-4960-9b49-28ef73e2ce99(dhcp35-33.lab.eng.blr.redhat.com)" reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[rpc-client.go:42:transaction.RunStepOn]" txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
ERRO[2018-05-23 19:06:08.391429] Setxattr failed                               error="file exists" key=trusted.glusterfs.volume-id path=/bricks/brick0/rep5 source="[common.go:190:volumes.initBricks]"
DEBU[2018-05-23 19:06:08.393687] running step function                         reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=vol-create.StoreVolume txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.515033] running step function                         reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[step.go:73:transaction.runStepFuncLocal]" stepfunc=rep6.Unlock txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.515091] attempting to unlock                          key=locks/rep6 reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[lock.go:62:transaction.createLockStepFunc.func2]" txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
DEBU[2018-05-23 19:06:08.516709] lock unlocked                                 key=locks/rep6 reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[lock.go:65:transaction.createLockStepFunc.func2]" txnid=c9914a4e-db61-4461-bebc-07a0fd6a597c
INFO[2018-05-23 19:06:08.517715] new volume created                            reqid=7914b80c-a8f0-440e-afb8-82f96ace7622 source="[volume-create.go:147:volumes.volumeCreateHandler]" volume-name=rep6
INFO[2018-05-23 19:06:08.520019] ::1 - - [23/May/2018:19:06:08 +0530] "POST /v1/volumes HTTP/1.1" 201 988  reqid=7914b80c-a8f0-440e-afb8-82f96ace7622

**Comment by Madhu-1** [comment]
not able to reproduce this issue 

1)create first  volume 
```
/build/glustercli volume create test_volume1 8d796e28-fa4f-46a5-aca9-a9838f15c7ac:/export/brick1/data 9f0eec84-aa3a-4066-a4ea-94c673ffebf4:/export/brick2/data 8d796e28-fa4f-46a5-aca9-a9838f15c7ac:/export/brick3/data 9f0eec84-aa3a-4066-a4ea-94c673ffebf4:/export/brick4/data --force
test_volume1 Volume created successfully
Volume ID:  c4b3e470-f072-4e07-a8fc-6a15d13d119e
```
2)create 2nd volume
```
 ./build/glustercli  volume create test_volume2 8d796e28-fa4f-46a5-aca9-a9838f15c7ac:/export/brick1/data 9f0eec84-aa3a-4066-a4ea-94c673ffebf4:/export/brick2/data 8d796e28-fa4f-46a5-aca9-a9838f15c7ac:/export/brick3/data 9f0eec84-aa3a-4066-a4ea-94c673ffebf4:/export/brick4/data  -v
ERRO[2018-05-18 14:24:41.498750] volume creation failed                        error="Request failed with HTTP Status code 500\nStep vol-create.ValidateBricks failed on 2 nodes" volume=test_volume2
Volume creation failed

Error: Request failed with HTTP Status code 500
Step vol-create.ValidateBricks failed on 2 nodes
```

3)to create replica volume use cli command like 

```
/glustercli volume create rep6 --replica=3 10.70.35.235:/bricks/brick0/rep5 10.70.35.33:/bricks/brick0/rep6 10.70.35.52:/bricks/brick0/rep6
```


@rmadaka  if you are able to reproduce with latest glusterd2,  please let us know

**Comment by rmadaka** [comment]
Not able to reproduce this issue with latest build

**Comment by rmadaka** [comment]
If we are trying to use previous volume brick , volume creation failing with below error . 
closed this issue as not reproducible.

 ./glustercli volume create rep4 replica 3 10.70.35.33:/bricks/brick0/rep4 10.70.35.52:/bricks/brick0/rep2 10.70.35.8:/bricks/brick0/rep4
Volume creation failed

Error: Request failed with HTTP Status code 500
Transaction step vol-create.ValidateBricks failed on peer 72f7790b-24de-446e-ad88-56da73046db7 with error: Xattr trusted.glusterfs.volume-id already present on /bricks/brick0/rep2
