### ISSUE TITLE
Building Glusterd2 fails

### ISSUE THREAD

**Issue by rishubhjain** [gluster/glusterd2#792]
Building glusterd2 fails with error:

glusterd2/transaction/rpc-service.go:55: cannot use p (type *txnSvc) as type TxnSvcServer in argument to RegisterTxnSvcServer:
	*txnSvc does not implement TxnSvcServer (wrong type for RunStep method)
		have RunStep("context".Context, *TxnStepReq) (*TxnStepResp, error)
		want RunStep("github.com/gluster/glusterd2/vendor/golang.org/x/net/context".Context, *TxnStepReq) (*TxnStepResp, error)

**Comment by rishubhjain** [comment]
@prashanthpai

**Comment by prashanthpai** [comment]
This works on my machine, @aravindavk's machine and also CI machine. Weird.
But it definitely was introduced by [this commit](https://github.com/gluster/glusterd2/commit/5c0eaeaabe517f22276f2b03c2a1ed77e189f4ae). Reverting it harmless.

**Comment by aravindavk** [comment]
can you try again by deleting vendor directory?
