### ISSUE TITLE
Bitrot scrub status command failing for  bitrot enabled volumes

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#798]
Scenario1:

-> Enable bitrot on any volume
-> Bitrot enabled  successfully
-> Then check the bitrot scrub status
-> Bitrot scrub status failing with below error
 
Commands:

./glustercli bitrot enable rep1
Bitrot enabled successfully for volume rep1

./glustercli bitrot scrub rep1 status
Failed to get bitrot scrub status for volume rep1

Error: Request failed with HTTP Status code 400
Bitrot is not enabled

Scenario2:

If I check bitrot scrub status for not enabled volumes  failing with  below error

./glustercli bitrot scrub vol2 status
Failed to get bitrot scrub status for volume vol2

Error: Request failed with HTTP Status code 500
strconv.Atoi: parsing "": invalid syntax

**Comment by amarts** [comment]
Can we consider automating it and adding into travis CI? I saw overall 3 bugs in this feature testing?
