### ISSUE TITLE
Add makefile

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#8]

**Comment by atinmu** [comment]
https://review.gerrithub.io/246250 posted for review

**Comment by kshlm** [comment]
Why do you think this is a necessity?

**Comment by atinmu** [comment]
Don't you think we should have a make interface to build the project? Also I was thinking of using go test tool chain to run all the unit tests. a simple 'make test' command will run all the unit tests from the repository.

**Comment by kshlm** [comment]
What's so hard in running, `go build` and `go test`?

**Comment by atinmu** [comment]
we could run any commands like that but makefile is a place holder  where we can club all of them and define what specifics we need to do.

**Comment by kshlm** [comment]
#28 introduced a makefile. While the introduced makfile still doesn't have some of the things @atinmu's original review, we can get those in as we go along.
