### ISSUE TITLE
 peer add with short names not FQDN (hostname -s) is failing

### ISSUE THREAD

**Issue by rmadaka** [gluster/glusterd2#807]
peer add with short names not FQDN (hostname -s) is failing

Tried First time:

./glustercli peer add  dhcp35-194
Peer add failed

Error: Post http://localhost:24007/v1/peers: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

Tried Second time:
-> Second time filed with different error code

./glustercli peer add  dhcp35-194
Peer add failed

Error: Request failed with HTTP Status code 409
already processing another join/leave request

Second Time Logs:

time="2018-05-28 14:37:56.240678" level=error msg="join request failed" error="already processing another join/leave request" peer="dhcp35-194:24008" reqid=57b018b4-82f4-4f3c-9f00-704ce3da86c7 source="[addpeer.go:78:peers.addPeerHandler]"
time="2018-05-28 14:37:56.240878" level=info msg="::1 - - [28/May/2018:14:37:56 +0530] \"POST /v1/peers HTTP/1.1\" 409 82" reqid=57b018b4-82f4-4f3c-9f00-704ce3da86c7

**Comment by rmadaka** [comment]
After tried with shortname  peer add is failing with hostname (FQDN)   and ipaddress also for same peer which is tried with short name.

./glustercli peer add dhcp35-194.lab.eng.blr.redhat.com 
Peer add failed

Error: Request failed with HTTP Status code 409
already processing another join/leave request


./glustercli peer add 10.70.35.194
Peer add failed

Error: Request failed with HTTP Status code 409
already processing another join/leave request

**Comment by rishubhjain** [comment]
@rmadaka I have verified this, It works now, please check and if it's not reproducible please close this issue.

**Comment by rmadaka** [comment]
```glustercli peer add dhcp35-194
Peer add successful
+--------------------------------------+-----------------------------------+--------------------+--------------------+
|                  ID                  |               NAME                |  CLIENT ADDRESSES  |   PEER ADDRESSES   |
+--------------------------------------+-----------------------------------+--------------------+--------------------+
| 46b846fd-32e8-4046-9080-fb827413ccff | dhcp35-194.lab.eng.blr.redhat.com | 127.0.0.1:24007    | dhcp35-194:24008   |
|                                      |                                   | 10.70.35.194:24007 | 10.70.35.194:24008 |
```

currently peer add with short names working.
