### ISSUE TITLE
cli: Unify --glusterd-{host,https,port} into a single --endpoints option

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#834]
Current options:

```sh
[ppai@gd2-1 glusterd2]$ glustercli --help
Gluster Console Manager (command line utility)

Usage:
  glustercli [command]

Available Commands:
  bitrot          Gluster Bitrot
  device          Gluster Devices Management
  events          Gluster Events
  geo-replication Gluster Geo-replication
  help            Help about any command
  peer            Gluster Peer Management
  snapshot        Gluster Snapshot Management
  volume          Gluster Volume Management

Flags:
      --cacert string          Path to CA certificate
      --glusterd-host string   Glusterd Host (default "localhost")
      --glusterd-https         Use HTTPS while connecting to Glusterd
      --glusterd-port int      Glusterd Port (default 24007)
  -h, --help                   help for glustercli
      --insecure               Accepts any certificate presented by the server and any host name in that certificate.
      --json                   JSON Output
      --loglevel string        Severity of messages to be logged (default "INFO")
  -v, --verbose                verbose output
      --xml                    XML Output

```

**Comment by prashanthpai** [comment]
@Madhu-1 It's good to implement this with `etcdctl`'s `--endpoints=` option as a reference for usability

**Comment by aravindavk** [comment]
I prefer having that as additional option. With the default setup, if only port is different then it is easy to specify port using `--glusterd-port` than specifying `--endpoints` with complete URL

**Comment by prashanthpai** [comment]
> With the default setup, if only port is different then it is easy to specify port using --glusterd-port

There can be multiple interfaces on the same machine and glusterd2 can be configured to be listening on one of them.

It's less ambiguous if it's more explicit. It will also reduce the number of options we expose (3 to 1). As an example - `http://127.0.0.1:xxxx` or  `http://localhost:xxxx` isn't so hard to specify. FWIW, the name `endpoint` is used as convention in etcd, OpenStack, OpenShift and a lot of places.
