### ISSUE TITLE
Unified Volume Create API and mount bricks on Glusterd2 start

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#851]
Based on the comments in PR #661, listed the fixes required for Smart Volume Create API

- Single REST API `/volumes` and auto provision bricks if size is specified.
- Volume name as optional parameter
- Mount bricks on Glusterd2 start or Volume Start 
- Save device/lv details in `brick.MountInfo`(This structure is added by Snapshot feature, useful here also. We can even skip custom `fstab` logic since this is sufficient for mounting bricks on Glusterd2 start)
- Add `omitempty` for optional API parameters

**Comment by aravindavk** [comment]
I will open new issues for each of the following tasks and move out of `GCS-Sprint1`

> Auto distribute count: If Distribute count is not specified and disk space is not enough to create volume, try again with increased distribute count till all the bricks can be planned(till max distribute count)

> Arbiter brick size calculation: Introduce configurable option for average file size with good default value. Apply the formula while planning arbiter brick

> Global defaults should be configurable: Default replica count, Default Snapshot reserve factor, etc should be configurable via API/Config

> Add support for multiple filesystem types(Default to xfs)

**Comment by atinmu** [comment]
Moving this to Sprint 2 as there's good amount of work required to complete all of the issues referenced.

**Comment by aravindavk** [comment]
> Moving this to Sprint 2 as there's good amount of work required to complete all of the issues referenced.

Patch #973 posted for the tasks other than the new issues opened. It can be merged if somebody reviews it.

**Comment by aravindavk** [comment]
@atinmu updated status in first comment.

**Comment by aravindavk** [comment]
Updated title and description of issue

**Comment by aravindavk** [comment]
Closing this issue since #973 is merged.
