### ISSUE TITLE
Intelligent Volume Expand

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#852]
To expand a Volume which is created using intelligent Volume provisioner,

- Collect expand size as API input
- Get existing sub volume size
- if expand size > sub volume size, then `number_of_new_subvols = ceil(expand_size / subvol_size)`
- Number of new bricks required = num_bricks_in_existing_subvol * number_of_new_subvols
- Expand defaults based on existing sub volumes(File system type, replica count, disperse count etc)
- Plan brick layout based on above information
- Reuse the prepare bricks transaction steps
- Reuse the Volume expand Transaction steps

Replica count can be increased or decreased if size=0 and replica_count is given and different than existing replica_count.

Please add if any other cases needs to be handled.

**Comment by raghavendra-talur** [comment]
@aravindavk we also discussed that there should be a way to retain the subvol count the same and use expansion feature of underlying partition. This needs to be checked for feasibility and documented if not possible.

**Comment by aravindavk** [comment]
In case of Volume expand by Brick resize:

- Collect expand size as API input
- Expand size = Expand size given / number of subvolumes
- For each brick, check If device free size > expand size. Error if space is not sufficient
- Run `lvresize` on all bricks (Refer: https://www.systutorials.com/5621/extending-a-mounted-ext4-file-system-on-lvm-in-linux/ or any other blog)
- Update the devices size after resize
- Update Volume size in Volinfo

**Comment by Madhu-1** [comment]
@aravindavk can we remove `GCS/0.3` tag from this issue, as we are not supporting volume expand in GCS as of now.

**Comment by aravindavk** [comment]
Volume Expand feature is available by increasing the brick size using `lvresize`. Opened new issue to expand Volume by automatically adding subvolume https://github.com/gluster/glusterd2/issues/1382
