### ISSUE TITLE
Multi node transaction framework support

### ISSUE THREAD

**Issue by atinmu** [gluster/glusterd2#88]

**Comment by kshlm** [comment]
#90 introduces transactions spanning multiple nodes. Initial implementation used the `volume-create` command to test the framework. Other existing commands will be migrated soon.

**Comment by kshlm** [comment]
#123 and #124 migrated the other commands to the multi-node txn framework

**Comment by atinmu** [comment]
@kshlm  can this be closed now?

**Comment by prashanthpai** [comment]
Only peer operations are out of the purview of transaction framework, which is expected. All other operations currently implemented have been ported to use transaction framework. @kshlm can chime in and close this if there's nothing additional to be done here.
