### ISSUE TITLE
SHD is not healing the files

### ISSUE THREAD

**Issue by karthik-us** [gluster/glusterd2#890]
Even though the shd is started and connected to all the bricks, it is not healing the files which are pending heal.

**Comment by karthik-us** [comment]
@aravindavk, @vpandey-RH can any one of you take a look at this?

**Comment by itisravi** [comment]
@karthik-us you might want to explain the imshd part.

**Comment by karthik-us** [comment]
In the gd1 shd graph for every subvol in a replicated/distributed-replicated volume the option
"option iam-self-heal-daemon yes"
will be set, which is missing in the gd2 shd graph. That might be causing the issue.

**Comment by aravindavk** [comment]
I will add that missing option, it should be added under `type cluster/replicate` right?

**Comment by itisravi** [comment]
It applies for both EC and AFR.

**Comment by aravindavk** [comment]
@itisravi thanks. Is it possible to paste the sample glustershd volfile from glusterd1?

**Comment by itisravi** [comment]
http://termbin.com/htqq has the sample output.  If not already there, all the below volume options need to be enabled when shd volfile is created:

```
volume testvol-replicate-0
    type cluster/replicate
    option iam-self-heal-daemon yes
    option use-compound-fops off
    option self-heal-daemon enable
    option entry-self-heal on
    option data-self-heal on
    option metadata-self-heal on
    option background-self-heal-count 0
    option afr-pending-xattr testvol-client-0,testvol-client-1,testvol-client-2
    subvolumes testvol-client-0 testvol-client-1 testvol-client-2
end-volume
```

**Comment by aravindavk** [comment]
One more issue I need to address. Reopened the issue for the same
