### ISSUE TITLE
Let bricks choose their own port

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#924]
The current way of glusterd2 picking ports for bricks is racy and we often see e2e test failures related to that. We must let the bricks pick their own ports.

**Comment by amarts** [comment]
@prashanthpai we need to discuss and detail out the tasks here. This can be decent amount of work. Lets see what is the minimum we have to do to handle the races, and what is the 'ideal' solution in long run.

**Comment by prashanthpai** [comment]
> This can be decent amount of work.

@amarts That's right. I'm optimistic that we can build upon prior work done by Prasanna here:

https://review.gluster.org/#/c/14670/
https://review.gluster.org/#/c/14613/
https://review.gluster.org/#/c/14671/

To further reduce the amount of work and to not introduce new regression, unlike the patches above, we can consider to omit corresponding changes in glusterd1 and limit this change to glusterd2.

**Comment by atinmu** [comment]
Would be interested to know how with out GD1 changes this can be taken care of.

In anyways, I’d suggest when we build up brick multiplexing support in GD2, we take care of this part.

^^ @rtalur

**Comment by prashanthpai** [comment]
> Would be interested to know how with out GD1 changes this can be taken care of.

gd2 case: If brick-port is not passed as an argument while spawning brick, glusterfsd will bind to a free port.

gd1 case: Glusterd1 will continue to explicitly set a brick-port as command line arg when spawning brick process. No change will be made there.

In both cases, brick process will report the port used by it to glusterd{1,2} in the `SIGN IN` request.

**Comment by prashanthpai** [comment]
Marking this as a GCS blocker as this can be a dependency for brick multiplexing  https://github.com/gluster/glusterd2/issues/219

cc @atinmu

**Comment by prashanthpai** [comment]
@amarts patch (https://review.gluster.org/#/c/glusterfs/+/21249/) that does the necessary changes in glusterfs code has been merged. Corresponding change in glusterd2 will be done soon.

**Comment by amarts** [comment]
Also note, as firewall setting was one of the concerns on the newer approach, we need an option for hook scripts (or eventsapi), which can get the new port as the argument, and opens the ports properly!

This should be documented as well!

**Comment by prashanthpai** [comment]
@amarts Yes, that's required. However, I see it as an improvement though. Your change doesn't introduce any regression.

Currently, firewall is configured as follows:
https://github.com/gluster/glusterfs/blob/master/extras/firewalld/glusterfs.xml#L13 i.e we open a range (512) of ports for bricks in firewalld.

An admin can still use the same firewall configuration and set `sysctl -w net.ipv4.ip_local_port_range="49152 49664"`. This will ensure that linux kernel will allocate a ephemeral port only in the specified range.

**Comment by amarts** [comment]
> An admin can still use the same firewall configuration and set sysctl -w net.ipv4.ip_local_port_range="49152 49664". This will ensure that linux kernel will allocate a ephemeral port only in the specified range.

Document it please! While lot of this is expected to be known by Admin, having it clearly documented makes the product fool proof!

**Comment by nbalacha** [comment]
Question: Are the range of brick ports opened automatically in the firewall or only those that are actually used by the gluster bricks? Or is this to be done by the admin?

**Comment by prashanthpai** [comment]
Currently, during RPM install, a firewalld service file gets installed. This file has a range of ports that firewalld shall open (automatically):
https://github.com/gluster/glusterfs/blob/master/glusterfs.spec.in#L1494-L1496
https://github.com/gluster/glusterfs/blob/master/extras/firewalld/glusterfs.xml#L13

However, the admin has to tell the linux kernel to allocate ports to brick only in the range specified in the firewalld config:
See: https://github.com/gluster/glusterd2/blob/master/doc/network.md#firewall-configuration

**TODO**:  I'm working on integrating dbus support in glusterd2 which will enable glusterd2 to notify firewalld to open only those ports used by bricks.

**Comment by nbalacha** [comment]
> Currently, during RPM install, a firewalld service file gets installed. This file has a range of ports that firewalld shall open (automatically):
> https://github.com/gluster/glusterfs/blob/master/glusterfs.spec.in#L1494-L1496
> https://github.com/gluster/glusterfs/blob/master/extras/firewalld/glusterfs.xml#L13
> 
> However, the admin has to tell the linux kernel to allocate ports to bricks only in the range specified in the firewalld config:
> See: https://github.com/gluster/glusterd2/blob/master/doc/network.md#firewall-configuration
> 

I see this is already considered. My concern was that if there is no way to prevent other processes from being assigned ports in this range, this becomes a security issue.

> **TODO**: I'm working on integrating dbus support in glusterd2 which will enable glusterd2 to notify firewalld to open only those ports used by bricks.

This sounds good. So glusterd2 is responsible for ensuring that only the ports used by the currently running brick processes are opened.

**Comment by prashanthpai** [comment]
> My concern was that if there is no way to prevent other processes from being assigned ports in this range, this becomes a security issue.

There is still no such provision to prevent other processes from binding to these ports. I'm guessing that selinux may have some provision for something like that. The sysctl parameter `net.ipv4.ip_local_port_range` is a system-wide change, so is the above firewalld configuration.

> So glusterd2 is responsible for ensuring that only the ports used by the currently running brick processes are opened.

That's right.
