### ISSUE TITLE
volume option not found shard.shard

### ISSUE THREAD

**Issue by greatwar** [gluster/glusterd2#954]
gd2 report shard.shard option not found, which named features.shard in gd1.but option shard.shard-block-size accepted by gd2.

after search the doc/issues/sources .  gd2 load options from xlator.so , but only shard-block-size defined in xlator options: (from  [src of shard.c](https://github.com/gluster/glusterfs/blob/release-4.1/xlators/features/shard/src/shard.c))
```
struct volume_options options[] = {
        {  .key = {"shard-block-size"},
           .type = GF_OPTION_TYPE_SIZET,
           .op_version = {GD_OP_VERSION_3_7_0},
           .flags = OPT_FLAG_SETTABLE | OPT_FLAG_CLIENT_OPT | OPT_FLAG_DOC,
           .tags = {"shard"},
           .default_value = "64MB",
           .min = SHARD_MIN_BLOCK_SIZE,
           .max = SHARD_MAX_BLOCK_SIZE,
           .description = "The size unit used to break a file into multiple "
                          "chunks",
        },
        { .key = {NULL} },
};
```

so how to enable shard feature in gd2?

**Comment by aravindavk** [comment]
Thanks for reporting the issue. Currently gd2 expects `<xlator-name>.<option>`, but in this case `shard` enable option was only maintained in Glusterd1 and not in shard xlator. We will work on the fix.

**Comment by aravindavk** [comment]
> Can sharding become a volume type instead? It makes more sense that way as we cannot disable it once enabled.

https://github.com/gluster/glusterd2/issues/853

**Comment by aravindavk** [comment]
With PR #1376, this can be enabled using `glustercli volume set <volname> features/shard on`
