### ISSUE TITLE
quota limit set

### ISSUE THREAD

**Issue by harigowtham** [gluster/glusterd2#963]
Enabling the limit set operation on the quota enabled volumes through GD2

**Comment by harigowtham** [comment]
https://github.com/gluster/glusterd2/pull/703 is the PR this change is being worked on

**Comment by atinmu** [comment]
I'm moving this to Sprint 2 given we have higher priority items to be delivered by Sprint 1. Development work on this PR can continue.

**Comment by aravindavk** [comment]
Closing this issue since existing quota feature will be discontinued in glusterfs. Please open new issue when design for new Quota feature is available.
