### ISSUE TITLE
Validation of volume set (xlator) options for client side xlators

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#968]
As we load shared objects of xlator during startup of glusterd2, the client xlators may not be present on the node where glusterd2 is installed. In that case, xlator options of client xlators aren't loaded. Hence glusterd2 doesn't know about those client options and can't validate them. Should packaging be done in such a way that client xlators are installed on system which has glusterd2 ?

**Comment by kshlm** [comment]
Client xlators are always installed on servers. The glusterfs-server package always pulls in glusterfs-client package. To this is a non-issue almost always.

**Comment by prashanthpai** [comment]
> Client xlators are always installed on servers. The glusterfs-server package always pulls in glusterfs-client package. To this is a non-issue almost always.

Thanks for clarifying. There's nothing else to be done here then :)
