### ISSUE TITLE
Implement Index and Full Heal API and CLI

### ISSUE THREAD

**Issue by vpandey-RH** [gluster/glusterd2#972]
Related to [#427](https://github.com/gluster/glusterd2/issues/427). This feature needs to be completed in GCS-Sprint1. The rest of the self heal APIs will be targeted  for GCS-Sprint2.

**Comment by vpandey-RH** [comment]
@atinmu As dicussed in the standup today, this is the [#bug](https://bugzilla.redhat.com/show_bug.cgi?id=1240658), that needs to be addressed  in relation to full heal before we implement it in GD2.

**Comment by atinmu** [comment]
@vpandey-RH I still don't understand how the work on GD2 can be blocked because of GD1's missing functionality. Also better to talk about upstream BZs which is https://bugzilla.redhat.com/show_bug.cgi?id=1240658 . 

@itisravi any pointers here?
