### ISSUE TITLE
Mount Snapshot Brick on glusterd restart 

### ISSUE THREAD

**Issue by rafikc30** [gluster/glusterd2#974]
Snapshot bricks, Bricks of cloned volume and bricks of restored volume should mandatorily do a check to see bricks are mounted or not during a volume start. This is essential in case of a node reboot where the mount point won't be present in the machine.

**Comment by aravindavk** [comment]
@rafikc30  Is this fixed now?

**Comment by rafikc30** [comment]
This is fixed using the pull request https://github.com/gluster/glusterd2/pull/1053
