### ISSUE TITLE
glusterd2 v4.0dev-7 fails to start, errors out with: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by sac** [gluster/glusterd2#975]
I'm running glusterd2 version v4.0dev-7, fails with error:

INFO[2018-07-09T16:25:38+05:30] gd2-muxserver: Failed service '(*sunrpc.SunRPC)(nil)' (4.999918 failures of 5.000000), restarting: true, error: runtime error: invalid memory address or nil pointer dereference, stacktrace: goroutine 316 [running]:                                                   
github.com/gluster/glusterd2/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1.1(0xc4204a7dc0, 0x1)                                   
        /home/kaushal/go/src/github.com/gluster/glusterd2/vendor/github.com/thejerf/suture/supervisor.go:448 +0xbc                                  
panic(0xff62a0, 0x19ca2c0)
        /usr/lib/go/src/runtime/panic.go:489 +0x2cf
github.com/gluster/glusterd2/servers/sunrpc.(*SunRPC).Serve(0x0)
        /home/kaushal/go/src/github.com/gluster/glusterd2/servers/sunrpc/server.go:112 +0x77                                                        
github.com/gluster/glusterd2/vendor/github.com/thejerf/suture.(*Supervisor).runService.func1(0xc4204a7dc0, 0x1, 0x19e3600, 0x0)                     
        /home/kaushal/go/src/github.com/gluster/glusterd2/vendor/github.com/thejerf/suture/supervisor.go:454 +0x63                                  
created by github.com/gluster/glusterd2/vendor/github.com/thejerf/suture.(*Supervisor).runService                                                   
        /home/kaushal/go/src/github.com/gluster/glusterd2/vendor/github.com/thejerf/suture/supervisor.go:457 +0x5b                                  
  supervisor=gd2-servers
INFO[2018-07-09T16:25:38+05:30] Entering the backoff state.                   supervisor=gd2-muxserver 

Attaching complete error log.
[console.log](https://github.com/gluster/glusterd2/files/2175857/console.log)

**Comment by prashanthpai** [comment]
@sac Please use the latest nightly build from here http://artifacts.ci.centos.org/gluster/gd2-nightly/
