### ISSUE TITLE
Implement Delete all command in snapshot

### ISSUE THREAD

**Issue by rafikc30** [gluster/glusterd2#976]
Snapshot should implement delete all command that deletes all the snapshot in the volume. It should also have the capability to delete all snapshots of a particular volume.

**Comment by rafikc30** [comment]
Implementing delete all command for the snapshot is not easy. Given that we have to acquire a lock on all the snapshots marked for deletion plus their parent volumes. Even if we managed to do that, it will be a time-consuming operation where the rest client has to wait.

Implementing delete all operation in glustercli is not that difficult. Where we can get the list of snapshots first and then sent delete command one by one. In this case, We don't need to worry about the timeout, Also we can see the progress of the operation. This is the approach taken in gd1 one to implement delete all cli.

**Comment by amarts** [comment]
@rafikc30 I like the approach, and we should only do it this way. It is tool which should do it, and APIs should be provided for doing one small thing.

**Comment by rafikc30** [comment]
@amarts also I was wondering comments like snapshot status, snapshot info should be restricted to one snapshot. Is it really helpful for a customer to Print all snapshots/volumes with status/info on stdout or as a rest api response. It will be more confusing, given that we will have number volumes as high. IMHO, it makes more sense to have list all followed by status or info of a particular entity.

**Comment by amarts** [comment]
Agree! Let the API deal with only one volume at a time, and cli (or any other high level tool) consuming can list the status, list by doing the iteration on all the volumes.

**Comment by aravindavk** [comment]
Fixed with PR https://github.com/gluster/glusterd2/pull/1241
