### ISSUE TITLE
Improper error message for failed REST authentication

### ISSUE THREAD

**Issue by prashanthpai** [gluster/glusterd2#993]
```sh
$ glustercli peer list
Failed to get Peers list

Error: Request failed with HTTP Status code 401
invalid character 'A' looking for beginning of value
```

I pulled the latest glusterd2 changes which presumably had the change which turns on REST authentication by default.

**Comment by aravindavk** [comment]
@Madhu-1 please look into this. Is this related to the restauth changes?

**Comment by Madhu-1** [comment]
@aravindavk this is not related to recent changes, this is due to the error handling when we get an unexpected status code in restclient.
