### ISSUE TITLE
Auto distribute count for Intelligent Volume Provisioning

### ISSUE THREAD

**Issue by aravindavk** [gluster/glusterd2#999]
Current dynamic Volume create API accepts distribute count as input and defaults to 1 if no distribute count is specified. New feature is required to find distribute count automatically based on given Volume size and available size.

If Distribute count is not specified and disk space is not enough to create volume, try again with increased distribute count till all the bricks can be planned(till max distribute count)

**Comment by aravindavk** [comment]
Issue #851 is split into multiple issues. This is one among them

**Comment by aravindavk** [comment]
Alternate idea compared to Iterative method till max distribute count: New API tunable `max-brick-size`.

    if (requested-size > max-brick-size) 
    {
        distribution_count = int(requested-size / max-brick-size);
        if (requested-size % max-brick-size > 0)
        {
            distribution_count++;
        }
    }

**Comment by JohnStrunk** [comment]
I like the notion of having `max-brick-size` as it makes efficient bin packing easier when item size is constrained.
